### ISSUE TITLE
Call recordings instances have wrong uri

### ISSUE THREAD

**Issue by alexcchan** [twilio/twilio-php#130]
If you retrieve call recordings, the instances have uri values like this:

/2010-04-01/Accounts/AC.../Calls/CA.../Recordings/RE...

instead of:

/2010-04-01/Accounts/AC.../Recordings/RE...

It looks like the issue is how ListResource calculates the new uri:

https://github.com/twilio/twilio-php/blob/master/Services/Twilio/ListResource.php#L53

I'm not sure how to fix it.  Maybe override getObjectFromJson in Recordings.php?

**Comment by ihumanable** [comment]
The 5.x line handles this correctly by populating the uri from the response instead of attempting to construct it.  The 4.x line has been put into maintenance mode, this is a minor bug and will be closed in favor of upgrading to the 5.x line.
