### ISSUE TITLE
Error while Installing Twilio PHP helper Libraries on Windows OS (32-bit)

### ISSUE THREAD

**Issue by laxmikantD** [twilio/twilio-php#159]
I am facing issue while running command: "pear channel-discover twilio.github.com/pear"

Error snippet: "Trying to discover channel twilio.github.com/pear over https:// instead
Discovery of channel "twilio.github.com/pear" failed (channel-add: Cannot open "
https://twilio.github.com/pear/channel.xml" (Connection to `twilio.github.com:44
3' failed: A connection attempt failed because the connected party did not prope
rly respond after a period of time, or established connection failed because con
nected host has failed to respond."

Here is the PEAR version details:
PEAR Version: 1.9.4
PHP Version: 5.3.20
Zend Engine Version: 2.3.0
Running on: Windows NT PS8436 5.2 build 3790 (Windows Server 2003 Enterprise Edition Service Pack 2) i586

I tried running these commands on different test machines but still getting same error . Can anyone help me to resolve this problem?

**Comment by ihumanable** [comment]
4.x and 5.x are now delivered through as composer packages, closing as out of date.
