### ISSUE TITLE
static:: not available in PHP 5.2 (again)

### ISSUE THREAD

**Issue by alexcchan** [twilio/twilio-php#169]
This line causes parse errors in PHP 5.2

https://github.com/twilio/twilio-php/blob/master/Services/Twilio.php#L71

Parse error: syntax error, unexpected T_STATIC in /path to file/Services/Twilio.php on line 71

**Comment by alexcchan** [comment]
Another occurrence

https://github.com/twilio/twilio-php/blob/master/Services/Twilio.php#L238

**Comment by efossier** [comment]
We've completely rewritten the library for 5.x, please upgrade and let us know if this is still an issue.
