### ISSUE TITLE
JSON not being retained during pagination for usage records?

### ISSUE THREAD

**Issue by rezakazemi** [twilio/twilio-php#170]
When requesting sms-outbound usage records (for example), it looks like the php library is trying to hit the following URL:

/2010-04-01/Accounts/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/Usage/Records/Daily?Category=sms-outbound&StartDate=2014-01-01&EndDate=2014-03-01&Page=1&PageSize=50

Which obviously won't work as it doesn't contain the necessary '.json' after the 'Daily'. Twilio therefore sends back XML instead of JSON and the php library barfs. 

This only happens when there are more than 50 records and pagination comes into play.

In Twilio.php, work is being done to manually add the '.json' to paths that are full_uri=false (even ones with a query string to build), but it seems this one is sneaking past, as it is flagged as a full_uri=true (see getRequestUri function declaration).

My suggestion is verifying in all cases that the last thing before the start of the query string is a literal '.json' whether or not a full_uri=true path is being supplied to getRequestUri.

Sorry if my explanation is unclear.

**Comment by gontham** [comment]
Ran into the same issue.

Here is the temp fix I used:
```PHP
 public static function getRequestUri($path, $params, $full_uri = false) {
    	$json_path = $full_uri ? $path : "$path.json";
        
        if (!$full_uri && !empty($params)) {
            $query_path = $json_path . '?' . http_build_query($params, '', '&');
        } else {
        	//BUG FIX START
        	list($path,$params) = explode("?",$json_path);
        	if(preg_match("/\.json$/",$path) !== 1)$path.=".json";
        	$json_path = implode("?",array($path,$params));
        	//BUG FIX END        	        	
            $query_path = $json_path;
        }
        return $query_path;
    }
```

**Comment by plabbett** [comment]
Tracked down a "This likely indicates a 500 server error" when trying to pull usage reports and gontham's fix mentioned above fixes it for me. Outbound Voice and Voice Minutes categories specifically were being pulled as XML and failing when being put through json_decode()

**Comment by peardox** [comment]
I always find it best to use a webhook for usage, for outbound a callback is a neat solution as well

I'm somewhat annoyed with twilio-php, it promises much but fails to deliver in all but the simplest cases

I think it's time we had something better so as I'm funded (for the coming month) I think I'll write something that does what we want as opposed to what they provide

**Comment by davidquarles** [comment]
Experiencing the exact same thing.  The fix @gontham suggested seems to work but forking this repo and hacking at our composer config isn't exactly an ideal or sustainable solution.  I received an email just the other day [announcing](http://s815114181.t.en25.com/e/er?s=815114181&lid=2016&elq=c68e7309625f42bfb0eb82f70ea3a7db&elqaid=1910&elqat=1&elqTrackId=bf90ff588f86485889719f53992e6d73) that pagination for ListResources will be deprecated on 9/14.  Does anyone know if this bug will be fixed by that release, or should we submit a pull request ourselves?

**Comment by efossier** [comment]
We've completely rewritten the library for 5.x, please upgrade and let us know if this is still an issue.
