### ISSUE TITLE
Error when using web proxy on 3.12.2

### ISSUE THREAD

**Issue by jasonborden** [twilio/twilio-php#182]
I'm using a web proxy with twilio-php (Using CURLOPT_PROXY) to send sms messages. When using a proxy I get a "PHP Notice:  Undefined variable: headers in /<path>/Services/Twilio/TinyHttp.php on line 109". Then it throws an exception "Could not decode response body as JSON. This likely indicates a 500 server error". My message is still sent properly, but the response is not properly parsed when using a proxy.

**Comment by svigneux** [comment]
+1, it would be nice to have this issue fixed.  
thanks!

**Comment by nodefortytwo** [comment]
Its been two years, there is a valid pull request and yet this still hasn't been fixed?

**Comment by LukeXF** [comment]
I agree, would love for this to be added

**Comment by efossier** [comment]
We've rewritten the library from the ground up for the 5.x releases and are therefore no longer adding features to older versions, please upgrade and let us know if you still need this functionality.
