### ISSUE TITLE
Services_Twilio_Twiml say('0') says nothing

### ISSUE THREAD

**Issue by emilebourquin** [twilio/twilio-php#184]
<?php
    require('./twilio-php-master/Services/Twilio.php');

    header('Content-Type: text/xml');

    $response = new Services_Twilio_Twiml();
    $response->say('0');
    print $response;

responds with:

    <?xml version="1.0" encoding="UTF-8"?>
    <Response><Say/></Response>

**Comment by ihumanable** [comment]
Fix for the 5.x line is here https://github.com/twilio/twilio-php/pull/357

**Comment by ihumanable** [comment]
5.x line updated
