### ISSUE TITLE
Error in the twilio-php library

### ISSUE THREAD

**Issue by joelgerber** [twilio/twilio-php#186]
I'm getting this error when trying to send an SMS using the twilio-php client. Any thoughts?

Warning: file_get_contents(https://api.twilio.com/2010-04-01/Accounts/AC759b680145e820d5fc0607ed52d818a3/Messages.json) [function.file-get-contents]: failed to open stream: HTTP request failed! HTTP/1.1 400 BAD REQUEST in E:\wamp\www\twilio\reminders\Services\Twilio\HttpStream.php on line 62

Fatal error: Uncaught exception 'Services_Twilio_HttpStreamException' with message 'Unable to connect to service' in E:\wamp\www\twilio\reminders\Services\Twilio\HttpStream.php:65 Stack trace: #0 [internal function]: Services_Twilio_HttpStream->__call('/2010-04-01/Acc...', Array, 'From=6146298870...') #1 E:\wamp\www\twilio\reminders\Services\Twilio.php(228): Services_Twilio_HttpStream->post('/2010-04-01/Acc...', Array) #2 E:\wamp\www\twilio\reminders\Services\Twilio\ListResource.php(92): Services_Twilio->createData(Array) #3 E:\wamp\www\twilio\reminders\Services\Twilio\Rest\Messages.php(24): Services_Twilio_ListResource->_create(Array) #4 E:\wamp\www\twilio\reminders\simulate.php(22): Services_Twilio_Rest_Messages->create() #5 {main} thrown in E:\wamp\www\twilio\reminders\Services\Twilio\HttpStream.php on line 65

**Comment by efossier** [comment]
We've completely rewritten the library for 5.x, please upgrade and let us know if this is still an issue.
