### ISSUE TITLE
Implement namespaces

### ISSUE THREAD

**Issue by henrikhj** [twilio/twilio-php#187]
With both PHP 5.2 and PHP 5.3 now having reached EOL and are no longer maintained, it would be a good time to implement namespaces and adopt the PSR-0 and PSR-4 standards for the library.
This will make it much more streamlined for implementation in existing projects and also improve the structure of the code.

**Comment by AndrolGenhald** [comment]
https://github.com/AndrolGenhald/twilio-php

What else needs to be changed? I haven't gotten around to changing a lot of the documentation, and I know there's some pear stuff in there that should be updated; is there anything else?

**Comment by rlmckenney** [comment]
Hi, I was looking for this too.  

I checked out the fork by AndrolGenhald.  At first glance it does not seem to be [PSR-4 compliant](http://www.php-fig.org/psr/psr-4/).  It does not utilize fully qualified namespaces and there is more than one class in some of the files.

It would be really great if the Twilio team updated this library.

**Comment by henrikhj** [comment]
I agree that Twilio should assume responsibility for their own library. But the work done by AndrolGenhald seems like a big step in the right direction, even though I have just had a quick glance.

@AndrolGenhald May I ask if you represent Twilio or just a helpful soul?

**Comment by AndrolGenhald** [comment]
Just another user trying to fix things up a bit :)
I'll see if I can get around to reading the PSR-4 spec and start implementing it next week.

**Comment by ecaron** [comment]
@skimbrel Can this get flagged as a blocker for the 5.0.0 release?

**Comment by skimbrel** [comment]
You bet. I can't go into detail on here but 5.0 is going to be a very big and exciting release. You'll know when it gets here :)

**Comment by ihumanable** [comment]
5.x has been release with full namespace support.
