### ISSUE TITLE
Unable to filter by "DateCreated>"

### ISSUE THREAD

**Issue by bkuhl** [twilio/twilio-php#189]
I'm attempting to query all messages sent to a phone number in the last 15 seconds.  Unfortunately it doesn't appear to be filter the results correctly.

My code:

```php

        $createdAfter = Carbon::now()->subSeconds(15)->format(Carbon::RFC2822);

        /** @var \Services_Twilio_AutoPagingIterator $messages */
        $messages = $this->twilioClient->account->messages->getIterator(0, 50, [
            'Direction'     => 'inbound',
            'To'            => '+1'.self::NUMBER,
            'Body'          => 'Test',
            'DateCreated>'  => $createdAfter
        ]);

        foreach ($messages as $message) {
            var_dump($message->date_created); // string(31) "Wed, 03 Sep 2014 15:24:40 +0000"
            var_dump($createdAfter); // string(31) "Wed, 03 Sep 2014 15:43:52 +0000"
            exit;
        }
        exit('no messages');
```
I'd expect to see `no messages` in the output, but messages keep being returned.

I've tried formatting the date several different ways with no luck:
```
string(31) "Wed, 03 Sep 2014 15:24:40 +0000"
string(31) "Wed, 03 Sep 2014 15:43:52 +0000"
```
```
string(31) "Wed, 03 Sep 2014 15:24:40 +0000"
string(19) "2014-09-03 15:47:09"
```

The syntax appears to be correct based on https://github.com/twilio/twilio-php/blob/master/Services/Twilio/ListResource.php#L175

**Comment by skimbrel** [comment]
The name of the field is also `DateSent` rather than `DateCreated` if filtering to today's messages is still useful for you.

**Comment by bkuhl** [comment]
Awesome, thanks!!
