### ISSUE TITLE
Library conflicts with firebase-token-generator-php

### ISSUE THREAD

**Issue by iameli** [twilio/twilio-php#192]
Hi,

It looks like both this library and https://github.com/firebase/php-jwt (a dependency of firebase-token-generator-php) both implement a class called "JWT". I included both packages in my Composer install and got lots of 

```
[07-Oct-2014 19:40:48 US/Eastern] PHP Fatal error:  Cannot redeclare class JWT in /var/composer/twilio/sdk/Services/Twilio/Capability.php on line 196
```

It looks like that class is only used in Capability.php. Any harm in changing it to `Twilio_JWT` or something?

Thanks!

**Comment by mikemclin** [comment]
:+1:   What's the status on this?

**Comment by mikemclin** [comment]
I just noticed that the new firebase/php-jwt v3.x.x package introduces namespaces. So, no more collisions.

**Comment by ihumanable** [comment]
Version 5.x has full namespacing as well now and should avoid any future collisions.
