### ISSUE TITLE
Call Iterator Doesn't Release Memory

### ISSUE THREAD

**Issue by djbusby** [twilio/twilio-php#199]
When using the Twilio SDK I try this:

    foreach ($st->account->calls->getIterator(0, 500) as $call) {
      // Something
    }

Over time, as I iterate through my 600k+ calls the script dies, after running out of memory (which is limited to 256M).  Using the 

    memory_get_usage()

routines as well as external profilers I can see memory usage continue to rise as the script goes on.

When I drop the Twilio SDK and use my own code (from https://github.com/edoceo/radix) to iterate the calls the memory consumption is level for the entire run of the script.  Something in Service_Twilio (3.12.6) is not letting go of my RAMs

**Comment by ihumanable** [comment]
Can you please retry with the latest version 5.x and reopen if still an issue.
