### ISSUE TITLE
Class 'TwimlException' not found	in cakephp Framework

### ISSUE THREAD

**Issue by Widrogo** [twilio/twilio-php#201]
hi, I am using cakephp Framework and when I use Services_Twilio_Twiml, always have this error:

Error: Class 'TwimlException' not found	
File: C:\xampp\htdocs\MyWeb\app\Vendor\Twilio\Services\Twilio\Twiml.php	
Line: 42

 if I comment this line I have this error:

Error: Call to a member function addChild() on a non-object	
File: C:\xampp\htdocs\MyWeb\app\Vendor\Twilio\Services\Twilio\Twiml.php	
Line: 106

well you can see what happen in my function:

public function index() {
                 $this->autoRender = false;
                 App::import('Vendor', 'Twilio', array('file' => 'Twilio'.DS.'Services'.DS.'Twilio.php'));
                $AccountSid = "acxxxxxxxxxxxxxxxxxxxxxxxxx";
                $AuthToken = "zxxxxxxxxxxxxxxxxxxxxxx";
		$response = new Services_Twilio_Twiml($AccountSid, $AuthToken);
		$gather = $response->gather(array('numDigits' => 10, 'finishOnKey' => '#', 'timeout' => 20, 'action' => 'http://www.xxxxx.com/twilio/check'));
		$gather->say("hola que tal presiona 1 emergencia presiona 2 ayuda", array('language' => 'es'));
		$response->say("bueno", array('language' => 'es'));

		$this->response->type('text/xml');
		$this->response->body($response);

		return $this->response;
	}

**Comment by alexw23** [comment]
+1
