### ISSUE TITLE
SSL certificate problem: self signed certificate in certificate chain 

### ISSUE THREAD

**Issue by prionkor** [twilio/twilio-php#203]
Hello,

I am upgrading from Twilio PHP Library from `v3.12.1` to `v3.12.6` Right away I am getting this error

> SSL certificate problem: self signed certificate in certificate chain

We are moving all dependency under composer support. Please let me know if there is any steps involved to upgrade. `v3.12.1` had an certificate file I do not see it on `v3.12.6` Please advice a workaround which allow us to connect via `https`

**Comment by Gipetto** [comment]
It might make sense to update the library docs with info about keeping certs up to date.

**Comment by prionkor** [comment]
Thanks, That fixes the issue :)

**Comment by JoseVallejo** [comment]
Hi! I have the same problem in R. Once I put my credentials for me to use Plotly I get

**Comment by JoseVallejo** [comment]
Hi! I have the same issue in R when using plotly. I would appreciate some help:
py <- plotly()
trace0 <- list(
  x = c(1, 2, 3, 4),
  y = c(10, 15, 13, 17)
)
trace1 <- list(
  x = c(1, 2, 3, 4),
  y = c(16, 5, 11, 9)
)
response <- py$plotly(trace0, trace1, kwargs=list(filename="basic-line", fileopt="overwrite"))
# Error in function (type, msg, asError = TRUE)  : 
#  SSL certificate problem: self signed certificate in certificate chain

**Comment by pflammer** [comment]
I have the same problem, but the suggested fix doesn't seem to work.

I have an updated cacert.pem file that is referenced in the php.ini file using curl.cacert, and I have tried the following code to try to update the cacert at runtime:
  $_http = new Services_Twilio_TinyHttp
    (
     "https://api.twilio.com",
     array("curlopts" => array
           (
            CURLOPT_USERAGENT => 'twilio-php/4.2.0',
            CURLOPT_HTTPHEADER => array('Accept-Charset: utf-8'),
            CURLOPT_CAINFO => '/etc/php5/cacert.pem'
            )
           )
     );
  $client = new Services_Twilio($AccountSid, $AuthToken,null,$_http);

Based on everything I've read that should fix it, but it doesn't. Setting:
            CURLOPT_SSL_VERIFYPEER => false
does fix the problem. Is there something I'm missing here?

**Comment by hairys** [comment]
That's because Twiilio's api server (api.twilio.com) presents *four* certificates to the client at the time of this writing. Three are used in the certificate chain. The extraneous cert is "Thawte Premium Server CA" that curl is complaining about. Incidentally, this cert isn't present in the latest cacert.pem. I added this cert to my cacert.pem and the problem is gone.
Care to elaborate why there's an unnecessary cert in the list guys?

**Comment by hairys** [comment]
Further reading reveals why. From [http://curl.haxx.se/docs/caextract.html](http://curl.haxx.se/docs/caextract.html):
> **RSA-1024 removed **
> Around early September 2014, Mozilla removed the trust bits from the certs in their CA bundle that were still using RSA 1024 bit keys. This may lead to TLS libraries having a hard time to verify some sites if the library in question doesn't properly support "path discovery" as per RFC 4158. (That includes OpenSSL and GnuTLS.)

"Thawte Premium Server CA" is a 1024-bit cert.
You can get it from [https://www.thawte.com/roots/thawte_Premium_Server_CA.pem](https://www.thawte.com/roots/thawte_Premium_Server_CA.pem)

**Comment by keyboardface** [comment]
Thank you! Adding the https://www.thawte.com/roots/thawte_Premium_Server_CA.pem into my cacert.pem fixed it for me as well.

**Comment by hoangmanh09it** [comment]
hairys thanks you. my problem have fixed :)

**Comment by juancruzhurtado** [comment]
Hey guys,

Having this exact same issue. It is driving me insane. I have followed all the instructions, but it is still not working!

Any other suggestions?

**Comment by vinitdave27** [comment]
I am also facing the same exact error. I have tried the solution mentioned above where in copy paste the contents of the thawte_premium_server_ca certificate into the cacert.pem. I have placed the same in the wamp_install_dir/certs directory and have updated the curl.cainfo=C:\wamp\certs\cacert.pem in the php.ini located in the wamp_install_dir/bin\apache\apache2.4.9\bin.

I have restarted the WAMP services and i am still facing the same issue. Any further troubleshooting steps/solution would be appreciated.

**Comment by anagio** [comment]
@vinitdave27 what is the output of `phpinfo()`? Check that your certificate file is loading

**Comment by vinitdave27** [comment]
@anagio Can you guide me to what exact parameter do you want to see in the phpinfo() page. Also, i am new to php....hence, can you tell me how to check if the certificates are loading correctly....i would really appreciate your help.

**Comment by baptistedonaux** [comment]
## Solution tried
I have  the same problem, but I don't find solution.

- I downloaded cacert.pem [here](http://curl.haxx.se/docs/caextract.html).
- I add in my php.ini this line
```php
curl.cainfo=/cacert.pem
```
- I restart my PHP-FPM.

When I call API with ```twilio/sdk```, I have already the same fail.

## My error
>  SSL certificate problem: self signed certificate in certificate chain 

## My configuration
- PHP 5.6.17
- What else ?

Do you have an idea ?

**Comment by nvanheuverzwijn** [comment]
Why is this close ? There is clearly a problem with twilio certificate as it is not valid in debian 8 stock install... Check hairys comment as it is very relevant to the problem Twilio has with it's certificate. Twilio certificate is not deemed secure by cUrl.

**Comment by rtek** [comment]
Please allow a way to inject the CA file into the HTTP client for the future releases. It allows the CA bundle to be packaged with the application for portability.

**Comment by carlosdp** [comment]
We're forwarding this to our security team to see if there's something we can do on our end. Will update in #285 when we have a plan of action. Thanks guys!

**Comment by jkrehm** [comment]
@rtek It's possible to inject a CA file into the HTTP client now (see pflammer's comment above), it's just not as easy as one would hope because of the current function and property visibility.

e.g

```
$httpClient = new Services_Twilio_TinyHttp(
    'https://api.twilio.com',
    array(
        'curlopts' => array(
            CURLOPT_USERAGENT  => Services_Twilio::qualifiedUserAgent(phpversion()),
            CURLOPT_HTTPHEADER => array('Accept-Charset: utf-8'),
            CURLOPT_CAINFO     => '/path/to/cacert.pem',
        ),
    )
);
```

But yeah, improving that in a future version would be awesome! Even if it's just making `_getBaseUri()` publicly visible.

**Comment by rtek** [comment]
@jkrehm Agreed! - I ended up doing that but I'm uncomfortable looking into the constructor for http client configuration details. Not a huge deal given the config options were rather benign.

**Comment by baptistedonaux** [comment]
Please make a feedback when issue will be closed. @carlosdp

**Comment by rmaddox** [comment]
That is bug in Debian, they removed some certificates. It will be resolved hopefully soon. Some solutions are already described here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812488

**Comment by hairys** [comment]
Not gone :)
![untitled](https://cloud.githubusercontent.com/assets/10733642/14369980/89ddb994-fcf7-11e5-866d-68cafa5fc905.png)
The fact that it's still being presented to clients means curl is going to freak out trying to validate the chain.

**Comment by jpasher-distribion** [comment]
I can confirm that the api.twilio.com servers are still sending the Thawte Premium Server CA in the certificate chain. All eight IP addresses that are used by api.twilio.com are sending them. You can see this in the Certification Paths section on SSL Labs:

https://www.ssllabs.com/ssltest/analyze.html?d=api.twilio.com&s=52.1.150.36&hideResults=on

Because the servers are sending the old 1024-bit Thawte Premium Server CA, it's causing systems without that certificate and running OpenSSL 1.0.1 (e.g. Debian 8) to fail due to the self-signed nature of the certificate. It needs to be removed from the chain that is being presented by the web server to the client.

**Comment by hairys** [comment]
For anyone having trouble locating your cacert.pem file, you can:

- *Linux/Unix* - Some distros like to use different paths for ca certs, use **strace** to attach to the php process handling requests and watch which files it attempts to open when it tries to connect to twilio. Look for paths that reference ssl or pem files.
- *Windows* - There is no default path setup for curl. You have to set it in php.ini (**curl.cainfo**) or set CURLOPT_CAINFO when initializing curl in your code.

**Comment by tveni** [comment]
In twilio\sdk\Twilio\Http\CurlClient.php
add 
 CURLOPT_SSL_VERIFYPEER => false,
after
CURLOPT_TIMEOUT => $timeout,  
This will solve the issue in local.  

$options = $this->curlOptions + array(
            CURLOPT_URL => $url,
            CURLOPT_HEADER => true,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_INFILESIZE => Null,
            CURLOPT_HTTPHEADER => array(),
            CURLOPT_TIMEOUT => $timeout,
          
        );
