### ISSUE TITLE
Message.php doesn't have a delete() method

### ISSUE THREAD

**Issue by alexcchan** [twilio/twilio-php#206]
Docs here:

https://github.com/twilio/twilio-php/blob/master/docs/usage/rest/messages.rst#redacting-or-deleting-messages

suggest using:

```
$message = $client->account->messages->get("MM123");
...
$message->delete(); // Deletes entire message record
```

however the only currently available method is:

```
$message = $client->account->messages->delete("MM123");
``

**Comment by skimbrel** [comment]
Fixed by @caseysoftware in #204.
