### ISSUE TITLE
Can't send valid SMS with test credentials

### ISSUE THREAD

**Issue by dan-peterson** [twilio/twilio-php#213]
Sending an SMS using the test credentials and magic test numbers fail when using a valid 'to' number with corresponding valid 'from' number.

Resulting error:
Exception 'Services_Twilio_RestException' with message 'Resource not accessible with Test Account Credentials'

This should work.Test numbers are listed here along with the expected results: https://www.twilio.com/docs/api/rest/test-credentials

The following should send an SMS under test mode, and succeed.

From: +15005550006 (This number passes all validation.)
To: Any non-test number (Any other phone number is validated normally.)

Spying on the CURL request reveals that the API end-point the SDK hits is structured like this:
/2010-04-01/Accounts/{TestAccountSid}/Messages.json

However the documentation specifies the end-point should be:
/2010-04-01/Accounts/{TestAccountSid}/**SMS**/Messages

Note that manually creating the POST request via POSTMan to the latter end-point, behaves as expected.

**Comment by skimbrel** [comment]
Unfortunately, the /SMS/Messages endpoint is deprecated, which is why the helper libraries stopped using it, and it looks like we missed out on enabling test credentials on the replacement /Messages endpoint. I can't promise a quick fix, but we'll do the right thing and get test /Messages going for you.

**Comment by ihumanable** [comment]
The Test API has been deprecated in favor of Network Layer mocking via the `Holodeck` helper.
