### ISSUE TITLE
Extract TinyHttp?

### ISSUE THREAD

**Issue by eddiezane** [twilio/twilio-php#214]
Digging the simplicity of the TinyHttp class. I began to write something very similar for the SendGrid PHP library because I wanted to maintain support for PHP 5.3 and use cURL without a heavy dependency. 

I started taking code from the class and realized it might be better as its own library. Would you be at all interested in doing this? If not I'd be more than happy to do so and of course credit Twilio and the original writer as per your license :smiley:.

**Comment by skimbrel** [comment]
I think it's probably a little more than we have bandwidth for but we'd probably be happy to replace the inlined class with a library reference. @ihumanable, thoughts?

**Comment by ihumanable** [comment]
Agree with you @skimbrel, we probably don't have the bandwidth to do the extracting and packaging up, but if @eddiezane would like to, we would welcome it and adopt it as a replacement for the inline class.

**Comment by eddiezane** [comment]
Thanks so much @skimbrel and @ihumanable! Will do and keep you updated.
