### ISSUE TITLE
Bug in hosted API

### ISSUE THREAD

**Issue by MikeRavenelle** [twilio/twilio-php#216]
The .zip has a bug in it that will not allow the developer to use the library causing error:

HP Fatal error:  Cannot redeclare Services_Twilio_autoload() 

Issue is in:

function Services_Twilio_autoload($className)
{
    if (substr($className, 0, 15) != 'Services_Twilio' && substr($className, 0, 26) != 'TaskRouter_Services_Twilio') {
        return false;
    }
    $file = str_replace('_', '/', $className);
    $file = str_replace('Services/', '', $file);
    return include dirname(__FILE__) . "/Twillio.php"; <<<<<<<<<<< should be /$file.php
}

**Comment by skimbrel** [comment]
This usually means you've required the library more than once in your code. Are you loading it with `require` or `require_once`?

**Comment by MikeRavenelle** [comment]
It was not an issue with require or require once. It is literally a wrong variable in the last line. By now it could have been fixed. Was only on the uploaded zip.

**Comment by philnash** [comment]
Hey @MikeRavenelle, I just checked and the latest zip, [version 4.0.4](https://github.com/twilio/twilio-php/releases/tag/4.0.4), seems to have this line correct. Could you try again? Thanks!
