### ISSUE TITLE
PHP Fatal error:  Cannot redeclare Services_Twilio_autoload()

### ISSUE THREAD

**Issue by piavgh** [twilio/twilio-php#218]
Hi everyone,

I use Phalcon PHP framework to make my web api. I use base project here https://github.com/jeteokeeffe/php-hmac-rest-api

Now I need to use Twilio for SMS.

I put twilio-php folder in library folder and then I included it in index.php

```php
require $appDir . '/library/twilio-php/Services/Twilio.php';
```

But I got this error 
```
"PHP Fatal error:  Cannot redeclare Services_Twilio_autoload() (previously declared in /usr/share/nginx/html/2way/api/app/library/twilio-php/Services/Twilio.php:9) in /usr/share/nginx/html/2way/api/app/library/twilio-php/Services/Twilio.php on line 9"
```

I checked this Twilio.php file and I tried to 

```php
var_dump(dirname(__FILE__) . "/Twilio.php"); die;
```

before this line 

```php
return include dirname(__FILE__) . "/Twilio.php";
```

The return value is 
```
string(73) "/usr/share/nginx/html/2way/api/app/library/twilio-php/Services/Twilio.php"
```

Which is the same file (Twilio.php)

Is this why I got the "Cannot redeclare Services_Twilio_autoload()" error?
How to solve this?

Thank you very much

**Comment by ecaron** [comment]
There are two options:
* The immediate cheap-and-dirty would be changing all your `require` and `include` to `require_once` and `include_once`
* Don't include Twilio directly, but instead put it in the `composer.json` file and rely on the composer autoloader to provide the class whenever you need it.

You also might find more appropriate assistance at [the Twilio tag on StackOverflow](http://stackoverflow.com/questions/tagged/twilio)

**Comment by piavgh** [comment]
Hi eracon,

Your first solution doesn't work, I tried that before posting this issue :)

But I am able to make it work now by making a single Twilio.php file that contain every class needed for SMS. This is maybe the dirtiest way but it works.

I wll close this issue now
