### ISSUE TITLE
How to add twilio to the providers list in laravel 5

### ISSUE THREAD

**Issue by hajindersingh645** [twilio/twilio-php#220]
Hi,

I have installed the Twilio SDK using composer, but now i don't know how and what command need to be entered into the APP.PHP file under providers list.

Can somebody help me in this regard?

Thanks

**Comment by hajindersingh645** [comment]
Any one here?

**Comment by mottihoresh** [comment]
The way I've done it the past is to have a Twilio controller, and within that controllers constructor class initialize the client.

```
class TwilioController extends Controller
{
    protected $client;

    function __construct(Setting $settings)
    {
     
        $sid = $this->settings->getByKey('twilio_sid');
        $auth_token = $this->settings->getByKey('twilio_auth_token');

        // Setup Twilio Content
        $this->client = new \Services_Twilio($sid, $auth_token);
        $this->token = new \Services_Twilio_Capability($sid, $auth_token);
    }

}
```

PS. that Settings class, is a Database model that store settings
