### ISSUE TITLE
Services_Twilio_Rest_Addresses missing create(...)

### ISSUE THREAD

**Issue by alexcchan** [twilio/twilio-php#221]
Services_Twilio_Rest_Addresses missing is missing a create(...) function corresponding to:

https://www.twilio.com/docs/api/rest/addresses#list-post

https://github.com/twilio/twilio-php/blob/master/Services/Twilio/Rest/Addresses.php

**Comment by efossier** [comment]
We've completely rewritten the library for 5.x, please upgrade and let us know if this is still an issue.
