### ISSUE TITLE
Lookups_Services_Client not autoloaded properly when installed from composer.

### ISSUE THREAD

**Issue by andrewnicols** [twilio/twilio-php#223]
I'm using Twilio in a Symfony app. It all works fine when I instantiate a new Services_Twilio(), but when I try to perform a lookup as per the PHP docs, the Lookups_Services_Twilio() instance cannot be autoloaded.

Swapping over load order such that Services_Twilio() comes before Lookups_Services_Twilio() resolves this issue.

**Comment by skimbrel** [comment]
@dougblack Can you get to this today? I'm at Pycon and my personal laptop doesn't have anything set up...

**Comment by elliotlings** [comment]
Has this been resolved?

**Comment by elliotlings** [comment]
#225

**Comment by JonEastman** [comment]
Hey guys! just ran into this same issue.  Thanks for putting a fix together for it.  Just curious, what version tag will this fix be accessible through?

**Comment by skimbrel** [comment]
I'll try to get a release cut this week, stay tuned.

**Comment by skimbrel** [comment]
4.0.1 is available now.

**Comment by JonEastman** [comment]
Hey @skimbrel! Just installed the new version with composer and still getting the same "class not found" error and "Did you forget a use statement for this class?" recomendation from Symfony.  Do you have any suggestions for why this might still be occurring?

**Comment by ihumanable** [comment]
It appears that there is an error in our composer autoloader, we will work on releasing a fix for this today

**Comment by ihumanable** [comment]
The autoloading model in composer has been updated in twilio/sdk 4.0.2, this has been released and tested as working correctly with and without Symfony.

4.0.2 has been published to packagist.org.

Make sure to update your composer.json file to `4.0.2`, `4.0.*`, or `4.*`
It may also be necessary to clear your composer cache using `composer clear-cache`
