### ISSUE TITLE
Could not decode response body as JSON.

### ISSUE THREAD

**Issue by RobbyR0b** [twilio/twilio-php#226]
I am receiving the error "error:Could not decode response body as JSON. This likely indicates a 500 server error". This happened after I fixed issue #203 . 

Locally testing everything works fine, on my remote server I receive this Exception. Its obviously environmental, but not sure where to start. Ideas?

**Comment by RobbyR0b** [comment]
re-installed CURL with proper CA bundles on server.. fixed.

**Comment by simo97** [comment]
i have the same error but i am testing my code locally
