### ISSUE TITLE
Uncaught exception 'Services_Twilio_TinyHttpException' with message 'SSL certificate problem:

### ISSUE THREAD

**Issue by christianogalabu** [twilio/twilio-php#227]
[07-May-2015 00:31:49 Europe/Berlin] PHP Fatal error:  Uncaught exception 'Services_Twilio_TinyHttpException' with message 'SSL certificate problem: self signed certificate in certificate chain' in C:\xampp\htdocs\sms\Services\Twilio\TinyHttp.php:119
Stack trace:
#0 C:\xampp\htdocs\sms\Services\Twilio.php(183): Services_Twilio_TinyHttp->__call('post', Array)
#1 C:\xampp\htdocs\sms\Services\Twilio.php(183): Services_Twilio_TinyHttp->post('/2010-04-01/Acc...', Array, 'From=%2B1202350...')
#2 C:\xampp\htdocs\sms\Services\Twilio\ListResource.php(92): Base_Services_Twilio->createData('/2010-04-01/Acc...', Array)
#3 C:\xampp\htdocs\sms\Services\Twilio\Rest\Messages.php(24): Services_Twilio_ListResource->_create(Array)
#4 C:\xampp\htdocs\sms\send-sms.php(17): Services_Twilio_Rest_Messages->create(Array)
#5 {main}
  thrown in C:\xampp\htdocs\sms\Services\Twilio\TinyHttp.php on line 119

**Comment by skimbrel** [comment]
Hi!

This means your system's SSL certificates are out of date and can't validate the certificate the Twilio API is presenting. Common causes for this and some potential solutions are already documented in the FAQ: https://github.com/twilio/twilio-php/blob/master/docs/faq.rst

Please give that a try first and see if it helps solve this for you.

**Comment by christianogalabu** [comment]
Please Sam,
Even after following your FAQ url, the messages are not going. Even when i
use the "DEVTOOL" on your site some goes some don't. Please advice it
driving me craze.

Thanks

private function sendSMS($mobilenumber,$msg){
 $AccountSid = "ACxxxxxxxxxxxxxxxxxxxxxx";
 $AuthToken = "20xxxxxxxxxxxxxxxxxxxxx";

try {
$http = new Services_Twilio_TinyHttp(
    'https://api.twilio.com',
    array('curlopts' => array(
        CURLOPT_SSL_VERIFYPEER => true,
        CURLOPT_SSL_VERIFYHOST => 2,
    )));
 $client = new Services_Twilio($AccountSid, $AuthToken, "2010-04-01",
$http);
  $from = "+12023504105";
 $to = $mobilenumber;
 // The SMS body
 $message = $msg;
 // Send a new outgoing SMS
$response = $client->account->sms_messages->create($from, $to, $message);

// Get the delivery status
//return $response->status;

} catch (Exception $e) {
echo "Caught exception: " . $e->getMessage();
}

}

On Fri, May 8, 2015 at 5:08 PM, Sam Kimbrel <notifications@github.com>
wrote:

> Hi!
>
> This means your system's SSL certificates are out of date and can't
> validate the certificate the Twilio API is presenting. Common causes for
> this and some potential solutions are already documented in the FAQ:
> https://github.com/twilio/twilio-php/blob/master/docs/faq.rst
>
> Please give that a try first and see if it helps solve this for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twilio/twilio-php/issues/227#issuecomment-100282825>.
>



-- 
I stand for Jesus Christ, how about you.

**Comment by skimbrel** [comment]
Can you please write in to help@twilio.com? Our Support team is better equipped to help you track down the source of this issue.

**Comment by keyboardface** [comment]
I too have tried all of the same solutions in the FAQ to no avail. Using PHP  5.6.9, Curl 7.42.1. Difference is that it's on Windows. Uploaded the same script to a CPanel server and it worked immediately. 

No clue as to what to change on the Windows config to fix it. 

Thanks,
Tom

**Comment by mittal-sam** [comment]
Facing the same problem with xampp on windows. Tried everything

**Comment by varunjoshi12** [comment]
Hi please help me i am facing this error while using the twilo api and i have verified my number then also it shows that error

Fatal error: Uncaught exception 'Services_Twilio_RestException' with message 'The source phone number provided, +18817493061, is not yet verified for your account. You may only make calls from phone numbers that you've verified or purchased from Twilio.' in /opt/lampp/htdocs/twilo/Services/Twilio.php:297 Stack trace: #0 /opt/lampp/htdocs/twilo/Services/Twilio.php(180): Base_Services_Twilio->_processResponse(Array) #1 /opt/lampp/htdocs/twilo/Services/Twilio/ListResource.php(92): Base_Services_Twilio->createData('/2010-04-01/Acc...', Array) #2 /opt/lampp/htdocs/twilo/Services/Twilio/Rest/Calls.php(32): Services_Twilio_ListResource->_create(Array) #3 /opt/lampp/htdocs/twilo/Services/test.php(21): Services_Twilio_Rest_Calls->create('8817493061', '8817493061', 'http://twimlets...') #4 {main} thrown in /opt/lampp/htdocs/twilo/Services/Twilio.php on line 297

**Comment by jiromm** [comment]
Add a line `CURLOPT_SSL_VERIFYPEER  => false,` in TinyHttp.php on line ~60. But after you'll have another problem.

**Comment by skimbrel** [comment]
@jiromm Please, please, _please_ do not encourage people to disable SSL certificate verification. The documentation for this library clearly explains how to install updated certificate bundles for libcurl to enable SSL communication with the Twilio API. Disabling SSL verification leaves your requests to Twilio completely vulnerable to interception by a malicious third party.

At this point, this ticket has become a dumping ground for people with issues vaguely related to making requests to Twilio with the PHP client. I'm going to close it and encourage everyone to contact `help@twilio.com` to get direct help with their specific problems.

**Comment by skimbrel** [comment]
Editing contents to prevent this from showing up in Google and encouraging users to disable SSL verification.
