### ISSUE TITLE
Fatal error: Uncaught exception 'Services_Twilio_TinyHttpException' with message 'Couldn't resolve host 'api.twilio.com''

### ISSUE THREAD

**Issue by vkandrikar** [twilio/twilio-php#229]
while making a voice call request getting below error 

Fatal error: Uncaught exception 'Services_Twilio_TinyHttpException' with message 'Couldn't resolve host 'api.twilio.com'' in /home/www/BCARD/custom/CEMV/TEMP_CC/Services/Twilio/TinyHttp.php:119
Stack trace:
#0 /home/www/BCARD/custom/CEMV/TEMP_CC/Services/Twilio.php(179): Services_Twilio_TinyHttp->__call('post', Array)
#1 /home/www/BCARD/custom/CEMV/TEMP_CC/Services/Twilio.php(179): Services_Twilio_TinyHttp->post('/2010-04-01/Acc...', Array, 'Method=GET&Fall...')
#2 /home/www/BCARD/custom/CEMV/TEMP_CC/Services/Twilio/ListResource.php(92): Base_Services_Twilio->createData('/2010-04-01/Acc...', Array)
#3 /home/www/BCARD/custom/CEMV/TEMP_CC/Services/Twilio/Rest/Calls.php(32): Services_Twilio_ListResource->_create(Array)
#4 /home/www/BCARD/custom/CEMV/TEMP_CC/autoAlerting.php(100): Services_Twilio_Rest_Calls->create('+441290211984', '+918390786524', 'http://twimlets...', Array)
#5 /home/www/BCARD/custom/CEMV/TEMP_CC/autoAlerting.php(39): fnMakeVoiceCall('+918390786524', 'Hi, this is tes...')
#6 {main}

  thrown in /home/www/BCARD/custom/CEMV/TEMP_CC/Services/Twilio/TinyHttp.php on line 119

**Comment by ezekel** [comment]
I am having problem too.

**Comment by vkandrikar** [comment]
add below code at all files where u r getting error


$_h = curl_init();
	curl_setopt($_h, CURLOPT_HEADER, 1);
	curl_setopt($_h, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($_h, CURLOPT_HTTPGET, 1);
	curl_setopt($_h, CURLOPT_URL, 'https://api.twilio.com' );
	curl_setopt($_h, CURLOPT_PROXY, '35.56.104.42:8080');
	curl_setopt($_h, CURLOPT_DNS_USE_GLOBAL_CACHE, false );
	curl_setopt($_h, CURLOPT_DNS_CACHE_TIMEOUT, 2 );
	curl_setopt($_h, CURLOPT_SSL_VERIFYPEER, FALSE);
	curl_setopt($_h, CURLOPT_SSL_VERIFYHOST,  2);
	
	curl_exec($_h);

**Comment by kevinburke** [comment]
2 second DNS cache timeout is pretty aggressive. Can probably turn this
down to 60 (the default)


--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by skimbrel** [comment]
Please do not encourage people to disable SSL peer verification! This leaves your application open to man-in-the-middle attacks against your traffic to Twilio, which means an attacker could read your messages or steal your Twilio API credentials. If your application throws errors related to SSL certificate validation, please see the FAQ: https://twilio-php.readthedocs.org/en/latest/faq.html#ssl-validation-exceptions

**Comment by ezekel** [comment]
@vkandrikar  Is this will also will work in sending message ?

**Comment by dhavalstays** [comment]
@vkandrikar Where should I add that code. At line 128 it throws exception.


Fatal error: Uncaught exception 'Services_Twilio_TinyHttpException' with message 'Couldn't resolve host 'api.twilio.com'' in /Applications/AMPPS/www/Test/twilio/Services/Twilio/TinyHttp.php:128 Stack trace: #0 /Applications/AMPPS/www/Test/twilio/Services/Twilio.php(193): Services_Twilio_TinyHttp->__call('post', Array) #1 /Applications/AMPPS/www/Test/twilio/Services/Twilio.php(193): Services_Twilio_TinyHttp->post('/2010-04-01/Acc...', Array, 'From=%2B1650229...') #2 /Applications/AMPPS/www/Test/twilio/Services/Twilio/ListResource.php(92): Base_Services_Twilio->createData('/2010-04-01/Acc...', Array) #3 /Applications/AMPPS/www/Test/twilio/Services/Twilio/Rest/Messages.php(24): Services_Twilio_ListResource->_create(Array) #4 /Applications/AMPPS/www/Test/twilio/Services/Twilio/Rest/Messages.php(71): Services_Twilio_Rest_Messages->create(Array) #5 /Applications/AMPPS/www/Test/index.php(70): Services_Twilio_Rest_Messages->sendMessage('+XXXX', '+XXX', 'This is a test.') #6 {main} thrown in /Applications/AMPPS/www/Test/twilio/Services/Twilio/TinyHttp.php on line 128

**Comment by dhavalstays** [comment]
@ezekel Have you got the solution for this?

**Comment by ezekel** [comment]
@dhavalstays , I don't have yet. I am still struggling on this twillio

**Comment by dhavalstays** [comment]
@ezekel Please post the solution once you resolve it.

**Comment by vkandrikar** [comment]
@ezekel 
yes, it work for sending messages also

**Comment by vkandrikar** [comment]
@dhavalstays
u can add the CURL code at very 1st line of php page before doing anything

        require('Services/Twilio.php');	
	$_h = curl_init();
	curl_setopt($_h, CURLOPT_HEADER, 1);
	curl_setopt($_h, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($_h, CURLOPT_HTTPGET, 1);
	curl_setopt($_h, CURLOPT_URL, 'https://api.twilio.com' );
	curl_setopt($_h, CURLOPT_PROXY, 'YOUR PROXY');
	curl_setopt($_h, CURLOPT_DNS_USE_GLOBAL_CACHE, false );
	curl_setopt($_h, CURLOPT_DNS_CACHE_TIMEOUT, 2 );
	curl_setopt($_h, CURLOPT_SSL_VERIFYPEER, FALSE);
	curl_setopt($_h, CURLOPT_SSL_VERIFYHOST,  2);	
	curl_exec($_h);

**Comment by ezekel** [comment]
@dhavalstays ,

do we need to purchase twilio phone number in order to send messages ?
because @devinrader said that,phone number should be purchase in twilio even you are in trial account.

see `https://github.com/twilio/twilio-php/issues/230#issuecomment-114804049`

**Comment by andriytkachiv** [comment]
This is still not resolved. I don't understand, its a commercial library, is it maintain??

**Comment by efossier** [comment]
We've completely rewritten the library for 5.x, please upgrade and let us know if this is still an issue.

**Comment by Omazon** [comment]
I have the same issue, I haven't been able to resolve, I use the composer packer (for laravel), any idea, someone please!!

**Comment by imthepitts** [comment]
@Omazon if this issue started since Aug. 20, it may be due to our updated root certificate: 

https://support.twilio.com/hc/en-us/articles/360007853433-Troubleshooting-Certificate-Errors-for-the-REST-API 

If you need additional assistance, please contact our Support team: https://www.twilio.com/help/contact 

All the Best,
Zack
