### ISSUE TITLE
Fatal error: Uncaught exception 'Services_Twilio_TinyHttpException' with message 'SSL certificate problem

### ISSUE THREAD

**Issue by ezekel** [twilio/twilio-php#230]
I downloaded now the libcurl and I exract the folder,so how can I use this libcurl what is the next step after extracting the folder. ?
I am using windows 8

Thank you in advance.

**Comment by punithavimalraj** [comment]
Hi , 

Pls Is any update about this?

**Comment by shakib609** [comment]
follow the instructions skimbrel posted here.. [203](https://github.com/twilio/twilio-php/issues/203) then add the certificate from hairys link.

**Comment by ezekel** [comment]
@shakib609 

I get this error

![twilio](https://cloud.githubusercontent.com/assets/6830057/8300412/2e754a00-19b7-11e5-935d-b164f030f1c5.PNG)

**Comment by shakib609** [comment]
I found [this link](https://www.twilio.com/user/account/phone-numbers/incoming) in twilio. You can find out if your twilio account number is SMS-Enabled on this page. If it's not then you have to buy another Sms-capable phone number.

You should check [this link](https://www.twilio.com/user/account/settings/international/sms) too.

**Comment by ezekel** [comment]
I am in trial account, I never tried to success first in my trial account,before I can buy new phone number

**Comment by shakib609** [comment]
the screenshot shows that you are not using the phone number provided by twilio free account.. All twilio free accounts only give you number from either USA or CANADA.. So your number should be starting with +1 or something like that..

**Comment by devinrader** [comment]
Hey @shakib609, trial accounts will actually be presented a default number option based on the geo-location of their IP address and whether or not Twilio offers local numbers in that country.  Plus you can change that default number during the signup process.

@ezekel, it looks like the number you are trying to use as the From phone number is not a Twilio phone number.  All Twilio accounts, trial or not, are restricted to sending SMS messages only from numbers purchased from Twilio.

**Comment by ezekel** [comment]
@devinrader ,

Thank you for the reply, so I need to purchased phone number to twilio so that I can send messsages ?

**Comment by devinrader** [comment]
@ezekel you should have been given a Twilio phone number during your signup process.  If you don't see one under the [numbers tab](https://www.twilio.com/user/account/phone-numbers/incoming) in your account portal, I'd shoot an email over to help@twilio.com and our awesome support team can get you set up.
