### ISSUE TITLE
file_get_contents(): Failed to enable crypto in Twilio/Twilio/HttpStream.php on line 67

### ISSUE THREAD

**Issue by glawas** [twilio/twilio-php#231]
When attempting to send a message using SSL and Services_Twilio_HttpStream. I triggered an "Unable to connect to service" Services_Twilio_HttpStreamException.  The underlying cause of this exception was the following error: file_get_contents(): Failed to enable crypto in Twilio/Twilio/HttpStream.php on line 67

So we did a little digging and discovered that the issue was being caused by a missing SSL Context Option ("cafile").  The Services_Twilio_HttpStream is being instantiated with a static set of context options; one of which enables  peer verification but does not check for or require that the ca file be available.

The fix for us was to patch this ssl context option to the library file.  A better alternative would be to allow this option to be passed in or perhaps to enforce an interface and allow devs to pass in there own implementation of Services_Twilio_HttpStream as the fourth parameter to Services_Twilio.

**Comment by jhoughtelin** [comment]
I just ran in to this same error on one of my servers and found it to be a configuration issue.  file_get_contents can't verify any SSL without a ca bundle or path to them. 

I resolved this issue in a couple ways but by far the easiest mechanism was by way of installing the PHP Curl extension.  (which I didn't have installed)

PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57)
