### ISSUE TITLE
Cannot redeclare Services_Twilio_autoload() in blank PHP Project

### ISSUE THREAD

**Issue by pastapreneur** [twilio/twilio-php#234]
Platform: OS X 10.10 running PHP 5.6.5
Download the Twilio library from https://www.twilio.com/docs/php/install as a ZIP file

Write the following code:

```php
<?php
require_once('lib/Twilio/Services/Twilio.php');
```

(where lib/Twilio is the folder where Twilio is installed and this test PHP file is sitting next to the lib directory.

Get the following error: 
```
Fatal error: Cannot redeclare Services_Twilio_autoload() (previously declared in /path/to/project/lib/Twilio/Services/Twilio.php:9) in /path/to/project/lib/Twilio/Services/Twilio.php on line 21
```

**Comment by skimbrel** [comment]
Huh. This works for me on OS X with PHP 5.6.7 installed via homebrew.

Can you make sure you've got the latest version of the library by downloading a fresh copy, just to sanity-check that?

**Comment by pastapreneur** [comment]
Weird. After re downloading the library it works. Not sure what was going on there.

Thanks for your help.
