### ISSUE TITLE
Alphanumeric fallback

### ISSUE THREAD

**Issue by andrewnicols** [twilio/twilio-php#235]
It would be great if the library (or even better, the API) supported automatic fallback when using alphanumeric senders.

That is to say, if you could provide both a From, and an Alphanumeric code. In the case that the Recipient cannot receive Alphanumeric codes, the API (or library) should fall back automatically to the provided number.

**Comment by philnash** [comment]
Hey @andrewnicols,

It's not the case that the API supports that at the moment. If you wanted to provide the fallback, you could do the following though:

```php
try {
  $client->account->messages->sendMessage("Alpha", $number, "Hello");
} catch (Services_Twilio_RestException $e) {
  // 21612 is the error code when you try to send a message using an alphanumeric sender and you can't
  if($e->getCode() == "21612") {
    $client->account->messages->sendMessage($fromNumber, $number, "Hello");
  } else {
    throw $e;
  }
}
```

**Comment by andrewnicols** [comment]
Hi Phil,

Sorry, I was suggesting that this should be a feature of the API, or at the very least the library.

Since there is no API endpoint to find out whether a number will support alphanumeric coding, you are forcing developers to either hardcode the list (from your website), or to handle one failure type separately to others. 

Essentially we will end up with a nasty set of try/catch where the catch tries to repeat the call and does try/catch again for any subsequent errors.

IMO this should be built into the Twilio API but failing that into the php library. Preferably the former though.

Thanks,
Andrew

**Comment by philnash** [comment]
Ah, I see! I have enquired within about how we could offer this through the API, so your suggestion has absolutely been noted. In the meantime, we certainly accept pull requests for this sort of thing, perhaps a method that decorates the `sendMessage` method with an extra fallback number parameter and does the try catch that I wrote above?

**Comment by jmctwilio** [comment]
This functionality should be supported through CoPilot.

https://www.twilio.com/docs/api/rest/sending-messages-copilot
