### ISSUE TITLE
Alphanumeric Sender ID

### ISSUE THREAD

**Issue by dror3go** [twilio/twilio-php#236]
I want to use the (pretty new) feature [Alphanumeric Sender ID](https://www.twilio.com/help/faq/sms/what-is-alphanumeric-sender-id-and-how-do-i-get-started) when sending SMS.

What's the minimum SDK version I should use? Cause now I'm getting an error saying:
> The From phone number **XXXX** is not a valid, SMS-capable inbound phone number or short code for your account

Where **XXXX** is the body of the SMS I'm trying to send.

**Comment by skimbrel** [comment]
Can you paste the code you're using to send messages? The `From` parameter should contain the sender ID you want to send from, and your message body should go in the `Body` parameter.

**Comment by dror3go** [comment]
I'm using [aloha/twilio](https://github.com/aloha/laravel-twilio) for Laravel, so it's pretty straight forward:
```
Twilio::message($to, $message):
```
The `from` is configured in a config file of the package, along with `sid` & `token`. So I simply change the `from` value in the config file to a textual value and try to send SMS.
Note that when changing back the config value of "from" to my Twilio number - the SMS is sent.

**Comment by skimbrel** [comment]
Ah, I see.

Can you reproduce this against the Twilio API using `curl` or something similar on the command line? It's possible that the number you're trying to send to is in a country that doesn't support alpha sender.

**Comment by dror3go** [comment]
According to [your help center](https://www.twilio.com/help/faq/sms/what-countries-does-twilio-support-alphanumeric-sender-id), Israel is among the list of counties you support.
I just noticed that the XXXX I wrote before is actually 869669 - which translates to the alphanumeric sender ID string I'm trying to send from.

BTW, the error I'm getting is 21606. Am I missing something, and I have to configure the alphanumeric string I'm using in my Twilio account?

**Comment by dror3go** [comment]
Tried with curl:

```
curl -XPOST https://api.twilio.com/2010-04-01/Accounts/<MY_SID>/Messages -d "Body=Hi" -d "To=%2B97252<MY_NUMBER>" -d "From=<MY_ALPHANUMERIC_SENDER_ID>" -u "<MY_SID>:<MY_TOKEN>"
```

and got in response:

`<?xml version='1.0' encoding='UTF-8'?>
<TwilioResponse><RestException><Code>21606</Code><Message>The From phone number 869669 is not a valid, SMS-capable inbound phone number or short code for your account.</Message><MoreInfo>https://www.twilio.com/docs/errors/21606</MoreInfo><Status>400</Status></RestException></TwilioResponse>`

**Comment by skimbrel** [comment]
Hm. This is probably deeper in the stack than I'm familiar with. Can you open a ticket with help@twilio.com and tell them I sent you?

**Comment by dror3go** [comment]
Just got a reply saying that it's not supported for trial accounts... :-)

**Comment by dror3go** [comment]
Now with a paid account, sending SMS to a number in a supported country with alphanumeric sender ID gives me the following error when using twilio-php:
`
The From phone number 869669 is not a valid, SMS-capable inbound phone number or short code for your account
`
Sending it with curl works great and the alphanumeric sender ID is working.

Can I use Twilio's SDK version 3.12.* to use alphanumeric sender ID?

**Comment by philnash** [comment]
Hey @dror3go, did you say earlier that you are sending a text string, not the number 869669?

**Comment by dror3go** [comment]
Hi @philnash, as I [wrote before](https://github.com/twilio/twilio-php/issues/236#issuecomment-110240796) - the number 869669 is actually a number representation of my "from" parameter, where ABC = 2, DEF = 3 ... WXYZ = 9.

**Comment by philnash** [comment]
Thanks @dror3go, that seems really strange. Could you email me your Account SID to  philnash@twilio.com and I'll take a look.

**Comment by thisispiers** [comment]
i'm also seeing this error. any reason?

**Comment by philnash** [comment]
This case turned out to be an old version of aloha/twilio for Laravel. Try upgrading the plugin or just using the latest Twilio PHP helper.

**Comment by rkorach** [comment]
Hi @philnash, I have the exact same problem with node. Alphanumeric Sender ID works great with curl, but whenever sent through the twilio-node (v 2.8.0) module it sends me an error 21212.

(Since I'm talking about node this may not be the right place to post, let me know if so)

**Comment by philnash** [comment]
Hey @rkorach,

My guess is that you are using `client.sms.messages.create` when using the Node library. This uses the [old, deprecated `SMS/Messages` endpoint](https://www.twilio.com/docs/api/rest/sms) and does not work with Alphanumeric Sender IDs. You should be able to replace that call with `client.messages.create` (which uses the [newer `/Messages` endpoint](https://www.twilio.com/docs/api/rest/message)) and it will work.

Let me know if that helps!

**Comment by rkorach** [comment]
wow. And now I feel publicly stupid. I cannot even tell where I got that from, as Twilio doc is correct, updated AND perfectly clear.
Thanks a lot @philnash for taking the time, this was the exact mistake on my side.

**Comment by philnash** [comment]
My guess is that you found it in the [Node helper library documentation](http://twilio.github.io/twilio-node/) as that currently shows the old API. So I wouldn't blame yourself.

You'll be pleased to hear that I have a [Pull Request open to fix that now](https://github.com/twilio/twilio-node/pull/148).

Hope the rest of your application goes well!
