### ISSUE TITLE
SMS

### ISSUE THREAD

**Issue by jeanfrancis** [twilio/twilio-php#237]
Any plan to support SMS ? like if we want to forward SMS received on a number to another number

**Comment by philnash** [comment]
Hi @jeanfrancis. Checking out your profile, you list yourself as in Cameroon. Are you asking whether we are going to support receiveing SMS messages on a Cameroonian number? If so, we are continually working on expanding the reach of our numbers, but I can't say if or when we will support numbers for SMS in Cameroon. It is possible with many numbers from other countries to receive SMS and forward it to another number, there is a quick how to accomplish this here: https://www.twilio.com/help/faq/sms/how-do-i-forward-my-sms-messages-to-another-phone-number

Let me know if this helps at all.

**Comment by jeanfrancis** [comment]
I don't have any issue with receiving sms in my location , was asking about receive a sms on a number and automalitcally forward it to another number like we can do it for voice using Twimlets : https://www.twilio.com/labs/twimlets

**Comment by philnash** [comment]
Ok, that's cool. You absolutely can receive SMSs on a Twilio number and forward them, the article I linked above can show you how to do that. Let me know if that helps!
