### ISSUE TITLE
Fatal error: Uncaught exception 'Services_Twilio_TinyHttpException' with message 'SSL certificate problem: self signed certificate in certificate chain'

### ISSUE THREAD

**Issue by dhavalstays** [twilio/twilio-php#240]
I have tried all the solutions from this link still it is showing me an error

Fatal error: Uncaught exception 'Services_Twilio_TinyHttpException' with message 'SSL certificate problem: self signed certificate in certificate chain' in /Applications/AMPPS/www/Bluelight/twilio/Services/Twilio/TinyHttp.php:119 Stack trace: #0 /Applications/AMPPS/www/Bluelight/twilio/Services/Twilio.php(179): Services_Twilio_TinyHttp->__call('post', Array) #1 /Applications/AMPPS/www/Bluelight/twilio/Services/Twilio.php(179): Services_Twilio_TinyHttp->post('/2010-04-01/Acc...', Array, 'From=%2B1650229...') #2 /Applications/AMPPS/www/Bluelight/twilio/Services/Twilio/ListResource.php(92): Base_Services_Twilio->createData('/2010-04-01/Acc...', Array) #3 /Applications/AMPPS/www/Bluelight/twilio/Services/Twilio/Rest/Messages.php(24): Services_Twilio_ListResource->_create(Array) #4 /Applications/AMPPS/www/Bluelight/twilio/Services/Twilio/Rest/Messages.php(71): Services_Twilio_Rest_Messages->create(Array) #5 /Applications/AMPPS/www/Bluelight/index.php(47): Services_Twilio_Rest_Messages->sendMessage('+1XXX', '+1XXXX in /Applications/AMPPS/www/Bluelight/twilio/Services/Twilio/TinyHttp.php on line 119

How to resolve it?

**Comment by punithavimalraj** [comment]
Hi ,

Pls Is any update about this?

**Comment by shakib609** [comment]
I have solved the problem following this link.. [203](https://github.com/twilio/twilio-php/issues/203)

**Comment by mohammedabualsoud** [comment]
I just updated my libcurl and issue solved as they said on the docs.

**Comment by ihumanable** [comment]
Answered
