### ISSUE TITLE
4.2.1 fails to load with composer (Autoload failure)

### ISSUE THREAD

**Issue by rbalik** [twilio/twilio-php#241]
I get this error after updating twilio-php to 4.2.1 via composer:
` PHP Fatal error:  require(): Failed opening required 'Services_Twilio_Resource.php' `

This happens before even calling any Twilio functions. It's on the line where I'm doing `require('vendor/autoload.php');`

It looks like what might be happening is that because the autoloader is declared in the same file as the Twilio class which inherits from Services_Twilio_Resource that it's trying to find that class before the autoloading actually takes place.

**Comment by rbalik** [comment]
My theory is definitely wrong since it is registerting the autoloader right there. I'll investigate further.

**Comment by rbalik** [comment]
Never mind. I figured it out. Had some of my own autoloading in the wrong order.

**Comment by fiatux** [comment]
Having the same problem. I am using lots of packages and only Twilio is causing this error, so I'm assuming my Auloloaders should be fine. How did you solve this?
