### ISSUE TITLE
ListResource returning all records even when page is set

### ISSUE THREAD

**Issue by imthepitts** [twilio/twilio-php#245]
Even when specifying page limit, all records are being returned.

```php
$client = new Services_Twilio($account_sid, $auth_token); 
 
$calls = $client->account->messages->getIterator(0, 10);
 
$i = 0; 
foreach ($calls as $call) { 
	echo $i++ . ' ' . $call->sid . '<br>';
}

```

**Comment by ihumanable** [comment]
The arguments to getIterator() simply describe the desired pageSize per request.  getIterator() returns a Services_Twilio_AutoPagingIterator which will go and fetch more data once the internal page is exhausted.

**Comment by imthepitts** [comment]
Ah, thanks, @ihumanable.
 
So for developers who just want to fetch 50 items, this would be the proper way?

```php
$calls = $client->account->calls->getPage(0, 50)->getIterator();
```

**Comment by mplacona** [comment]
Correct @imthepitts
