### ISSUE TITLE
The number is unverified. Trial accounts cannot send messages to unverified numbers

### ISSUE THREAD

**Issue by sdeering** [twilio/twilio-php#246]
Any ideas?

![image](https://cloud.githubusercontent.com/assets/1787454/8446087/79d22b58-1fe8-11e5-8b28-0ec66a86826b.png)

![image](https://cloud.githubusercontent.com/assets/1787454/8446083/651119d6-1fe8-11e5-8767-2465720de3b4.png)

**Comment by philnash** [comment]
It looks like, from your screengrabs, you're trying to send an SMS message to a number starting +4 yet the number you say is verified is a +61 number.  Have you made sure the +4 number is verified too?

**Comment by sdeering** [comment]
Thanks for your reply mate, I solved it by creating a new Twilio number which has only SMS/MMS capabilities and used this one to send the message and it now works. Strange but good now.

**Comment by philnash** [comment]
Glad to hear you're sorted!

**Comment by heralds25** [comment]
Hello there! should i upgrade my account? to use SMS function? Im trying to send a message my virtual number but it says there "21608 While your account is in Trial Mode, you may only send SMS messages to verified numbers. Upgrade to a Full Twilio account to send to any phone number." TIA

**Comment by imthepitts** [comment]
@heralds25 while in trial mode, you can only send SMS to verified numbers, which you can set up here: 
https://www.twilio.com/console/phone-numbers/verified

If you need further assistance, please reach out to our support team:
https://www.twilio.com/console/support/tickets/create

**Comment by heralds25** [comment]
ok thanks sir @imthepitts. I'm beginner for the SMS gateway when it works i will upgrade my account thanks.

**Comment by AcMoe** [comment]
Can I send unverified phone numbers from Myanmar when upgrading my twilio account.

**Comment by philnash** [comment]
@AcMoe You can! Here are the guidelines for sending messages to Myanmar: https://www.twilio.com/sms/guidelines/mm and these are the costs: https://www.twilio.com/sms/pricing/mm.

**Comment by erkrujjawal786** [comment]
Hii. I am from India and beginner on twilio. I have buyed twilio trial number and released it but that number is of USA. When i use to send sms from this number it gives me error:-`RestException [Error]: The number  is unverified. Trial accounts cannot send messages to unverified numbers; verify  at twilio.com/user/account/phone-numbers/verified, or purchase a Twilio number to send messages to unverified numbers.`

**Comment by childish-sambino** [comment]
@erkrujjawal786 Recommend reaching out to [support](https://twilio.com/help/contact).
