### ISSUE TITLE
Check valid to number for SMS send before sending SMS

### ISSUE THREAD

**Issue by nilesh712** [twilio/twilio-php#247]
HI,
I am using your API to send SMS to my website users.
But one issue I am facing is I want to check first that ,Is that number is valid or not?
Is there any API in Twillio which can help to check valid to number?

Thanks in advance.

Regards,
Nilesh

**Comment by philnash** [comment]
Hi @nilesh712, you're in luck for that API absolutely exists! Take a look at our [Lookup API](https://www.twilio.com/lookup) ([documentation here](https://www.twilio.com/docs/api/rest/lookups)), I think you'll find it does exactly what you need.

Let me know if that helps!

**Comment by nilesh712** [comment]
Hi,

Thanks for your help.
But there is no library in twillio.php for this class.
I am getting this error : Class 'Lookups_Services_Twilio' not found 
Can you help to find twilio.php file which includes this class,Lookups_Services_Twilio?

**Comment by philnash** [comment]
Ah, sorry, I see. The `Lookups_Services_Twilio` class is defined [here](https://github.com/twilio/twilio-php/blob/558c96789bf84740d7957aa7fde91014d703261c/Services/Twilio.php#L481).

Which version of the Twilio PHP library are you using?

**Comment by peardox** [comment]
There's a bad issue with Twilio lookups

I've got 350k numbers I know are good (they rang us)

My colleague has 149k - his list is an address book with Twilio Lookup

I recently sent about 65k SMSes to people in his list - got a 10% fail rate...

Basically the only way to verify a number is gonna cost you a cent - send them a SMS and check the delivery status and error code - if it fails mark the record as potentially bad (they can change status so a counter is a good idea)

Twilio lookup just tells you if a number is valid, not if its real - here's a sample

Go to https://www.twilio.com/lookup and enter +441613759999 - rubbish as 999 at the end of a UK number is restricted for police so you get a dead number

**Comment by philnash** [comment]
Hey @peardox,

You are right, the best way to find out if a phone number can receive an SMS message is to send an SMS message to it. In fact, the only way to be 100% confident is to send the number a unique generated code that the owner of the phone can then enter into a form to ensure that the message has been sent and received as delivery receipts for SMS messages are not 100% trustworthy either. Alternatively, you could phone the number and have the recipient enter a code using the dial pad, that would confirm it was a real phone too (although it might be a landline and still not able to receive SMS if that's what you need).

Numbers could indeed look valid and not be possible, like your example of the 999 number. It could also be a valid number and not assigned to any phone/SIM card at the time. Or it could have been assigned to a phone/SIM but returned to the network for recycling. There are many reasons a valid phone number may not be able to receive calls or SMS messages. 

What are you trying to achieve with your number lists? Is there anything we can help with?

**Comment by peardox** [comment]
My list is people who've called one of our clients, my colleague's is unverified while mine is (they called us)

We use the list to notify fans of our clients about new releases - one was rather vocal about his $6k bill (his own fault cos he didn't realise they were also gonna try voice)

I know that in the UK (best knowledge is local) I can tell if a number is land / mobile using the OFCOM data set, I guess there's something similar for the US even though they use local exchange codes

I thought about adding the unique bit to my original answer but decided against it as it over-complicated the reply

The best solution is a TWIML verification app - companies like Amazon verify you in a similar manner

twilio-php limits so much of what you can do - annoys me (see tracking calls thread)

My funders want all OO - I can't do that with the API as I wanna send a cookie

**Comment by philnash** [comment]
@peardox It sounds like you have a different issue to this one that was originally opened, and it might be a bit more deep than that. Do you want to email me on philnash@twilio.com and we can perhaps work together to help you solve your problems?
