### ISSUE TITLE
Lookup API not implemented by PHP?

### ISSUE THREAD

**Issue by LukeNZ** [twilio/twilio-php#248]
Is the Twilio Lookup API implemented by this repo? It doesn't appear to be supported, and there's no documentation surrounding it. Trying to lookup a number returns a `null` result.

**Comment by mbalonso** [comment]
Hey @LukeNZ,

I thought the same thing myself actually about an hour ago.  Did a little bit more diffing and found some examples at the bottom of https://www.twilio.com/docs/api/rest/lookups.  Hope that helps.
