### ISSUE TITLE
Exception: AUTOLOADER: Class Services_Twilio_TinyHttp not found! in autoloader.php(129) : eval()'d code on line 4

### ISSUE THREAD

**Issue by saada** [twilio/twilio-php#249]
``` php
$this->client = new Services_Twilio($AccountSid, $AuthToken);
```

the above line of code triggers the problem. I am using the composer package

**Comment by peardox** [comment]
Are you using a framework??? (took me a day to get Laravel happy)

It sounds like it from your mention of composer

Shove this somewhere near the top...

use Services_Twilio;

Then in the controller try something like this...

	$client = new Services_Twilio($twaccsid, $twauth);

	try {
		$message = $client->account->sms_messages->create(
			$to,
			$from,
			$msg,
			array('StatusCallback' => $callback));
		} catch (Services_Twilio_RestException $e) {
         		// Do something
		}

$to, $from and $msg are fairly obvious, the callback is optional - kill it if you're not using one / dont wanna know what happened if you hit a queue or other situation

**Comment by saada** [comment]
Yeah I tried this with no luck

**Comment by peardox** [comment]
See #253 as it involves the same issue

**Comment by varunjoshi12** [comment]
Hi please help me i am facing this error while using the twilo api and i have verified my number then also it shows that error

Fatal error: Uncaught exception 'Services_Twilio_RestException' with message 'The source phone number provided, +18817493061, is not yet verified for your account. You may only make calls from phone numbers that you've verified or purchased from Twilio.' in /opt/lampp/htdocs/twilo/Services/Twilio.php:297 Stack trace: #0 /opt/lampp/htdocs/twilo/Services/Twilio.php(180): Base_Services_Twilio->_processResponse(Array) #1 /opt/lampp/htdocs/twilo/Services/Twilio/ListResource.php(92): Base_Services_Twilio->createData('/2010-04-01/Acc...', Array) #2 /opt/lampp/htdocs/twilo/Services/Twilio/Rest/Calls.php(32): Services_Twilio_ListResource->_create(Array) #3 /opt/lampp/htdocs/twilo/Services/test.php(21): Services_Twilio_Rest_Calls->create('8817493061', '8817493061', 'http://twimlets...') #4 {main} thrown in /opt/lampp/htdocs/twilo/Services/Twilio.php on line 297

**Comment by efossier** [comment]
We've completely rewritten the library for 5.x, please upgrade and let us know if this is still an issue.
