### ISSUE TITLE
Is that Possible to have instant calling via twilio ?

### ISSUE THREAD

**Issue by niloybanik** [twilio/twilio-php#252]
I want to mean that is it possible to call a number from a web app and connect the both calling and caller party ?

**Comment by philnash** [comment]
Hey @niloybanik, it is definitely possible to do that, in fact it's a very popular use case for using Twilio. If you are using PHP you should check out this [tutorial for building a click to call system in PHP with Laravel](https://www.twilio.com/docs/howto/walkthrough/click-to-call/php/laravel).

Let me know if that helps!
