### ISSUE TITLE
No response received during a test outbound message

### ISSUE THREAD

**Issue by mlisondra** [twilio/twilio-php#253]
I tried the following code (similar to your examples), but I am unable to receive a response from the server. Please note that I am using a Test account.

<?php
 ini_set('display_errors',1);
error_reporting('E_ALL');

require "/vendor/twilio/sdk/Services/Twilio.php";
 
// set your AccountSid and AuthToken from www.twilio.com/user/account
$AccountSid = "wefwafawuasodvcmnsdousadf";
$AuthToken = "0890723904ljmdfv9723";

$client = new Services_Twilio($AccountSid, $AuthToken);
//print_r($client);
try {
    $message = $client->account->messages->create(array(
       "From" => "925-273-9243",
    "To" => "925-273-9243",
        "Body" => "Test message!",
    ));
	print_r($message);
	echo $e->getMessage();
} catch (Services_Twilio_RestException $e) {
    echo $e->getMessage();
}

**Comment by mlisondra** [comment]
I also tried code generated by the following page:
https://www.twilio.com/user/account/developer-tools/api-explorer/message-create

Though still no response.

<?php
require('/vendor/twilio/sdk/Services/Twilio.php'); 

 
// set your AccountSid and AuthToken from www.twilio.com/user/account
$AccountSid = "";
$AuthToken = "";

$client = new Services_Twilio($AccountSid, $AuthToken);

print $AccountSid;
$client->account->messages->create(array( 
	'To' => "+19259808485", 
	'From' => "+19252739243", 
	'Body' => "Test via web page",   
));

**Comment by peardox** [comment]
This is about as far off-topic as you can get but here goes...

Try this - it'll allow you to find out WHY it's not working from the stuff you get back in $res

This is using the REST API, twilio-php is an OO wrapper for this kinda stuff - personally I prefer REST as I get more control but the bosses like libraries :(

I've dumbed the code down a bit, the CURLOPT_SSL_VERIFYPEER should be true for production but then you need cacert.pem and to add a line like the following after the setting

	curl_setopt($ch, CURLOPT_CAINFO, dirname(__FILE__) . '/cacert.pem');


function send_message($AccountSid, $AuthToken, $from, $to, $body) {
	$res = false;
	
	$url = 'https://api.twilio.com/2010-04-01/Accounts/' . $AccountSid . '/Messages.json';

	$msg = "From=".urlencode($from)."&To=".urlencode($to)."&Body=".urlencode($body);

	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, $url); 
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
	curl_setopt($ch, CURLOPT_POST, 1); 
	curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC); 
	curl_setopt($ch, CURLOPT_POSTFIELDS, $msg); 
	curl_setopt($ch, CURLOPT_USERPWD, $AccountSid . ':' . $AuthToken);
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
	$res = curl_exec($ch);
	curl_close($ch);

        echo "<pre>\n";		
	print_r($res);
        echo "</pre>\n";		
	
	}

**Comment by mplacona** [comment]
Yeah, you are not getting the messages because you're using Test account credentials, which will give you the same experience of sending an SMS message (i.e give you a response and a SID), but not actually deliver a message.

To get a message delivered you will need to use your live credentials.

[Check this out](https://www.twilio.com/docs/api/rest/test-credentials) for more information on test credentials.

**Comment by mlisondra** [comment]
@mplacona This doesn't make quite sense to me. I thought the whole point of the trial account was to see the capabilities of Twilio, but for a limited time. I read the content that you forwarded me to.
According to documentation the following should work as I am using a valid "From" number, 15005550006.
Below is my updated code.
However, I still don't get a response from the system. Thanks.

$client = new Services_Twilio($AccountSid, $AuthToken);

$client->account->messages->create(array( 
	'To' => "+19259808485", 
	'From' => "+15005550006", 
	'Body' => "Test via web page",   
));

echo $client->sid;

**Comment by mplacona** [comment]
Hey, there is nothing else with using a trial account. All I said is that you should make sure you are using the production credentials (i.e. the ones you can copy from [this page](https://www.twilio.com/user/account/voice)

If that doesn't work, please send me your complete code to marcos@twilio.com and I will give it a try here.

Thanks

**Comment by mlisondra** [comment]
@mplacona Thanks. I just sent you my code via email.

**Comment by peardox** [comment]
I just sent you one from +1401xxxxxxx to the +1500xxxxxxx with a good result

This was using my CURL stuff

**Comment by peardox** [comment]
Oh - note I'm using a live account (it's one of my test numbers)

**Comment by peardox** [comment]
Spoke too soon - Unknown error.

**Comment by peardox** [comment]
Spoke too soon - Unknown Error (helpful, eh?)

**Comment by peardox** [comment]
Oh - 555 - course it don't work

**Comment by mlisondra** [comment]
@peardox Thanks for helping out. I'm not an API expert but this seems to be less straightforward that I think it should be. Some of the confusion maybe a combo of the documentation and a bit of the API docs.

**Comment by peardox** [comment]
I just wrote a test script using a new TRIAL account and the above REST API stuff

Worked perfectly sending myself a message from the trial US number to my home (UK) phone

The only difference is that the message from TRIAL includes the text...

'Sent from your trial Twilio account'

Exactly the same would work with twilio-php

Only the REST API is properly documented :(

**Comment by mplacona** [comment]
Hi @mlisondra , thanks for sending me your code along with your credentials. I just thought I'd reply here for future reference. Under Twilio, you can use either your production credentials, or test credentials. Like I said in my last message, test credentials do not let SMS messages go out, and hence will give you the behavior you're getting.

I looked up your account, and saw that the credentials you're using are indeed the ones for your test account. To send outbound SMS, you need to be using the credentials that can be found in [this page](https://www.twilio.com/user/account/voice)

Hope this solves your issue.

**Comment by mplacona** [comment]
Hey @peardox , not really sure what you mean when you say "Only the REST API is properly documented" aren't you using the PHP library to make your requests? 

As for documentation, I would recommend creating issues and sending pull requests if you find problems with the documentation. We're happy to take them :-)

**Comment by mlisondra** [comment]
@mplacona  I tried it again with the production credentials and still no response. I didn't mention it before, but I am running the code on a localhost. I don't believe that would make a difference, however. I'll try using the curl option outlined in the docs.

**Comment by mplacona** [comment]
Hey @mlisondra I actually run the following code (with my own credentials and number) and successfully had messages sent to me:

```
<?php
require_once 'Services/Twilio.php';

// Your Account Sid and Auth Token from twilio.com/user/account
 $sid = 'AC';
 $token = '01';
 $client = new Services_Twilio($sid, $token);

 $client->account->messages->create(array( 
    'To' => "+44", 
    'From' => "+44", 
    'Body' => "Test via web page",   
 ));
 echo $client->Sid;
?>
```

**Comment by peardox** [comment]
The twilio-php library is extremely badly designed with no decent
documentation over and above very simple tasks

No, I use CURL (that's properly documented) in general - if you can
understand how to do a CURL call you can do everything

A simple example of bad documentation is how to pass a StatusCallback via
twilio-php - you can do it but the documentation completely fails to
explain the method

Going from bad to impossible is tracking - Twilio supports tracking via
Cookies (unavailable in twilio-php)

PHP is a dominant language so I guess you're loosing a huge number of
wannabe clients simply owing to bad documentation and missing features

Don't worry, you're not the only ones with imperfect APIs (you should see
WooCommerce REST - I had to branch that one until Max Rice fixed his end)

I'm seriously considering writing twilio-rest-php with proper dox as
twilio-php is simply an inadequate solition
