### ISSUE TITLE
International

### ISSUE THREAD

**Issue by peardox** [twilio/twilio-php#254]
"The 'To' phone number: +2348029xxxxxx, is not currently reachable using the 'From' phone number: +441548xxxxxx via SMS."

Yeah - I know it won't work - UK -> NG is not doable

My colleague wants to know how to detect local only availability or a superset thereof

I could easily set up a +1 number to call everywhere but FR but there's no way I can see to find out if I'm calling +33 xxxxxxxxxxxxxxx that it's possible

**Comment by philnash** [comment]
That's a quirk of UK landline numbers on Twilio. If you check out the details on the number in your dashboard you will find that UK landline numbers can only send SMS messages domestically. You can use a UK mobile number if you want to use UK numbers to send internationally.

I'm on my phone right now, so can't check in to the greater question you asked, but will check on that later.

**Comment by peardox** [comment]
Thanks for the prompt reply Phil + go sit on the beach or summat (you're meant to be on holiday)

I'll loop my colleague in

**Comment by varunjoshi12** [comment]
Hi please help me i am facing this error while using the twilo api and i have verified my number then also it shows that error 

 Fatal error: Uncaught exception 'Services_Twilio_RestException' with message 'The source phone number provided, +18817493061, is not yet verified for your account. You may only make calls from phone numbers that you've verified or purchased from Twilio.' in /opt/lampp/htdocs/twilo/Services/Twilio.php:297 Stack trace: #0 /opt/lampp/htdocs/twilo/Services/Twilio.php(180): Base_Services_Twilio->_processResponse(Array) #1 /opt/lampp/htdocs/twilo/Services/Twilio/ListResource.php(92): Base_Services_Twilio->createData('/2010-04-01/Acc...', Array) #2 /opt/lampp/htdocs/twilo/Services/Twilio/Rest/Calls.php(32): Services_Twilio_ListResource->_create(Array) #3 /opt/lampp/htdocs/twilo/Services/test.php(21): Services_Twilio_Rest_Calls->create('8817493061', '8817493061', 'http://twimlets...') #4 {main} thrown in /opt/lampp/htdocs/twilo/Services/Twilio.php on line 297

**Comment by ihumanable** [comment]
Answered, @varunjoshi12 please contact help@twilio.com for more general API questions.
