### ISSUE TITLE
Error message not in documentation? "Message body is required"

### ISSUE THREAD

**Issue by msacchetti** [twilio/twilio-php#255]
My code is returning an error but i cant find the error in any of the docs or error codes.

The Services_Twilio_RestException is returning: "Message body is required." Which is not a documented error. What could be the case here? 

The code successfully sends the SMS to the first recipient, and then all other recipients in the loop return the error  "Message body is required".

Here is the full code.

    foreach ($recipients as $recipient) {
        try {
            $message = $client->account->messages->create([
            "From" => $from,
            "To"   => '+1' . $recipient->phone_number,
            "Body" => stripslashes($message->afternoon_text),
        ]);
        } catch (Services_Twilio_RestException $e) {
            $db->query("INSERT INTO error_logs SET error='" . addslashes($e->getMessage()) . "'");
        }
    }

**Comment by philnash** [comment]
Hey @msacchetti, I responded to your question on [StackOverflow](http://stackoverflow.com/questions/32261051/twilio-error-message-that-is-not-in-documentation-message-body-is-required/32268185#32268185). Perhaps we can sort out your problem over there.

If you think there should be documentation for the error message "Message body is required" please open another issue or pull request.

Thanks
