### ISSUE TITLE
Add sanity check before foreach() call in Services/Twilio/Twiml.php:108

### ISSUE THREAD

**Issue by synesisinc** [twilio/twilio-php#257]
Hello,

I'm getting a lot of the following php warnings:

E_WARNING: Invalid argument supplied for foreach() in .../vendor/twilio/sdk/Services/Twilio/Twiml.php(108)

It would be simple to add a check before the foreach() for a valid iterable, is this possible?

Thank-you for such a great service and API!

**Comment by ihumanable** [comment]
I'm happy to add this to the new 5.x version, I'm having trouble reproducing but this seems like a harmless sanity check.

**Comment by ihumanable** [comment]
Added in https://github.com/twilio/twilio-php/pull/357

**Comment by ihumanable** [comment]
5.x line updated
