### ISSUE TITLE
Important Changes to Twilio's Security Certificate

### ISSUE THREAD

**Issue by chicag0** [twilio/twilio-php#260]
Does this use the SHA2 certs that Twilio is requiring soon?

**Comment by javipsantos** [comment]
On December 1, 2015 at 4:30 PM PT.

**Comment by carlosdp** [comment]
Yes, you shouldn't have to do anything to the library usage to use SHA2 certs. If you would like to test your service with the new cert, you should be able to change the HTTPS port to `8443` (our test port) like so:

```php
$client->http->port = '8443';
```

**Comment by ihumanable** [comment]
Answered
