### ISSUE TITLE
script break when sending sms

### ISSUE THREAD

**Issue by adeelshaffi** [twilio/twilio-php#261]
Hi!
I am using a twilio php library. I have written a script which send reminder to users automatically. below is the code

    try {
        $response = $client->account->messages->SendMessage($from_number, $to_number, $sms_message);
        if (isset($response->sid)) {
            $message_delivery_status = 'Delivered';
        }
    } catch (Services_Twilio_RestException $e) {
        echo $e->getMessage();
    }

But it neither displays any error, nor any exception. Script break at first line inside Try block when sms is being sent.

I cannot find whats is the problem. I am stuck. Please help.

**Comment by philnash** [comment]
Your problem is the call to `$client->account->messages->SendMessage`. The method is actually [`sendMessage`](https://github.com/twilio/twilio-php/blob/3ec47c0bf8bce1a25e02e007c1245405bdadb7a6/Services/Twilio/Rest/Messages.php#L57), you just have the "s" capitalised and that is throwing an error that your try/catch isn't looking for.

**Comment by adeelshaffi** [comment]
Oh ok. I copied the code from example mentioned here in twilio doc.
by the way will this work too?
    $response = $client->account->messages->create(array(
        "From" => $from_number,
        "To" => $to_number,
        "Body" => $sms_message
    ));

**Comment by adeelshaffi** [comment]
no its still not working. can you please tell what else could it be?

**Comment by philnash** [comment]
I don't know. Do you get any errors from Twilio or a stack trace from your code? What is your current code?

**Comment by adeelshaffi** [comment]
here is the error: (error reporting turned off by client before)

Fatal error: Call to a member function sendMessage() on null in file_name.php on line 180

code:

function send_sms_reminder($from_num,$to_num,$message){
    try {
        $response = $client->account->messages->sendMessage($from_num, $sms_number_phone, $sms_message); // THIS is LINE 180.
        if (isset($response->sid)) {
            $message_delivery_status = 'Delivered';
        }
    } catch (Services_Twilio_RestException $e) {
        echo $e->getMessage();
    }
}

**Comment by philnash** [comment]
So, that error message is saying that you're calling `sendMessage` on `null`.

Where is `$client` set in respect to that function? And how do you create it?

**Comment by adeelshaffi** [comment]
here is the full function code

    function send_sms_reminder($client_account_sid, $client_auth_token,$from_num,$to_num,$message){
        $account_sid = $client_account_sid;
        $auth_token = $client_auth_token;
        $client = new Services_Twilio($account_sid, $auth_token);
        *// var_dump($client); returned object:object(Services_Twilio)*
        try {
            $response = $client->account->messages->sendMessage($from_num, $sms_number_phone, $sms_message); // THIS is LINE 180.
            if (isset($response->sid)) {
                $message_delivery_status = 'Delivered';
            }
        } catch (Services_Twilio_RestException $e) {
            echo $e->getMessage();
        }
    }

please see the screenshot containing var_dump of $client object
![check](https://cloud.githubusercontent.com/assets/13587633/10578492/ec2b8e34-768b-11e5-8a05-49beda854875.png)

**Comment by Gipetto** [comment]
Is that the full function code? If so, your input parameters to `send_sms_reminder()` don't match the params the you pass in to `$client->account->messages->sendMessage()`. 

You take in `$to_num` but then you try to send the message with `$sms_number_phone`. You have the same problem with `$message` and `$sms_message`.

You need to make sure that you're passing valid information to the Twilio api client.

**Comment by adeelshaffi** [comment]
Sorry, i changed the code after starting this thread. I have updated my last comment to have correct function parameters being used.

The error is still the same and i thought it was related to related to $client object. but i have posted screenshot of that too. Is there any problem with that?

**Comment by philnash** [comment]
What do you get if you `var_dump`:
* `$client->account`
* `$client->account->messages`
?

**Comment by adeelshaffi** [comment]
please see the screenshot of dumping both the 1- $client->account & 2- $client->account->messages
![vardump_result](https://cloud.githubusercontent.com/assets/13587633/10606561/22820a00-774d-11e5-9964-538986ab8329.png)

**Comment by philnash** [comment]
That's really weird. What version of the twilio-php library are you using?

**Comment by adeelshaffi** [comment]
yeah my bad. it was definitely older version. I updated it to the latest version and now its working.
Thanks for your great help.

**Comment by philnash** [comment]
Ah, good stuff! Glad I could help :)
