### ISSUE TITLE
How to verify phonenumber before sending SMS 

### ISSUE THREAD

**Issue by ahmedwafdi** [twilio/twilio-php#263]
hello i want to verify phonenumber before  sending any sms and to avoide any exceptions .i know that twilio provide a lookups service but if the phonenumber was incorrect it throw "The requested resource /PhoneNumbers/0600100 was not found" ;
any idea ??

**Comment by carlosdp** [comment]
It sounds like you have the right idea, you're going to have to catch that 404 exception if you want to use the Lookups API.

If you need more information or guidance, I'd recommend contacting support at https://www.twilio.com/help/contact . They are always standing by to answer questions about how to use our API and likely have a nice snippet of code for you to look at!
