### ISSUE TITLE
Extra slash in requests, but only on certain environments

### ISSUE THREAD

**Issue by ctrlaltdylan** [twilio/twilio-php#266]
Hello,

We're using the Twilio PHP client in our application. It's been tested locally and on our staging server (Amazon E2) and the application works fine.

However on our production environment the client does not format URLs as expected and adds an extra / to the request:

```
Services_Twilio_RestException·The requested resource /2010-04-01/Accounts//AvailablePhoneNumbers/US/Local.json was not found
```

The production environment is also Amazon E2, but never had a problem with other API wrappers. Thanks for your help!

Dylan

**Comment by philnash** [comment]
Hey Dylan,

That extra slash is actually the place that your Account SID would slip into the path. Like this:

```
/2010-04-01/Accounts/{{ ACCOUNT_SID }}/AvailablePhoneNumbers/US/Local.json
```

Perhaps you have an environment variable that you haven't set yet in production?

**Comment by ctrlaltdylan** [comment]
Wow. Huge facepalm here. That's definitely it.

Thank you!

**Comment by philnash** [comment]
No problem! I think that's something we've all done at some point and the URL does not make it obvious what went on. Glad you're sorted though!
