### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by thisispiers** [twilio/twilio-php#272]
I need to autoload the library with my project but it doesn't support namespaced autoloading.
Are there plans for this or do I have to manually namespace every file?
There is this repo: https://github.com/AlekseyKorzun/twilio-php-5 but that is wildly out of date.

Thanks

**Comment by kenmulford** [comment]
+1 for namespacing

**Comment by thisispiers** [comment]
No update on PSR-2 autoloading compatibility?

**Comment by carlosdp** [comment]
We're finishing up a new version of the library that will be namespaced. The current release candidate target is end of this month / beginning of February. It'll also improve a ton of other stuff.

**Comment by kenmulford** [comment]
Awesome!! Thanks for the update!

**Comment by tcrammond** [comment]
Has there been any update on this? Thanks

**Comment by carlosdp** [comment]
You can try out twilio-php version `5.0.0-RC1` which uses namespacing. It's also an entirely new library, so it works a little differently. We'll have a migration doc up soon.

**Comment by carlosdp** [comment]
https://github.com/twilio/twilio-php/wiki/5.x-Migration-Guide

**Comment by pantaoran** [comment]
I tried to get version 5.0.0-RC1 to work for sending SMS, but I failed. The calls described in the migration guide don't work as described, and I couldn't find any other documentation. So for now I'm going back to 4.10.

**Comment by ihumanable** [comment]
@pantaoran There was an error in the CurlClient for the 5.0.0-RC1, my apologies for the inconvenience.

This issue has been corrected in 5.0.0-RC2.

**Comment by ihumanable** [comment]
The 5.0.0 line has matured a great deal, 5.0.0-RC19 is very usable now and has full namespace support.
