### ISSUE TITLE
Fatal error: Uncaught exception 'Services_Twilio_TinyHttpException' with message 'Could not resolve host: taskrouter.twilio.com' in C:\wamp\www\twilio\Services\Twilio\TinyHttp.php on line 119

### ISSUE THREAD

**Issue by vinitdave27** [twilio/twilio-php#273]
I am trying to test the Twilio REST API for listing workers under my account. I am running a WAMP server with PHP 5.5.12 with curl 7.36.

Can you please help me troubleshoot this further. 

Awaiting your response. Have a nice day!!!

<?php
    // Download the Twilio-PHP library from twilio.com/docs/libraries,
    // and move it into the folder containing this file.
    require 'Services/Twilio.php';
 
    // Set your AccountSid and AuthToken
    $accountSid = 'accountSid';
    $authToken = 'authToken';
 
    // Set your WorkspaceSid and WorkflowSid
    $workspaceSid = 'workspaceSid'; 
    $workflowSid = 'workflowSid'; 

    
	// instantiate a new Twilio TaskRouter Rest Client 
    $taskrouterClient = new TaskRouter_Services_Twilio($accountSid, $authToken, $workspaceSid); 

    // create a new task 
    $taskrouterClient->workspace->tasks->create('{"selected_language": "es"}', $workflowSid); 

    // display a confirmation message on the screen
    echo "Created a new task"
?>

**Comment by vinitdave27** [comment]
I am also getting the error "Fatal error: Uncaught exception 'Services_Twilio_TinyHttpException' with message 'SSL certificate problem: self signed certificate in certificate chain' in C:\wamp\www\twilio\Services\Twilio\TinyHttp.php on line 119"

I have searched the same online, there have been vague descriptions for a solution but none seem to work. I would appreciate if you could share a detail solution for the same as well.

**Comment by ihumanable** [comment]
This is related to the Twilio SSL Certificate upgrade.  Updating your server root store to the latest should resolve issues.
