### ISSUE TITLE
Reject the older PHP versions

### ISSUE THREAD

**Issue by githubjeka** [twilio/twilio-php#276]
- 5.2 and 5.3 too old to support them and adapt to them. Freeze tag for them.
- Accept to [PSR-4](http://www.php-fig.org/psr/psr-4/)
- Use [phpDoc](http://www.phpdoc.org/)

**Comment by ihumanable** [comment]
The newest version, 5.x, supports 5.3+ using namespaces and many more best practices.  It has PSR-4 style namespaces and utilizes a prefixed PSR-4 autoloader when installed through composer, it has a custom autoloader based off the PSR-4 reference implementation when installed without composer.

All documentation is now in PHP Doc, we use the excellent https://github.com/apigen/apigen tool to generate handsome documentation at https://twilio.github.io/twilio-php
