### ISSUE TITLE
Autocomplete to Client object

### ISSUE THREAD

**Issue by githubjeka** [twilio/twilio-php#277]
Autocomplete `$this->client->` doesn't work. 
For example [here](https://github.com/twilio/twilio-php/blob/master/Services/Twilio/Rest/Call.php#L114)

![image](https://cloud.githubusercontent.com/assets/874234/12135902/3782beac-b453-11e5-8f06-e56251806c28.png)

**Comment by ihumanable** [comment]
The newest version 5.x fully supports autocomplete.  The 4.x line has been put into maintenance mode.
