### ISSUE TITLE
API certificate issues in Debian Jessie 8.3 

### ISSUE THREAD

**Issue by smelchior** [twilio/twilio-php#285]
As already mentioned in the issue #203 an ssl error is returned if the "Thawte Premium Server CA" certificate is missing from the ssl truststore as it is send by api.twilio.com. 
The recent Debian 8.3 point release updated the ca-certificates package to remove this certificate from the store though:
http://metadata.ftp-master.debian.org/changelogs/main/c/ca-certificates/ca-certificates_20141019+deb8u1_changelog

So as more and more people update to that release, they will not be able to use the API properly. We fixed this manually on our servers by readding the certificate to the store, but that cannot be the solution. You should consider to remove this certificate from your chain.

**Comment by ftzdomino** [comment]
A Twilio support response says that the issue isn't on their end.  Here's the kludgy fix for Debian Jessie:

wget "https://easyccconfig.googlecode.com/files/Thawte%20Premium%20Server%20CA.cer" -O /tmp/twiliokludge.cer
sudo openssl x509 -inform der -in /tmp/twiliokludge.cer -out /usr/local/share/ca-certificates/twiliokludge.crt
rm /tmp/twiliokludge.cer
sudo chmod 0644 /usr/local/share/ca-certificates/twiliokludge.crt
sudo chown root.root  /usr/local/share/ca-certificates/twiliokludge.crt
/usr/sbin/update-ca-certificates

**Comment by nvanheuverzwijn** [comment]
Why would debian remove that certificate ? Is it because it is insecure ?

**Comment by nvanheuverzwijn** [comment]
*RSA-1024 removed *
Around early September 2014, Mozilla removed the trust bits from the certs in their CA bundle that were still using RSA 1024 bit keys. This may lead to TLS libraries having a hard time to verify some sites if the library in question doesn't properly support "path discovery" as per RFC 4158. (That includes OpenSSL and GnuTLS.)

**Comment by jkrehm** [comment]
Seems like Twilio needs to update their certificate or switch SSL providers.

I just ran into this problem on OSX using the `cacert.pem` from http://curl.haxx.se/docs/caextract.html (we use that so our Windows clients can verify SSL).

**Comment by carlosdp** [comment]
We're talking to our security team to figure this out, will provide updates here when we have a game plan. Thanks guys!

**Comment by flyandi** [comment]
Any updates here - it seems the only work around right now is to disable SSL verification.

**Comment by nvanheuverzwijn** [comment]
@flyandi no, you have to download their certificate and add it to your chain. I am no expert in ssl but ftzdomino solution worked for me.

**Comment by carlosdp** [comment]
We've identified the issue and are working to resolve it server-side, will post here when that happens.

**Comment by nvanheuverzwijn** [comment]
@carlosdp Any news, ETA ? Thanks !

**Comment by nvanheuverzwijn** [comment]
Just wanted to add some info regarding ftzdomino script. Sometimes, `/usr/sbin/update-ca-certificates` does not call `c_rehash`. Simply add `-f` option to `update-ca-certificates` like this: `/usr/sbin/update-ca-certificates -f`.

**Comment by carlosdp** [comment]
We have removed the bad cert from our chain, hopefully this fixes the issue. Let me know if this worked!

**Comment by jkrehm** [comment]
I'm still getting `curl: (51) SSL: certificate verification failed (result: 5)` when I do the following:

1. Download https://curl.haxx.se/ca/cacert.pem to `/tmp/cacert.pem`
2. Run `curl --cacert /tmp/cacert.pem https://api.twilio.com`

If I append the bad cert (following) to the end of `cacert.pem` then it works.

````
thawte Premium Server CA
========================
-----BEGIN CERTIFICATE-----
MIIDNjCCAp+gAwIBAgIQNhIilsXjOKUgodJfTNcJVDANBgkqhkiG9w0BAQUFADCB
zjELMAkGA1UEBhMCWkExFTATBgNVBAgTDFdlc3Rlcm4gQ2FwZTESMBAGA1UEBxMJ
Q2FwZSBUb3duMR0wGwYDVQQKExRUaGF3dGUgQ29uc3VsdGluZyBjYzEoMCYGA1UE
CxMfQ2VydGlmaWNhdGlvbiBTZXJ2aWNlcyBEaXZpc2lvbjEhMB8GA1UEAxMYVGhh
d3RlIFByZW1pdW0gU2VydmVyIENBMSgwJgYJKoZIhvcNAQkBFhlwcmVtaXVtLXNl
cnZlckB0aGF3dGUuY29tMB4XDTk2MDgwMTAwMDAwMFoXDTIxMDEwMTIzNTk1OVow
gc4xCzAJBgNVBAYTAlpBMRUwEwYDVQQIEwxXZXN0ZXJuIENhcGUxEjAQBgNVBAcT
CUNhcGUgVG93bjEdMBsGA1UEChMUVGhhd3RlIENvbnN1bHRpbmcgY2MxKDAmBgNV
BAsTH0NlcnRpZmljYXRpb24gU2VydmljZXMgRGl2aXNpb24xITAfBgNVBAMTGFRo
YXd0ZSBQcmVtaXVtIFNlcnZlciBDQTEoMCYGCSqGSIb3DQEJARYZcHJlbWl1bS1z
ZXJ2ZXJAdGhhd3RlLmNvbTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA0jY2
aovXwlue2oFBYo847kkEVdbQ7xwblRZH7xhINTpS9CtqBo87L+pW46+GjZ4X9560
ZXUCTe/LCaIhUdib0GfQug2SBhRz1JPLlyoAnFxODLz6FVL88kRu2hFKbgifLy3j
+ao6hnO2RlNYyIkFvYMRuHM/qgeN9EJN50CdHDcCAwEAAaMTMBEwDwYDVR0TAQH/
BAUwAwEB/zANBgkqhkiG9w0BAQUFAAOBgQBlkKyID1bZ5jA01CbH0FDxkt5r1DmI
CSLGpmODA/eZd9iy5Ri4XWPz1HP7bJyZePFLeH0ZJMMrAoT4vCLZiiLXoPxx7JGH
IPG47LHlVYCsPVLIOQ7C8MAFT9aCdYy9X9LcdpoFEsmvcsPcJX6kTY4XpeCHf+Ga
WuFg3GQjPEIuTQ==
-----END CERTIFICATE-----
````

Note: cURL in PHP gives the same error as the CLI command.

**Comment by carlosdp** [comment]
@jkrehm can you try this again? the bad cert chain was definitely removed and I do see the Thawte root cert in that pem. Could you try just letting curl use the default trust store?

**Comment by jkrehm** [comment]
It works when I use the default trust store on my Mac, but it worked there before, too. For my company's product we have to use a CA file because half of our clients are on Windows and either Windows doesn't have a store of its own, or PHP/cURL doesn't know how to make use of it automatically. So we deliver a CA file with the application and use that.

I don't have a Debian instance to test with, so I don't know if the issue is resolved there. If no one else has a problem and it's an issue with https://curl.haxx.se/ca/cacert.pem (which comes from Firefox) then I'll just have to keep appending that `thawte Premium Server CA` certificate to the file, which isn't the end of the world. But from what you said, it seems like that certificate should not be necessary anymore.

**Comment by carlosdp** [comment]
@jkrehm yea that PEM must be out of date, you can even use Firefox to access api.twilio.com and it handshakes fine.

**Comment by smelchior** [comment]
As far as i can see the bad chain cert was removed, but Debian Jessie still has issues with it as before. This behaviour is described in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812708#15 
I am not sure when or if it will be fixed though.

**Comment by carlosdp** [comment]
Ah yea, well there doesn't seem to be anything wrong on our end, that might just have to be resolved by the Debian team. I'll let our team know this is an ongoing issue though! Thanks guys!
