### ISSUE TITLE
 file_get_contents(): SSL operation failed with code 1.

### ISSUE THREAD

**Issue by dendisuhubdy** [twilio/twilio-php#287]
PHP Notice:  Undefined index: number in /var/www/html/register.php on line 10
PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /var/www/html/twilio-php/Services/Twilio/HttpStream.php on line 67
PHP Warning:  file_get_contents(): Failed to enable crypto in /var/www/html/twilio-php/Services/Twilio/HttpStream.php on line 67
PHP Warning:  file_get_contents(https://api.twilio.com/2010-04-01/Accounts/ACd258fdf27d26ab96a0dc07e8284a7519/Messages.json): failed to open stream: operation failed in /var/www/html/twilio-php/Services/Twilio/HttpStream.php on line 67
PHP Fatal error:  Uncaught exception 'Services_Twilio_HttpStreamException' with message 'Unable to connect to service' in /var/www/html/twilio-php/Services/Twilio/HttpStream.php:70
Stack trace:
#0 /var/www/html/twilio-php/Services/Twilio.php(179): Services_Twilio_HttpStream->__call('post', Array)
#1 /var/www/html/twilio-php/Services/Twilio.php(179): Services_Twilio_HttpStream->post('/2010-04-01/Acc...', Array, 'To=&From=%2B125...')
#2 /var/www/html/twilio-php/Services/Twilio/ListResource.php(92): Base_Services_Twilio->createData('/2010-04-01/Acc...', Array)
#3 /var/www/html/twilio-php/Services/Twilio/Rest/Messages.php(24): Services_Twilio_ListResource->_create(Array)
#4 /var/www/html/register.php(16): Services_Twilio_Rest_Messages->create(Array)
#5 {main}
  thrown in /var/www/html/twilio-php/Services/Twilio/HttpStream.php on line 70

**Comment by ihumanable** [comment]
This error indicates that your server's certificate store does not trust the SSL certificate served by the Twilio API.  Updating your certificate store should address the issue.  If you are manually pinning an SSL Cert chain you should unpin and use your distributions best security practices.
