### ISSUE TITLE
Ubuntu 14.04.1 ca-certificates/20160104ubuntu0.14.04.1 causes SSL error

### ISSUE THREAD

**Issue by jak** [twilio/twilio-php#291]
> 'Error: Uncaught exception 'Services_Twilio_TinyHttpException' with message 'SSL certificate problem: unable to get local issuer certificate' in /home/citypantry/project/api/vendor/twilio/sdk/Services/Twilio/TinyHttp.php:119

After upgrading Ubuntu 14.04.1 LTS ca-certificates package to `20160104ubuntu0.14.04.1` (published 15 hours ago) this error occurs when attempting to contact Twilio using 4.10.0 of the PHP SDK.

Rolling back the package update returns normal service, however a fix needs to be found.

**Comment by jak** [comment]
This actually seems due to an SSL change Twilio rolled out at 3PM PST 24 Feb 2016 and have since reverted. It's just a huge coincidence ca-certificates was updated and released at the same time.

On a server which had not been downgraded, restarting php-fpm/nginx removed the error.

**Comment by mattstauffer** [comment]
I bashed my head on this for days with twilio. I thought I had lost my mind.
