### ISSUE TITLE
SSL Certificate problem: unable to get local issuer certificate in vendor/twilio/sdk/Services/Twilio/TinyHttp.php:119

### ISSUE THREAD

**Issue by luoshiben** [twilio/twilio-php#292]
I haven't rolled code in weeks, but all of a sudden we're getting the error:
exception 'Services_Twilio_TinyHttpException' with message 'SSL certificate problem: unable to get local issuer certificate' in /vendor/twilio/sdk/Services/Twilio/TinyHttp.php:119

I just updated to the latest version of twilio/sdk (4.10.0) but still no go. Any ideas? Thanks in advance!

**Comment by mikelinington** [comment]
@luoshiben I'm having the same issue, this closed issue from a few hours ago suggests that bouncing your server will fix the problem: https://github.com/twilio/twilio-php/issues/291

**Comment by luoshiben** [comment]
@mikelinington You're a lifesaver. I didn't think to look at closed issues for an issue that just recently started happening. Doing a restart `php5-fpm` (ubuntu) got things working again.

**Comment by carlosdp** [comment]
Sorry about that guys! An SSL change was made yesterday and is now reverted. Closing issue as this isn't a PHP problem.
