### ISSUE TITLE
Uncaught exception 'Services_Twilio_RestException' with message 'AfterSid is required for paging.' in /usr/share/php/Services/Twilio.php:297

### ISSUE THREAD

**Issue by Thominus** [twilio/twilio-php#296]
I noticed the exception posted below in my logs - it occurs whenever I try to retrieve a list of messages. 

**Version:** twilio-php v4.10.0, originally noticed in 4.8.1
My environment is apache v2.4.18, php5-fpm v5.6.17

### Code Snippet
//example from https://www.twilio.com/docs/api/rest/message#list-get-example-1
$client = new Services_Twilio('AC123', '123');
foreach ($client->account->messages as $message) {
    echo "From: {$message->from}\nTo: {$message->to}\nBody: " . $message->body;
}

```

### Exception / Log
```
PHP Fatal error:  Uncaught exception 'Services_Twilio_RestException' with message 'AfterSid is required for paging.' in /usr/share/php/Services/Twilio.php:297\nStack trace:\n#0 /usr/share/php/Services/Twilio.php(265): Base_Services_Twilio->_processResponse(Array)\n#1 /usr/share/php/Services/Twilio.php(236): Base_Services_Twilio->_makeIdempotentRequest(Array, '/2010-04-01/Acc...', 1)\n#2 /usr/share/php/Services/Twilio/ListResource.php(125): Base_Services_Twilio->retrieveData('/2010-04-01/Acc...', Array)\n#3 /usr/share/php/Services/Twilio/ListResource.php(179): Services_Twilio_ListResource->getPage(7, 50, Array, NULL)\n#4 [internal function]: Services_Twilio_ListResource->getPageGenerator(7, 50, Array, NULL)\n#5 /usr/share/php/Services/Twilio/AutoPagingIterator.php(104): call_user_func_array(Array, Array)\n#6 /usr/share/php/Services/Twilio/AutoPagingIterator.php(77): Services_Twilio_AutoPagingIterator->loadIfNecessary()\n#7 /home/twtesting/messagelist.php(18): Services_Twilio_AutoPagingIte...\n'

```

### Steps to Reproduce
1. implement something that lists messages as per examples such as shown at https://twilio-php.readthedocs.org/en/latest/usage/rest/messages.html#listing-messages  or https://www.twilio.com/docs/api/rest/message#list-get-example-1. The exception does not seem to occur when listing calls. 

2. The function works as expected but logs show this error.

**Comment by carlosdp** [comment]
@Thominus will be fixed by #297, we also are deploying a server-side fix for this, it's a legacy behavior we are trying to deprecate. It looks like you are working around this for now?

**Comment by Thominus** [comment]
@carlosdp Excellent!  Yes, for now - no problem for me to work around.

**Comment by ihumanable** [comment]
As #297 has landed I will be closing this issue.
