### ISSUE TITLE
Undefined property: Services_Twilio_Rest_Message::$status

### ISSUE THREAD

**Issue by Arhanger** [twilio/twilio-php#298]
### Undefined property: Services_Twilio_Rest_Message::$status
twilio/sdk/Services/Twilio/InstanceResource.php Line: 82

```php
public function __get($key)
    {
        if ($subresource = $this->getSubresources($key)) {
            return $subresource;
        }
        if (!isset($this->$key)) {
            $params = $this->client->retrieveData($this->uri);
            $this->updateAttributes($params);
        }
        return $this->$key;
    }
```
Even after calling updateAttribute property $this->$key might be not set. So it generates a notice. Expected behavior is to throw an Exception or to return null w/o generating notice.

### Steps to Reproduce
1. Execute the following code with not existing sid. **$twilioService** is an instance of \Services_Twilio

```php
$message = $twilioService->account->messages->get($sid);
$message->status;
```

**Comment by ihumanable** [comment]
New 5.x line eagerly loads properties to avoid this issue.
