### ISSUE TITLE
On line 53 

### ISSUE THREAD

**Issue by ZaheerAghani** [twilio/twilio-php#299]
Parse error: syntax error, unexpected ' ' (T_STRING), expecting ')' in /home/vol13_5/base.pk/basep_17328406/htdocs/wp-content/plugins/twilio-video/twilio-video.php on line 53 this is code line 53 is idenetity parameter
$return = array(
        'identity' => $identity,
        'token' => $token->toJWT(),
    );
    $response = new WP_REST_Response( $return );
    return $response;

**Comment by jingming** [comment]
Please direct this question to help@twilio.com

**Comment by ZaheerAghani** [comment]
thanks. problem has been solved...
