### ISSUE TITLE
Send same SMS to an array of mobile numbers

### ISSUE THREAD

**Issue by KTrentLR** [twilio/twilio-php#300]
Feature request: I know I can loop through a group of mobile numbers and do a send on each mobile, but if I have an array of numbers I want to send the same message to, is there a PHP method I can call to allow me to do this? This allows me on the server side to just do one call/method and finish versus looping through each number. It would still queue up on the twilio servers and only send 1/sec, but again, makes development easier and I don't need to worry about script process time.

**Comment by ihumanable** [comment]
The Messaging API does not support bulk-send operations at this time.  I will pass this suggestion along to our Product Team.

**Comment by ccloquet** [comment]
+1

**Comment by ihumanable** [comment]
I have provided this feedback to our Messaging Team.  If this feature becomes available in the API it will be made available in all helper libraries.  Since this request is not specific to `twilio-php` I'm going to close this particular issue.

**Comment by ccloquet** [comment]
Thank you so much !

**Comment by ricardofadini** [comment]
Hi, is this feature currently available?
I didn't find anything about it on Twilio docs.
Thanks!

**Comment by imthepitts** [comment]
@ricardofadini Thanks for checking with us. The Messaging API still does not support bulk-send operations. If you need further assistance or have additional questions, please reach out to our support team: https://www.twilio.com/console/support/tickets/create
