### ISSUE TITLE
Error Sending sms 

### ISSUE THREAD

**Issue by jollybi04** [twilio/twilio-php#301]
Hello there , i have some problems with my sender of text .
This is the error when i receive when i press send .Can anibody to help me pleasE ?

<br /> <b>Fatal error</b>: Uncaught exception 'Services_Twilio_RestException' with message 'Authenticate' in /home/u789333249/public_html/send/twilio-php-master/Services/Twilio.php:297 Stack trace: #0 /home/u789333249/public_html/send/twilio-php-master/Services/Twilio.php(180): Base_Services_Twilio-&gt;_processResponse(Array) #1 /home/u789333249/public_html/send/twilio-php-master/Services/Twilio/ListResource.php(92): Base_Services_Twilio-&gt;createData('/2010-04-01/Acc...', Array) #2 /home/u789333249/public_html/send/twilio-php-master/Services/Twilio/Rest/Messages.php(24): Services_Twilio_ListResource-&gt;_create(Array) #3 /home/u789333249/public_html/send/send.php(15): Services_Twilio_Rest_Messages-&gt;create(Array) #4 {main} thrown in <b>/home/u789333249/public_html/send/twilio-php-master/Services/Twilio.php</b> on line <b>297</b><br />

**Comment by jingming** [comment]
Please contact help@twilio.com for more details.
