### ISSUE TITLE
Error on Instantiation of Services_Twilio_Twiml. Wrong PHP Version? 

### ISSUE THREAD

**Issue by eshlepper** [twilio/twilio-php#302]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

I had been manually using the PHP DOMDomdocument class to write the Twiml for a while, with great success, and figured I'd use the official library for a new project; It seemed like essentially just what I'd been doing. No luck. Can't even instantiate a Twilio_Services_Twiml object.

**Version:** PHP Version 5.2.17!!!! 
**API Subdomain (api/taskrouter/ip_messaging):**

### Code Snippet
```php
$response = new Services_Twilio_Twiml();
```

### Exception / Log
```
None thrown. Parse Error.
```

### Steps to Reproduce
1. Include library.
2. Instantiate $response = new Twilio_Services_Twiml(); incidentally, some docs show Twilio_Services_Twiml (ie, with no parenthesis, instantiating a new object without calling constructor??????, using the class name?????, as per the info here: https://twilio-php.readthedocs.org/en/latest/usage/twiml.html#usage-twiml, but that can't be right: Other docs call constructor: https://twilio-php.readthedocs.org/en/latest/#generating-twiml
3. Error on instantiation:
Parse error: syntax error, unexpected T_STATIC, expecting T_STRING or T_VARIABLE or '$' in {mydir}/twilio-php/Services/Twilio/Twiml.php on line 121

### Feature Request
_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by Gipetto** [comment]
FYI: if a class' constructor takes no arguments there's no functional difference between `new MyClassName();` and `new MyClassName;`.

This is a feature of PHP.

**Comment by Gipetto** [comment]
`return new static($child);` in `Twiml.php` will fail on PHP 5.2.x - this feature was added in php 5.3.

It appears that backwards incompatible changes have been made and the minimum compatible version in the `readme` and `composer.json` have not been updated.

**Comment by ihumanable** [comment]
Answered
