### ISSUE TITLE
GETting IPM Users by Identity returns incorrect SID

### ISSUE THREAD

**Issue by matthewmoehring** [twilio/twilio-php#307]
**Version:** <= 4.10.0
**API Subdomain:** ip_messaging

When retrieving Users in IP Messaging by Identity, the user is retrieved, but the `sid` field contains the Identity used to retrieve the user and not the SID for that user.

### Example
```php
$client = new IPMessaging_Services_Twilio("ACCOUNT_SID", "ACCOUNT_TOKEN");
$service = $client->services->get("SERVICE_SID");
$user = $service->users->get("IDENTITY"); // Note: this is a request for Identity, not SID
print $user->sid; // Will contain the identity instead
```

When retrieving a User via a custom REST call to `GET /Services/{Instance SID}/Users/{Identity}`, the `sid` and `identity` fields **do** contain the correct information.

**Comment by matthewmeehan** [comment]
+1

**Comment by Josephwaelchli** [comment]
+1

**Comment by ihumanable** [comment]
The current generation of the helper library lazy loads all properties, when you have code that does this.
```php
$user = $service->users->get("IDENTITY");
```
Internally it sets the `sid` field, which is used later on for generating the URL to go fetch.  Once the fetch is executed the `sid` field will be correctly populated with the `sid` of the user.  The library will perform the fetch if you attempt to access a field that isn't populated, you can force the library to fetch by calling the `synchronize()` method added in 4.11.0
