### ISSUE TITLE
Twilio Operation timed out issue

### ISSUE THREAD

**Issue by poonam6785** [twilio/twilio-php#315]
I need some help regarding php twilio helper library.I am trying to fetch ad store sms logs from my twilio account to local database.But i am not able to get all logs after recieving half of them its showing this error

"Services_Twilio_TinyHttpException in TinyHttp.php line 119: Operation timed out after 59030 milliseconds with 32143 out of 57975 bytes received"

I dnt find out a way how to use nexturi for this issue

I am using like this
foreach ($client->account->messages as $msg){

}

**Comment by ihumanable** [comment]
It looks like your request is taking in excess of 59s, which should not happen, can you please open a ticket with help@twilio.com
