### ISSUE TITLE
Wrong namespace broken autoload

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-php#316]
**Version:** 5.0-RC6
**API Subdomain (api/taskrouter/ip_messaging):** TwiML

### Code Snippet
```php
<?php
require '/Users/xxxxxx/dev/api-snippets/tools/dependencies/php/5.0.0-RC6/vendor/autoload.php';

// Get the PHP helper library from twilio.com/docs/php/install

use Twilio\Twiml\Twiml;
$twiml = new Twiml();
```

### Exception / Log
```
PHP Fatal error:  Class 'Twilio\Twiml\Twiml' not found in /Users/xxxxx/dev/api-snippets/test.php on line 7
```

### Steps to Reproduce
1. Run the snippet above

I'm using RC6 version of the library. Apparently autoload will use folder structure to load namespaces. As you can see [here](https://github.com/twilio/twilio-php/blob/next-gen/Twilio/Twiml.php#L3), the Twiml class is in the wrong directory.

**Comment by mcelicalderon** [comment]
@jwitz10 Please take a look, we are trying to build a DevEd tutorial using the next-gen library. We are also creating the API docs code snippets for v5 of this library.

**Comment by carlosdp** [comment]
Thanks! Fix will go out on next release d7d9be9

**Comment by mcelicalderon** [comment]
Awesome, thanks @carlosdp

**Comment by ihumanable** [comment]
Twiml class is staying toplevel, but the namespace was been fixed per this PR https://github.com/twilio/twilio-php/pull/336
