### ISSUE TITLE
Unencoded keys on request parameters

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-php#318]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

**Version:** 5.0.0-RC6
**API Subdomain (api/taskrouter/ip_messaging):** API

### Code Snippet
```php
<?php
// Get the PHP helper library from twilio.com/docs/php/install
require_once('/path/to/vendor/autoload.php'); // Loads the library
use Twilio\Rest\Client;

// Your Account Sid and Auth Token from twilio.com/user/account
$sid = "ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
$token = "your_auth_token";
$client = new Client($sid, $token);

$calls = $client->account->calls->stream(
    array("status" => "completed", "starttimeAfter" => "2009-07-06"),
    50
);
// Loop over the list of calls and echo a property for each one
foreach ($calls as $call) {
    echo $call->to;
}
```

### Exception / Log
```
Not actual exception, but empty result.
```

### Steps to Reproduce
1. Run the snippet above.
2. Inspect request made to the API
3. URL key is not encoded properly.

Current version of the Twilio API supports query parameters like this one:

```
/2010-04-01/Accounts/ACXXXXXXXXXXXXXXXXXXXXX/Calls.json?Status=completed&StartTime%3E=2009-07-06
```

The next-gen version of this library also has support for this parameter as you can see [here](https://github.com/twilio/twilio-php/blob/next-gen/Twilio/Rest/Api/V2010/Account/CallList.php#L161). This will set the argument's key as `StartTime>`.

[Here](https://github.com/twilio/twilio-php/blob/next-gen/Twilio/Http/CurlClient.php#L140) is where the parameter's values get url_encoded but the keys are not encoded. The result of this will be a request to this URL:

```
/2010-04-01/Accounts/ACXXXXXXXXXXXXXXXXXXXXX/Calls.json?Status=completed&StartTime&gt;=2009-07-06
```

This will return an invalid response and cause problems in some testing frameworks when parsing the URL.

**Comment by mcelicalderon** [comment]
Awesome, thanks.

**Comment by ihumanable** [comment]
Updated in 5.0.0-RC10
