### ISSUE TITLE
Magic Method not working for base resources

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-php#329]
**Version:** 5.0.0-RC7
**API Subdomain (api/taskrouter/ip_messaging):** Taskrouter, API

### Code Snippet
```php
$activities = $client->taskrouter->workspaces()
    ->getContext($workspaceSid)
    ->activities
    ->read();
```

I'm not 100% sure that this is the right way to access taskrouter resources, but I can't find another way to do it. [This method](https://github.com/twilio/twilio-php/blob/next-gen/Twilio/Rest/Taskrouter.php#L81) is the one we are using to get a workspace list, and then we have to call getContext() instead of using the "magic method" as we do with the other resources. We should be able to so something like this:

```php
$activities = $client->taskrouter
    ->workspaces($workspaceSid)
    ->activities
    ->read();
```

The same goes for the accounts resource on the REST API. Magic method doesn't work for accounts, so now we have to do:

```php
$account = $client
    ->accounts
    ->getContext("ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    ->fetch();
```

This only happens in accounts, the rest of subresources can use the magic method to access a context directly.

**Comment by ihumanable** [comment]
This appears to be an error in how yoyodyne generates the convenience aliases, I think I have a plan for how to fix this and we should have a build within the next day or two with this fixed

**Comment by mcelicalderon** [comment]
Awesome, please let me know when this is released as I would have to modify the snippets to use the new syntax. Thanks!

**Comment by ihumanable** [comment]
Fixed in 5.0.0-RC17

**Comment by ihumanable** [comment]
Actually RC17 doesn't quite fix it all the way, RC18 does.

**Comment by mcelicalderon** [comment]
I might have to fix all the docs snippets before the 11th. I see that with the new version the methods I was using are gone. Will start doing that tomorrow. Thanks!
