### ISSUE TITLE
Missing Worker->reservations resource

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-php#331]
**Version:** 5.0.0-RC7
**API Subdomain (api/taskrouter/ip_messaging):** Taskrouter

Reservations sub resource is missing for workers in taskrouter.

This is the resource URI:

```
https://taskrouter.twilio.com/v1/Workspaces/WSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Workers/WKaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Reservations
```

**Comment by ihumanable** [comment]
Fixed in https://github.com/twilio/twilio-php/commit/967e0008091cab7e2d17bb3d0ca27b2c581c16ab

Released as 5.0.0-RC13
