### ISSUE TITLE
Non optional unique name (IP Messaging Channel)

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-php#337]
**Version:** 5.0.0-RC7
**API Subdomain (api/taskrouter/ip_messaging):** ip_messaging

`unique_name` should be an optional parameter when creating new channels in IP messaging. The docs confirm it and I also tested it with a direct call to the API. 

[This create method](https://github.com/twilio/twilio-php/blob/next-gen/Twilio/Rest/IpMessaging/V1/Service/ChannelList.php#L43) requires a unique name.

**Comment by jingming** [comment]
Released with `5.0.0-RC9`.
