### ISSUE TITLE
Wrong TwiML namespace (next-gen)

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-php#338]
**Version:** 5.0.0-RC7
**API Subdomain (api/taskrouter/ip_messaging):** TwiML

This is an important one. TwiML generation is broken due to a wrong namespace declaration [here](https://github.com/twilio/twilio-php/blob/next-gen/Twilio/Twiml.php#L3). There's even an open PR that fixes this https://github.com/twilio/twilio-php/pull/336
This PR also addresses this issue https://github.com/twilio/twilio-php/pull/310

As far as I'm concerned TwiML generation works fine once you fix the namespace error. We have manually changed this before in order for it to work. A release fixing this would be nice soon as we have a bunch of content and tutorials that won't work without this change.

**Comment by ihumanable** [comment]
PR Merged
