### ISSUE TITLE
User (IP Messaging) resource update/create params

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-php#340]
**Version:** 5.0.0-RC7
**API Subdomain (api/taskrouter/ip_messaging):** ip_messaging

[user resource](https://github.com/twilio/twilio-php/blob/next-gen/Twilio/Rest/IpMessaging/V1/Service/UserContext.php#L74) on IP Messaging doesn't allow the update of parameters other than the role. Based on the docs you should also be able to update `friendlyName` and `attributes`.

The same goes for the [create method](https://github.com/twilio/twilio-php/blob/next-gen/Twilio/Rest/IpMessaging/V1/Service/UserList.php#L42) on this resource. No way to specify attributes or friendlyName

**Comment by jingming** [comment]
Released with `5.0.0-RC9`.
