### ISSUE TITLE
Non optional update params (notify->credentials)

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-php#341]
**Version:** 5.0.0-RC7
**API Subdomain (api/taskrouter/ip_messaging):** notify

[This update operation](https://github.com/twilio/twilio-php/blob/next-gen/Twilio/Rest/Notifications/V1/CredentialContext.php#L64) for Credential resource in Notifier should have optional parameters. I should be able to update only `friendlyName` for example.

**Comment by jingming** [comment]
Released with `5.0.0-RC9`.
