### ISSUE TITLE
Detailed error messages missing

### ISSUE THREAD

**Issue by dprothero** [twilio/twilio-php#342]
**Version:** 5.0.0-RC8

PHP next-gen library doesn't seem to be returning detailed error messages, at least in my work with TaskRouter .... for example, in the current 4.x library, if I try to accept a reservation that has already been accepted, I get this message: "Reservation WRc42d8bbeb6dd080b89beff9a6b85340a is already in state [accepted] and cannot be updated to [accepted]" which is a *great* error message

However, in 5.x I just get "Unable to update record"

4.x code:
```php
$taskrouterClient = new TaskRouter_Services_Twilio($accountSid, $authToken, $workspaceSid); 
$taskrouterClient->workspace->tasks->get($taskSid)->reservations->get($reservationSid)->update('ReservationStatus', 'accepted'); 
```

5.x code:
```php
$client = new Client($accountSid, $authToken);

// update the reservation
$client->taskrouter->workspaces()
    ->getContext($workspaceSid)
    ->tasks($taskSid)
    ->reservations($reservationSid)
    ->update('accepted');
```

**Comment by ihumanable** [comment]
This is fixed in https://github.com/twilio/twilio-php/commit/704fd2d6749429d5a636a7a2fed9588e08db34c9

Released as 5.0.0-RC14
