### ISSUE TITLE
about twilio

### ISSUE THREAD

**Issue by califat** [twilio/twilio-php#344]
it doesn't accept for me 

Fatal error: Uncaught Services_Twilio_TinyHttpException: SSL certificate problem: self signed certificate in certificate chain in C:\xampp\htdocs\www\twilio\twilio-php\Services\Twilio\TinyHttp.php:119 Stack trace: #0 C:\xampp\htdocs\www\twilio\twilio-php\Services\Twilio.php(178): Services_Twilio_TinyHttp->__call('post', Array) #1 C:\xampp\htdocs\www\twilio\twilio-php\Services\Twilio\ListResource.php(92): Base_Services_Twilio->createData('/2010-04-01/Acc...', Array) #2 C:\xampp\htdocs\www\twilio\twilio-php\Services\Twilio\Rest\Messages.php(24): Services_Twilio_ListResource->_create(Array) #3 C:\xampp\htdocs\www\twilio\index.php(13): Services_Twilio_Rest_Messages->create(Array) #4 {main} thrown in C:\xampp\htdocs\www\twilio\twilio-php\Services\Twilio\TinyHttp.php on line 119

**Comment by ihumanable** [comment]
Please contact help@twilio.com for this issue.
