### ISSUE TITLE
Usage resources, unable to filter

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-php#347]
**Version:** 5.0.0
**API Subdomain (api/taskrouter/ip_messaging):** API

`Rest/Api/V2010/Account/Usage/Record/ ` list classes won't allow users to filter results based on a usage property. [This method](https://github.com/twilio/twilio-php/blob/next-gen/Twilio/Rest/Api/V2010/Account/Usage/Record/TodayList.php#L96) for instance, should be able to receive an array with properties to filter results. The docs say [this](https://www.twilio.com/docs/api/rest/usage-records#list-get-filters) and the snippet I'm trying to write filters usage records by category.

**Comment by ihumanable** [comment]
@mcelicalderon this appears to be an error in the API Definitions, will update and regen.

**Comment by mcelicalderon** [comment]
Thanks @ihumanable !

**Comment by ihumanable** [comment]
Fixed in https://github.com/twilio/twilio-php/tree/5.0.0-RC12
