### ISSUE TITLE
Missing filters for availablePhoneNumberCountry reading

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-php#348]
**Version:** 5.0.0-RC11
**API Subdomain (api/taskrouter/ip_messaging):** API

AvailablePhoneNumberCountry (Local, Mobile, Toll Free) won't allow filtering numbers by all the allowed parameters defined in the REST API. [This](https://github.com/twilio/twilio-php/blob/next-gen/Twilio/Rest/Api/V2010/Account/AvailablePhoneNumberCountry/LocalList.php#L105) and the respective classes for other phoneNumber types are missing some allowed filters like latitude, longitude, region. The method already supports the basic query params, [here](https://www.twilio.com/docs/api/rest/available-phone-numbers#local-get-advanced-filters) is a list of the advanced ones (only for US and Canada)

**Comment by ihumanable** [comment]
Fixed in https://github.com/twilio/twilio-php/tree/5.0.0-RC12
