### ISSUE TITLE
Lookups not handling spaces in phone number

### ISSUE THREAD

**Issue by ejunker** [twilio/twilio-php#365]
I am in the process of upgrading from version 4.x of the library to 5.1. With the 4.x version I could do phone lookups with a value of `515 222-1212` and it would work. Now after upgrading to 5.1 I get a `[HTTP 400] Unable to fetch record` exception. I figured out that if I remove the space in the number it works. For example, `515%20222-1212` where the space is encoded as `%20` does not throw an exception.

Is this expected behavior?

Here is example code that throws the exception.
```php
$client->lookups->phoneNumbers('515 222-1212')->fetch();
```

If I run the number through `rawurlencode()` before passing it in, it works.

**Comment by ihumanable** [comment]
This seems like a regression, will investigate

**Comment by ihumanable** [comment]
Thank you for reporting this regression, it is addressed in https://github.com/twilio/twilio-php/pull/370 and will be considered for immediate inclusion.

**Comment by ihumanable** [comment]
This was fixed in version 5.1.1
