### ISSUE TITLE
Does the sample on the main page need updating?

### ISSUE THREAD

**Issue by ytn3rd** [twilio/twilio-php#367]
The sample to send a text says 
```
$message = $client->account->messages->create(
  '9991231234', // From a valid Twilio number
  '8881231234', // Text this number
  array(
    'Body' => "Hello from Twilio!"
  )
);
```

But this errors with "A 'From' phone number is required".
But according to the source , https://github.com/twilio/twilio-php/blob/8e045e781b73368ede7e8e4337db8ba4d00a7692/Twilio/Rest/Api/V2010/Account/MessageList.php#L43

The function should be written as
```
$message = $client->account->messages->create(
  '8881231234', // Text this number
  array(
    'From' =>   '9991231234', // From a valid Twilio number
    'Body' => "Hello from Twilio!"
  )
);
```
and then this works. 

Does the README.MD (and all the other API reference docs which list it wrong) need updating, or am I not seeing things correctly.

**Comment by mcelicalderon** [comment]
Hey @ytn3rd, You are right! That's the way that example should be written. Could you please point me to the page where this example is written in the wrong way? Thanks!

PD: You can find examples for most of the API functionality in [the API docs](https://www.twilio.com/docs/api/rest). This one in particular [here](https://www.twilio.com/docs/api/rest/sending-messages#example-1)

**Comment by ytn3rd** [comment]
The example for [sending a text](https://www.twilio.com/docs/api/rest/sending-messages#example-1) that you linked does not follow the 'From' parameter rule. They are also C#, unsure if the issue of samples not being updated extends to C#. 

The other example I had where I got it from wrong was on the [composer page](https://packagist.org/packages/twilio/sdk), but that may have just pulled the README.MD from here.

**Comment by mcelicalderon** [comment]
Hey! You are right, I'll create a PR to update the README file. But about the [docs example I shared](https://www.twilio.com/docs/api/rest/sending-messages#example-1), the C# example does have a different method signature, but in the snippet widget you should be able to select `PHP` and specifically library version `5.x`

**Comment by ytn3rd** [comment]
Oh, thanks. I didn't even see the dropdown. I thought it was odd all the samples in the docs were in C#!
