### ISSUE TITLE
[3.13.1] Signature validation fails if Addons are enabled

### ISSUE THREAD

**Issue by prionkor** [twilio/twilio-php#371]
Addons are recent inclusion of Twilio and can be added by user from their account. I am twilio php sdk `v3.13.1` and signature string aren't matching when addons are enabled.

Is latest version of the sdk tested against this? If it does I am willing to upgrade. Also is there any breaking changes happened that I should be count on before I upgrade.

**Comment by efossier** [comment]
@prionkor Yes this should be fixed in the latest 5.x library. There will most likely be a fair amount of breaking changes upgrading from 3.x to 5.x, here is a migration guide to get you started: https://www.twilio.com/docs/libraries/php/migration-guide
