### ISSUE TITLE
Issue when calling a Twilio client

### ISSUE THREAD

**Issue by brayann** [twilio/twilio-php#378]
So I just ran into an issue and I couldn't figure it out, so either I'm doing something wrong or there's an issue with the new library.

I'm trying to call a Twilio client, we are identifying clients as `user_{id}_{company_id}`.

When I try to call a client with the following code: 

```php

$this->client->calls->create(
    "client:user_{$user->id}_{$user->company_id})", 
    "+{$from}", 
    [
	    "url" => \URL::to("/twilio/conference?CallUUID={$this->call->CallUUID}")
    ]
);

```

I get a RestException: `21211 [HTTP 400] Unable to create record: Called is not valid: client:user_290_3)`.

I checked the error number and it says it's an invalid number, however I'm dialing a Twilio client, not a number. https://www.twilio.com/docs/api/errors/21211

I also tried using the API explorer on the Twilio Console, and it worked normally in there, however I noticed it's an older version of the PHP library, because A) it's not even the same class name, and B, the To parameter is the second one and not the first like on the new library.

Let me know, thanks,

**Comment by imthepitts** [comment]
Looks like you're generating an invalid Client name:

```
client:user_290_3)
```

^ Note the parenthesis at the end of the ID.

Client names must contain only alphanumeric and underscore characters.

Try this instead:

```php
$this->client->calls->create(
  "client:user_{$user->id}_{$user->company_id}",
  "+{$from}",
  [
    "url" => \URL::to("/twilio/conference?CallUUID={$this->call->CallUUID}")
  ]
);
```

**Comment by brayann** [comment]
Wow, you're right, I don't know how I missed that, lol.

Thanks for spotting this, good eye!

**Comment by adilameeq** [comment]
I'm facing invalid client name..
How i can generate client name ?
If anyone know please help 
thank

**Comment by johnpaulmedina** [comment]
You must first generate a token using the Twilio-php library. Then using the ClientJS library when that client uses the token you will no longer receive invalid client.

https://www.twilio.com/docs/voice/client/tutorials/capability-tokens <https://www.twilio.com/docs/voice/client/tutorials/capability-tokens>



John Paul Medina, Partner
Lead Trust Media Group

Email: jp@leadtrust.io
Phone: (305) 804-9506



“To shape the organization not through the power of will or dictate, but rather through example, through coaching and through understanding and helping to achieve their goals"
