### ISSUE TITLE
Unable to create record: authenticate

### ISSUE THREAD

**Issue by ba01739** [twilio/twilio-php#380]
I'm getting the following error message:  Uncaught exception 'Twilio\Exceptions\RestException' with message '[HTTP 401] Unable to create record: Authenticate'

Below is my script.

``` php
<?php
error_reporting(E_ALL);
// Require the bundled autoload file - the path may need to change
// based on where you downloaded and unzipped the SDK
require  'autoload.php';

// Use the REST API Client to make requests to the Twilio REST API
use Twilio\Rest\Client;

// Your Account SID and Auth Token from twilio.com/console
$sid = 'SK679251dde54ae13ed6cabeeb1e5ffcf2';
$token = 'token';
$client = new Client($sid, $token);

// Use the client to do fun stuff like send text messages!
$client->messages->create(
    // the number you'd like to send the message to
    '+15555555555',
    array(
        // A Twilio phone number you purchased at twilio.com/console
        'from' => '+15555555555',
        // the body of the text message you'd like to send
        'body' => "Hey Jenny! Good luck on the bar exam!"
    )
);

?>
```

**Comment by ihumanable** [comment]
Based off the snippet you provided, it looks like you are trying to use an API Key (SK Sid Prefix is used for an API Key).

When using an API Key you should construct the client, as follows.

```php
<?php

require 'autoload.php';

use Twilio\Rest\Client;

$keySid = 'SK679251dde54ae13ed6cabeeb1e5ffcf2';
$keySecret = 'the-secret-returned-on-creation';
$accountsid = 'ACyouraccountsid';

$client = new Client($keySid, $keySecret, $accountSid);

// Use the $client to do things
```

**Comment by akshaykmr286** [comment]
What is $keysecret and $accountsid in this filr?
I have token and sid only

**Comment by gviger** [comment]
Having the same problem and have the same question as @akshaykmr286

**Comment by ihumanable** [comment]
@akshaykmr286 @gviger 

If you have a standard Account Sid (starts with `AC`) and Auth Token (found in the [Console](https://www.twilio.com/console)) then the following code should work

```php
<?php

require 'autoload.php';

use Twilio\Rest\Client;

$accountSid = 'ACyouraccountsid';
$authToken = 'yourauthtoken';

$client = new Client($accountSid, $authToken);

// Use the $client to do things
```

Only use the above snippet if you are using [API Keys](https://www.twilio.com/docs/api/rest/keys)

An easy way to know if you are trying to use API Keys is if you are authenticating with a something that starts with `SK`, all API Keys start with `SK`

**Comment by HeatfanJohn** [comment]
@ihumanable thank you for pointing out how to use the overloaded Client method.

FYI, this doesn't appear to be documented in the Twilio online documentation.  In fact, the Twilio Python SDK isn't very well documented.  A sample call is given and then you're told to see the REST API which documents the HTTP calls that the Python SDK uses, but doesn't show the methods of the Python SDK.

**Comment by efossier** [comment]
We've completely rewritten the library for 5.x so this is not really applicable anymore. The new library mirrors the rest api much more closely.

**Comment by khushi84throne** [comment]
Fatal error: Uncaught exception 'Twilio\Exceptions\ConfigurationException' with message 'Credentials are required to create a Client' in C:\wamp\www\sms\vendor\twilio\sdk\Twilio\Rest\Client.php on line 144
Twilio\Exceptions\ConfigurationException: Credentials are required to create a Client in C:\wamp\www\sms\vendor\twilio\sdk\Twilio\Rest\Client.php on line 144

**Comment by lakshsyal123** [comment]
Hey I want to check user credentials is write or not I used the below code and if the credentials is wrong I got "[HTTP 401] Unable to fetch record: Authenticate" with 500 page error. 
I installed "twilio/sdk": "^5.16" this version. 
Kindly confirm me where I am wrong.

$client = new Client($userName, $userPass);
$account = $client->api->accounts($userName)->fetch();

Thanks

**Comment by fahidjavid** [comment]
If anyone is trying to make calls and facing **Fatal error: Uncaught Twilio\Exceptions\RestException: [HTTP 400] Unable to create record: Account not authorized** issue then what you need to do is go to the https://www.twilio.com/console/voice/calls/geo-permissions/low-risk page (login required) and check the countries/country to which you are making calls, then save.

**Comment by prolonginc** [comment]
out issue was not sufficient funds :\ drove us nutts lol.

**Comment by naveen509** [comment]
> Having the same problem and have the same question as @akshaykmr286

did you fix the error? i have the same issue

**Comment by prolonginc** [comment]
Hello @naveen509  the issue was that there was no money in the account.

**Comment by naveen509** [comment]
> @akshaykmr286 @gviger
> 
> If you have a standard Account Sid (starts with `AC`) and Auth Token (found in the [Console](https://www.twilio.com/console)) then the following code should work
> 
> ```
> <?php
> 
> require 'autoload.php';
> 
> use Twilio\Rest\Client;
> 
> $accountSid = 'ACyouraccountsid';
> $authToken = 'yourauthtoken';
> 
> $client = new Client($accountSid, $authToken);
> 
> // Use the $client to do things
> ```
> 
> Only use the above snippet if you are using [API Keys](https://www.twilio.com/docs/api/rest/keys)
> 
> An easy way to know if you are trying to use API Keys is if you are authenticating with a something that starts with `SK`, all API Keys start with `SK`

i have the same src code but 

> Hello @naveen509 the issue was that there was no money in the account.

thank you for your quick reply. but its a trail account it worked initially and i received the sms but now not working . in twilio site they saying one month it will work

**Comment by naveen509** [comment]
> 
 

> thank you for your quick reply. but its a trail account it worked initially and i received the sms but now not working . in twilio site they saying one month it will work

**Comment by prolonginc** [comment]
@naveen509 yeah that is different from what i experienced. it seems that certain things fail and it triggers the 401 likely just bad exception handling

**Comment by naveen509** [comment]
ok. is there any other way to solve this ?

**Comment by usmanraza5245** [comment]
Hi there, I am using twilio messaging service to send messages. From last month, on localhost this error comes every time when i send message ,,"[HTTP 401] Unable to fetch page: Authenticate" , but sending message on live server is working well. On local and on live server the code is same.

**Comment by usmanraza5245** [comment]
Can anyone tell me what's the problem?

**Comment by childish-sambino** [comment]
@usmanraza5245 Please open a new issue as closed issues are not tracked as closely.

**Comment by naveen509** [comment]
thank you for your quick reply. but its a trail account it worked initially
and i received the sms but now not working . in twilio site they saying one
month it will work

**Comment by nawazfdev** [comment]
This error is just occur when put the wrong twilio credentials , see again credentials carefully and make this correct hopefully error will solve , in my case same error i was facing just because of wrong Twilio credentials
