### ISSUE TITLE
Fatal error: Class 'Twilio\Rest\Client' not found 

### ISSUE THREAD

**Issue by MerrickLee** [twilio/twilio-php#384]
For some reason I'm getting this error. I added the folder to my site and tried to do a send like the given example. 

Anyone come across this?

**Comment by jingming** [comment]
@MerrickLee Thanks for writing in! 

What version of the library are you using? and what is the code you are running?

**Comment by akshaykmr286** [comment]
I am getting the same error.

**Comment by paulan94** [comment]
Same error for me.

**Comment by MerrickLee** [comment]
I figured out the issue on my end....  Test this on your servers and see if this works. 
Copy and Paste their /Twilio folder in a directory on your site (DO NOT CHANGE "Twilio" folder name).

Make a file and add this code with your credentials. Then go to that page on a URL. Hopefully you should get a text within 15seconds.

```
<?php
require __DIR__ . '/Twilio/autoload.php';

// Use the REST API Client to make requests to the Twilio REST API
use Twilio\Rest\Client;

// Your Account SID and Auth Token from twilio.com/console
$sid = '#YOUR SID#';
$token = '#YOUR TOKEN#';
$client = new Client($sid, $token);


$send_number = '555555555'; // Add Number to Send To
$twilio_number = '555555555';// Add Your registered Twilio Number
$message = 'Merrick Lee freaking rocks!!!';

$send_number = '+1'.$send_number.'';
$twilio_number = '+1'.$twilio_number.'';


$client->messages->create(
    
    $send_number,
	
    array(
        'from' => $twilio_number,
        'body' => $message,
    )
);
?>
```

**Comment by ihumanable** [comment]
@MerrickLee yes, you are correct, the Twilio autoloader that ships in the non-Composer version follows the [PSR-4](http://www.php-fig.org/psr/psr-4/) conventions, so the namespaces and directories have to match.

**Comment by tommym9** [comment]
Hi,

I am seeing this issue when I've pulled in the library via composer. In my file I have the following:

`<?php

namespace Drupal\twilio_integration;

use Twilio\Rest\Client;

/**
 * Class DefaultService.
 */
class DefaultService {

    /**
    * Constructs a new DefaultService object.
    */
    public function __construct() {
      
        $this->client = new Client($this->account_sid, $this->auth_token);`

And I'm getting the `Error: Class 'Twilio\Rest\Client' not found in` error.

If I call the client directly `new Twilio\Rest\Client($this->account_sid, $this->auth_token);` then PHPStorm says that Rest is an undefined namespace.

This is being pulled into a Drupal 8 site which has autoloading. 

I can't see anything immediately wrong, fingers crossed someone else can spot my mistake.

Cheers

Tom
