### ISSUE TITLE
Failed to connect to api.twilio.com port 443

### ISSUE THREAD

**Issue by Prince029** [twilio/twilio-php#385]
HI

I am using twililo fist time.

got this error 

PHP Fatal error:  Uncaught exception 'Twilio\Exceptions\EnvironmentException' with message 'Failed to connect to api.twilio.com port 443: Connection timed out' in twilio-php-master/Twilio/Http/CurlClient.php:33
Stack trace:
#0 twilio-php-master/Twilio/Rest/Client.php(189): Twilio\Http\CurlClient->request('POST', 'https://api.twi...', Array, Array, Array, 'ACf82863388e634...', '0fe9fdb570767e7...', NULL)
#1 twilio-php-master/Twilio/Domain.php(70): Twilio\Rest\Client->request('POST', 'https://api.twi...', Array, Array, Array, NULL, NULL, NULL)
#2 twilio-php-master/Twilio/Version.php(64): Twilio\Domain->request('POST', '2010-04-01/Acco...', Array, Array, Array, NULL, NULL, NULL)
#3 twilio-php-master/Twilio/Version.php(204): Twilio\Version->request('POST', '/Accounts/ACf82...', Array, Array, Array, NULL, NULL, NULL)
#4 twilio-php-master/Twili in /home/pdweb6mb/public_html/demo/twilio-php-master/Twilio/Http/CurlClient.php on line 33

how can i solve this?. is there any mistake by me here ?

Please help me.

**Comment by ihumanable** [comment]
This looks like a connectivity issue between your server and Twilio, you should make sure that https://api.twilio.com can be resolved from the server.  For more detailed help, contact help@twilio.com
