### ISSUE TITLE
make Holodeck return multiple responses in sequence

### ISSUE THREAD

**Issue by kevinburke** [twilio/twilio-php#393]
I'm trying to test this function without going over the network:

```php
    // Buy a US number in the given area code. If no numbers are available, try
    // to buy any number.
    public function buyNumber(string $areaCode, array $properties = array()) {
        $cp = $properties;
        $cp['AreaCode'] = $areaCode;
        try {
            // If just buying a number works, great.
            return $this->client->incomingPhoneNumbers->create($cp);
        } catch (RestException $e) {
            if ($e->getCode() === ERROR_NO_PHONE_NUMBERS_AREA_CODE) {
                return $this->buyAnyNumber('US', $properties);
            }
            throw $e;
        }
    }
```

I can e.g. attach a fake version of the Twilio client, or subclass the Class and return mock objects, but I would rather take the Holodeck approach of saving the actual Twilio HTTP response and returning that to an instance of the client. 

As far as I can tell however Holodeck only allows you to save/return one response, which is useful for e.g. integration testing the twilio-php library against Twilio but doesn't solve my problem.

It would be nice if you could set multiple responses and then send them in sequence in response to requests. (I might try to write this but I am wondering if there's a design decision that led you to deliberately not do this.)

**Comment by kevinburke** [comment]
If there are other general purpose libraries that solve this problem, let me know, there's this: https://php-vcr.github.io/ but I am worried by "Doing this in PHP is not as easy as in programming languages which support monkey patching"

**Comment by kevinburke** [comment]
This turned out to be a pretty simple patch! https://gist.github.com/kevinburke/788475a0e658b3b55b7848f3f4d1c819

Happy to submit as a PR

**Comment by efossier** [comment]
@kevinburke sounds reasonable, im not aware of any design decisions that would forbid this. Can you submit a PR and we'll get this into the next release?

**Comment by ilanbiala** [comment]
PR #435 implements this.
