### ISSUE TITLE
How to disable CURLOPT_SSL_VERIFYPEER in Twilio rest client?

### ISSUE THREAD

**Issue by mostafasoufi** [twilio/twilio-php#398]
Hello @tacman 

How to disable `CURLOPT_SSL_VERIFYPEER` in the Curl? i can disable this with hard code.

Line 28 - `CurlClient.php`
`curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);`

But i want disable on the `Twilio\Rest\Client`

Regards

**Comment by philnash** [comment]
Hello! It is not recommended to disable `CURLOPT_SSL_VERIFYPEER`. From the [documentation for curl](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html):

> WARNING: disabling verification of the certificate allows bad guys to man-in-the-middle the communication without you knowing it. Disabling verification makes the communication insecure. Just having encryption on a transfer is not enough as you cannot be sure that you are communicating with the correct end-point.
