### ISSUE TITLE
twilio:sms "The 'To' number phone=+35193XXXXXXX is not a valid phone number"

### ISSUE THREAD

**Issue by apoca** [twilio/twilio-php#399]
I'm doin gsomething wrong?

### Exception / Log
MacBook-Pro-de-Miguel:esolidar-laravel apoca$ php artisan twilio:sms phone=+35193XXXXXXX
Sending SMS via Twilio to: phone=+35193XXXXXXX
This is a test message sent from the artisan console

                                                                    
  [Services_Twilio_RestException]                                   
  The 'To' number phone=+35193XXXXXXX is not a valid phone number.  
                                                                    

MacBook-Pro-de-Miguel:esolidar-laravel apoca$ 
<place exception / log here>

**Comment by efossier** [comment]
Hi @apoca, That seems like the api is returning you a 400 and is not specific to this library. Please contact support@twilio.com for issues like these.
