### ISSUE TITLE
Blank Exception being returned

### ISSUE THREAD

**Issue by StevenDStanton** [twilio/twilio-php#400]
**sdk version 5.4.2**
***API Subdomain: /2010-04-01/Accounts/xxx/Calls/xxx**

We are having an odd issue with our setup. We are using Phalcon, Ratchet and the Twilio PHP sdk. 

Our code is approximately as follows.

The client is successfully created and valid. 

    $client = new Client($sid, $token)

Then when we run the following code 

    try{
        $call = $client->calls($data)->fetch();
        echo $call->message;
    } catch (Exception $e){
        echo "Error: " . $e->getMessage();
    }

The only return we get in Ratchet is...

    An error has occurred:

This happens anytime we have execute the fetch() line.  It is not throwing an exception that we can check with the try catch block.

We checked debugging directly on the server and the exception is being thrown but is coming back empty

    object(Twilio\Exceptions\EnvironmentException)#101 (7) {
     ["message":protected]=>
     string(0) ""
     ["string":"Exception":private]=>
     string(0) ""
     ["code":protected]=>
     int(0)

I have confirmed that we are using valid data as I used the SID and Token to log directly into the website. While in the above example I have $data I have tried hard coding the SID we are checking in.

**Comment by efossier** [comment]
@StevenDStanton Is `$data` a string here? It must be a call sid to fetch. 
In regards to your error the only place we throw `EnvironmentException` is in `https://github.com/twilio/twilio-php/blob/master/Twilio/Http/CurlClient.php`, my guess is that `curl_error` call is returning an empty string.

**Comment by StevenDStanton** [comment]
@efossier at this point I don't even remember. That was 6 months ago, I forgot this was even still here and open
