### ISSUE TITLE
Uncaught Exception in CurlClient.php

### ISSUE THREAD

**Issue by noahfeder** [twilio/twilio-php#414]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

`CurlClient->request()` throws an `EnvironmentException` if there is an issue reaching the API. However, the catch statement only catches an `ErrorException` and then immediately throws that error again, resulting in an uncaught exception. Instead, should `CurlClient` instantiate a `Response` with a 4XX/5XX error code?

**Version:** 5.4.2
**API Subdomain (api/taskrouter/ip_messaging):** api

### Code Snippet
```php
try {
  $this->client->messages->create($to, array("from" => $from, "body" => $body));
} catch (Twilio\Exceptions\RestException $e) {
   return false;
}
return true;
```

### Exception / Log
```
Uncaught Twilio\\Exceptions\\EnvironmentException: Could not resolve host: api.twilio.com in /path/to/vendor/twilio/sdk/Twilio/Http/CurlClient.php:33
Stack trace:
#0 /var/www/profile.crowded.com/public_html/vendor/twilio/sdk/Twilio/Rest/Client.php(180): Twilio\\Http\\CurlClient->request('POST', 'https://api.twi...', Array, Array, Array, 'XXX', 'XXX', NULL)
#1 /path/to/vendor/twilio/sdk/Twilio/Domain.php(61): Twilio\\Rest\\Client->request('POST', 'https://api.twi...', Array, Array, Array, 'XXX', 'XXX', NULL)
#2 /path/to/public_html/vendor/twilio/sdk/Twilio/Version.php(55): Twilio\\Domain->request('POST', '2010-04-01/Acco...', Array, Array, Array, NULL, NULL, NULL)
#3 /path/to/public_html/vendor/twilio/sdk/Twilio/Version.php(195): Twilio\\Version->request('POST', '2010-04-01/Acco...', Array, Array, Array, NULL, NULL, NULL)
#4 /var/www/profile.crowded.com/pub in /path/to/vendor/twilio/sdk/Twilio/Http/CurlClient.php on line 33, referer: https://url-foo-bar.com/benbot/

```

### Steps to Reproduce
1. The CurlClient.php could not reach api.twilio.com, and the exception was not handled.
2. This occurred around 10AM EST, Wednesday 3/22/17, and resolved itself by 10:50AM.

### Feature Request
Don't allow unhandled

**Comment by efossier** [comment]
@noahfeder No we dont want to instantiate a Response in this case since the error wasn't an HTTP error so a status code wouldnt make sense, we were not able to reach twilio at all. I think in this case throwing the exception is the desired behavior and your application should decide what to do with it (perhaps you want to retry or something).

**Comment by noahfeder** [comment]
Thanks for the response @efossier. I'm still a little confused and would love some guidance. 

I've encountered other typical errors (No message body, invalid or missing phone number, etc.) and they all throw a `RestException`, so every time I attempt sending a message I wrap the code in a try block and catch any `Twilio\Exceptions\RestException` and handle it appropriately.

Would you recommend adding a second catch block for `Twilio\Exceptions\EnvironmentException` and using different error handling behavior for this more site-wide type of issue?

**Comment by efossier** [comment]
@noahfeder Sure, so a RestException represents an HTTP Error which means it will have a status code. An EnvironmentException represents a problem in your dev/code environment preventing the request from completing successfully, in this case you are not able to resolve the api.twilio.com hostname. 

How you handle those different kinds of errors is up to you, if you dont care what kind of exception was thrown and want to perform the same recovery steps then you can catch the common ancestor of both those exception which is `Twilio\Exceptions\TwilioException`. If the recovery steps are different and you want to distinguish between the different exceptions then I would recommend adding a second catch block for the EnvironmentException.

Did that answer your question? Feel free to @ me if you have any other questions.

**Comment by noahfeder** [comment]
Much appreciate the clarification!
