### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by jamesgraham** [twilio/twilio-php#419]
**API Subdomain: video**

### Feature Request
Could we get a target release for adding [these APIs](https://www.twilio.com/docs/api/video/rooms-resource#create-room)?

In the meantime, is there a recommended way to use the Curl examples from the SDK?

**Comment by jingming** [comment]
hey @jamesgraham!

Since it is beta product, it is included in the `alpha` line of the library: https://github.com/twilio/twilio-php/blob/5.7.3-alpha1/Twilio/Rest/Video/V1/RoomList.php#L40

**Comment by jamesgraham** [comment]
Thanks @jingming just seen a new version out already 🔥
