### ISSUE TITLE
Unable to implement the twilio with codeigniter

### ISSUE THREAD

**Issue by lotus77888** [twilio/twilio-php#421]
![screenshot from 2017-04-24 19 04 29](https://cloud.githubusercontent.com/assets/27622060/25339674/160018e4-2921-11e7-8c8a-637a1fdd462c.png)

**Comment by lotus77888** [comment]
Can u tell me the step by step process with codeigniter3

**Comment by efossier** [comment]
Hey @lotus77888, thanks for writing in. Im not familiar with codeigniter3 and we dont provide step by step guides for specific frameworks, it should just work as long as you are running this on a supported php version. The twilio part of your code looks fine to me and that error message looks like it wasnt able to load your test file, it doesnt seem related to using the twilio helper library.
