### ISSUE TITLE
Twilio "Unknown context accounts" Error

### ISSUE THREAD

**Issue by amankr567** [twilio/twilio-php#426]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

**Version:**
**API Subdomain (api/taskrouter/ip_messaging):**

### Code Snippet
```php
// Required if your environment does not handle autoloading
require 'vendor/autoload.php';


// Use the REST API Client to make requests to the Twilio REST API
use Twilio\Rest\Client;

try{
// Your Account Sid and Auth Token from twilio.com/user/account
$sid = "AC4ac62d26b2d9ae7ec5dd89be5f3199dd";
$token = "166654767ee7dd76e990e0628be32519";
$client = new Client($sid, $token);

$account = $client->accounts("AC4ac62d26b2d9ae7ec5dd89be5f3199dd")->fetch();

echo $account->dateCreated->format('Y-m-d H:i:s');
} catch(Exception $e) {
  echo 'Message: ' .$e->getMessage();
}
```

### Exception / Log
```
Message: Unknown context accounts
```

### Feature Request
_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by jamesgraham** [comment]
Hi @amankr567 please see previous ticket #412
