### ISSUE TITLE
Fax API doesn't work 

### ISSUE THREAD

**Issue by ajamous** [twilio/twilio-php#430]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

**Version:**
**API Subdomain (api/taskrouter/ip_messaging):**

### Code Snippet
```php
# paste code here
```

### Exception / Log
```
<place exception / log here>
```

### Steps to Reproduce
1.
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by jingming** [comment]
@ajamous Please redirect this ticket to help@twilio.com! Be sure to include the version of the library you are using and include a code snippet of what you are trying to accomplish.
