### ISSUE TITLE
Received calls sometimes has doubled prefix

### ISSUE THREAD

**Issue by gianpaolodn** [twilio/twilio-php#432]
Hi,

I'm using the latest version of the Api (but I don't think this is kinda related with this bug).

This is my code:

> // Get the PHP helper library from twilio.com/docs/php/install
> require_once 'vendor/autoload.php'; // Loads the library
> use Twilio\Rest\Client;
> 
> // Your Account Sid and Auth Token from twilio.com/user/account
> $sid = "**";
> $token = "**";
> $client = new Client($sid, $token);
> $code = "7735";
> $from_number = "+390294759500";
> 
> $call = $client->calls->create("+393286175***", $from_number,["url" => "some_url"]);
> 
> echo $call->sid . "\n";

what is happening is that sometimes I receive the call from  +390294759500, others  "+39390294759500" (with the prefix 39 repeated twice)

The log in the console says the call is always from +390294759500.

What's going on?

**Comment by jmctwilio** [comment]
@gianpaolodn I'm not sure how to replicate this issue.  I've written the code that you have above and everything is working as expected.  Could you provide steps to reproduce?  Where are you seeing the double-prefix?  On your phone when the call is incoming?

**Comment by gianpaolodn** [comment]
This is my call list. I'm contact with twilio support as well. They escalated the case to the carrier for a check up.


![screenshot_20170616-180725](https://user-images.githubusercontent.com/5014553/27321560-f53a1c44-559a-11e7-800b-47d3d1491de7.png)

**Comment by jmctwilio** [comment]
@gianpaolodn  Thanks for your response!  I looked through the helper library code and didn't see a reason for this error to occur and couldn't reproduce it myself.  From the helper library, there are a number of services inside Twilio and outside Twilio which are involved.  Your ticket with Customer Support will probably have the best chance of diagnosing and fixing the issue.  They'll be able to trace the issue through Twilio's system and determine if it's internal or external.  Best of luck!

**Comment by gianpaolodn** [comment]
ok, I'm still waiting from the customer support.
