### ISSUE TITLE
Installation on laravel 5.* giving error

### ISSUE THREAD

**Issue by Kirtsen** [twilio/twilio-php#433]
Your requirements could not be resolved to an installable set of packages.

Problem 1
    - The requested package aloha/twilio 4.9.2 exists as aloha/twilio[1.0.1, 1.0.2, 1.1.0, 1.x-dev, 2.0.0, 2.0.0-RC1, 2.0.0-RC2, 2.0.0-RC3, 2.0.0-RC4, 2.0.0-RC5, 2.1.0, 2.1.1, 2.x-dev, 3.0.0, dev-master] but these are rejected by your constraint.

**Comment by jmctwilio** [comment]
@Kirtsen Thank you for pointing this out.  Unfortunately, we do not maintain the 'aloha/twilio' package.  Our most recent version is 5.11 and theirs is 3.0.0 (as you see in the output above).

Our recent flurry of releases has gotten ahead of their most recent release.  There's an open issue on their repo already (and I've added a comment to explain our multitude of changes).  You can follow that issue at their repository here:  https://github.com/aloha/laravel-twilio
