### ISSUE TITLE
API explorer is wrong

### ISSUE THREAD

**Issue by Migraine-42** [twilio/twilio-php#434]
**Version:** 5.11.0
**API Subdomain (api/taskrouter/ip_messaging):** queues

### Code Snippet
```php

$queues = $client->accounts($acid) 
  ->queues->read(); 
 
foreach ($queues as $queue) { 
    echo $queue->sid; 
}
```

In the line '$queues =...' the term 'accounts($acid) ' is redundant but this is the snippet that is shown in the PHP API explorer.  And actually did work in 5.4.2  this has been fixed in in 5.11.0 but the API explorer needs to be updated.

**Comment by jmctwilio** [comment]
@Migraine-42 Absolutely correct, thanks for pointing it out.  I'll notify our team.
