### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by brayann** [twilio/twilio-php#445]
I've posted this before here: #443 but you guys closed it and never got back to me. This is a serious issue where it's draining our server's memory, I had to restart the service the other day.

A few more details on the issue: The code that we have does just 3 calls to the Twilio API, and yet it's doing ~400 API calls per request. I went into New Relic and I was able to break down what the library is doing:

<img width="1155" alt="screen shot 2017-08-14 at 7 40 19 pm" src="https://user-images.githubusercontent.com/253673/29295086-e9c64ef0-8128-11e7-8d5d-c649e9dd41b4.png">

Can you please leave this open until it's fixed? Thanks!

----

**Version:5.7.1**

### Code Snippet
```php
/**
	 * Moves the user to a new call from another call, and then ends it
	 *
	 * @param Companiesleads $newCall
	 * @param Companiesleads $originalCall
	 * @return mixed
	 */
	public function answerAndHangup($newCall, $originalCall)
	{
		try {
			$this->client // moves the user to the conference of the new call
						->calls($originalCall->calltype->outbound ? $originalCall->CallUUID : $originalCall->ChildCallSid)
						->update(['Url'    => \URL::to("/twilio/conference?CallUUID={$newCall->CallUUID}&transferred=1")]);
			sleep(0.5);
			$this->client // ends the previous call (that he was currently active)
						->calls($originalCall->calltype->outbound ? $originalCall->ChildCallSid : $originalCall->CallUUID)
						->update(['status'    => 'completed']);
			$conference = $this->client->conferences->read(array("friendlyName" => $newCall->CallUUID)); // Here we move the other line to not be on hold, when user enters that conference room
			$conferenceUUID = $conference[0]->sid;
			$this->client
						->conferences($conferenceUUID)
						->participants($newCall->calltype->outbound ? $newCall->ChildCallSid : $newCall->CallUUID)
						->update(['Hold' => 'false']);
			return true;
		} catch (\Exception $e) {
			\Bugsnag::notifyException($e);
			return $e->getMessage();
		}
	}
```

### Exception/Log
```
Symfony\Component\Debug\Exception\FatalErrorException: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes)

Location
----------------
vendor/twilio/sdk/Twilio/Rest/Api/V2010/Account/ConferenceInstance.php:47 - Illuminate\Exception\Handler::handleShutdown

----

Error
----------------
Symfony\Component\Debug\Exception\FatalErrorException: Allowed memory size of 536870912 bytes exhausted (tried to allocate 32768 bytes)

Location
----------------
vendor/twilio/sdk/Twilio/Http/CurlClient.php:36 - Illuminate\Exception\Handler::handleShutdown
```

### Steps to Reproduce
Not really sure but it seems that if you try to do more than a couple of operations on the library, it uses a lot of memory, causing this error to occur.

**Comment by brayann** [comment]
After reading the code for a bit, the only thing I can think of that could cause this is the API call that searches for the conference instance. Do you guys go through all active conferences and filter it per page after you receive the data?

**Comment by dougblack** [comment]
Hey @brayann, we do all filtering on the server. There is no client-side filtering in the library.

You're using [`->read()`](https://twilio.github.io/twilio-php/5.13.0/class-Twilio.Rest.Api.V2010.Account.ConferenceList.html#_read) which eager loads records. You might want the more memory efficient [`->stream()`](https://twilio.github.io/twilio-php/5.13.0/class-Twilio.Rest.Api.V2010.Account.ConferenceList.html#_stream).

It is unclear what is causing the filter to return what seems to be so many records. Can you confirm `Call->CallUUID` exists on your custom call object and that there is only one (or few) conferences that match it?

**Comment by brayann** [comment]
Yes it's an unique field, which stores your `callSid`. I'll try to switch methods to see if I see any improvements.

**Comment by efossier** [comment]
@brayann Yeah the `stream` and `read` methods accepts the same arguments, one just lazyloads the results in pages (default size of 50) while the other loads everything at once.

Just to add to dougs suggestion, it seems like you are trying to find a single conference by a unique name, is it possible to store the sid of that conference and directly fetch that conference rather than iterating the list of conferences to find it?

**Comment by brayann** [comment]
Kind of.. we do some operations here where we constantly move them around conferences (call waiting, call hold, etc), so it's kind of tricky.. but I guess there's no other way, in case switching to stream doesn't help. Thanks anyway!

**Comment by efossier** [comment]
@brayann another thing to keep in mind, just because it is making a lot more requests than you may expect does not necessarily mean this is the cause of the memory leak. 

How long does it take approximately for the script to consume so much memory that it crashes?

Doing a cursory google search based off the fact that the error occurred in the CurlClient and we use this to make the requests, this may be a potential lead: https://bugs.php.net/bug.php?id=13225 We call `curl_setopt` in our code one each request.
