### ISSUE TITLE
Feature request: additional params when call created

### ISSUE THREAD

**Issue by developeruz** [twilio/twilio-php#446]
Is there a way to pass additional [params](https://github.com/twilio/twilio-php/blob/f9d388ff24b0767eff91551d8d26fbd2bd1c7387/Twilio/Rest/Api/V2010/Account/CallList.php#L84) when new call created? Could you please add this feature?

**Comment by johnpaulmedina** [comment]
The additional params will not come back to you because they wont be stored on the Twilio side.

**Comment by developeruz** [comment]
Actually, they do. If Twilio JS SDK is used for front end then in connection object there is message object which is contained all additional params
```
{
    "_maxListeners": 0,
    "_events": {...},
    "device": {...},
    "message": {
        //*** Any additional parameters will be accessible here ***//
    },
    "options": {...},
    "parameters": {...},
    "_status": "closed",
    "_direction": "INCOMING",
    "sendHangup": false,
    "_publisher": {...},
    "_monitor": {...},
    "mediaStream": {...},
    "outboundConnectionId": "...",
    "pstream": {...}
}
```
In our project, we have different sources of connected calls. It would be very helpful if I can detect that call was created through REST API. Do you know any other solutions that can help us to detect if it is a created call?

**Comment by developeruz** [comment]
It seems that this message object is used for JS SDK internal stuff and can't be passed through REST API ([discussion is here](https://stackoverflow.com/questions/45855323/how-to-add-additional-information-to-the-twilio-connect-object?answertab=active#tab-top))
