### ISSUE TITLE
There is no way to search for fax compatible available phone numbers

### ISSUE THREAD

**Issue by kiberzauras** [twilio/twilio-php#450]
**Version**:  5.15.2

`Twilio\Rest\Api\V2010\Account\AvailablePhoneNumberCountry\{LocalList, LocalOptions, MobileList, MobileOptions, TollFreeList, TollFreeOptions}`

Classes missing `faxEnabled` option and fluent methods `setFaxEnabled()` to filter available phone numbers with fax compability.

**Comment by efossier** [comment]
@kiberzauras This is slated to be available in the next release which just so happens is planned for today.
