### ISSUE TITLE
CURLOPT_INFILESIZE causes failure

### ISSUE THREAD

**Issue by tenaciousRas** [twilio/twilio-php#451]
**Version:**
5.13.0

### Code Snippet
```php
@@ -98,11 +98,11 @@ class CurlClient implements Client {
        $timeout = is_null($timeout)
            ? self::DEFAULT_TIMEOUT
            : $timeout;
+        unset($this->curlOptions[CURLOPT_INFILESIZE]);
        $options = $this->curlOptions + array(
            CURLOPT_URL => $url,
            CURLOPT_HEADER => true,
            CURLOPT_RETURNTRANSFER => true,
-            CURLOPT_INFILESIZE => -1,
            CURLOPT_HTTPHEADER => array(),
            CURLOPT_TIMEOUT => $timeout,
        );
```

### Exception/Log
```
Caught PHP Exception [/ta/v2/comm/[redacted] - [redacted]]: Twilio\Exceptions\EnvironmentException '' thrown by [redacted]/twilio/sdk/Twilio/Http/CurlClient.php:31
```

### Steps to Reproduce
1. update CURL to version 7.56.1 or higher
2. execute code such as ```Client->newKeys->create(['friendlyName' => $friendlyName]);```
3. exception (above) is thrown

We see the exception with this version of curl:
```
curl 7.56.1 (amd64-portbld-freebsd10.3) libcurl/7.56.1 OpenSSL/1.0.2l zlib/1.2.8 nghttp2/1.26.0
Release-Date: 2017-10-23
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy
```

With this version of curl we did not see the exception:
```
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
```

**Comment by jmctwilio** [comment]
@tenaciousRas I believe this change corrects the issue you were encountering:
    https://github.com/twilio/twilio-php/pull/453

Thank you for doing such a thorough job of tracking down the issue.  Looks like libcurl has been busy correcting problems that've been nagging for a while and traditional hacks stopped working.  We'll need to test it on various version of libcurl and PHP to ensure it works as expected, but I got no errors locally when I implemented and tested it with 7.54.0 and 7.56.1.  If it doesn't work for you, please let us know on the PR!
