### ISSUE TITLE
Function create_function() is deprecated in php 7.2.0

### ISSUE THREAD

**Issue by iamtheoleo** [twilio/twilio-php#452]
twilio/sdk/Services/Twilio/Resource.php

    /**
     * Return camelized version of a word
     * Examples: sms_messages => SMSMessages, calls => Calls,
     * incoming_phone_numbers => IncomingPhoneNumbers
     *
     * @param string $word The word to camelize
     * @return string
     */
    public static function camelize($word) {
        $callback = create_function('$matches', 'return strtoupper("$matches[2]");');
 
        return preg_replace_callback('/(^|_)([a-z])/',
            $callback,
            $word);
    }

**Comment by mnwalker** [comment]
Would be great if this can be addressed soon rather than leaving it for php7.3 to get close.

Many PHP frameworks (eg. Laravel) encourage enforce good code by throwing a full exception for any kind of error even if it could be ignored and code continue.
As such my app using Twilio breaks in php7.2 which is officially launching very soon.

I could suppress deprecated errors in config but that would defeat the purpose of getting them and would much prefer to run good compatible code.

Is this package controlled purely by the Twilio team or should I help with a pull request for a fix to this?

**Comment by reedmaniac** [comment]
Yes, we also ran into this problem with an app whose production instance is using PHP 7.2.  Going to need to find a solution.

**Comment by GigaMick** [comment]
I just deployed my app to Heroku and it has bombed out due to this function. Rather irritating. Is there a fix?

**Comment by Macuacua1** [comment]
I had the same error today on heroku, but 1 moth ago worked perfectly

**Comment by florinfratica** [comment]
> I could suppress deprecated errors in config but that would defeat the purpose of getting them and would much prefer to run good compatible code.

How can you do so in Laravel?

**Comment by mnwalker** [comment]
> How can you do so in Laravel?
@florinfratica  https://stackoverflow.com/questions/18497788/laravel-breaks-entire-app-on-php-notices

But php7.2 is released now and the biggest PHP framework crashes on site of this deprecation notice unless config is changed from default.
So now is definitely a good time to work on making things future compatible, especially if as reported backwards compatibility is not an issue.

@jmctwilio do you accept pull requests on this repo if I was to prepare this update?

**Comment by petermeester** [comment]
You can fix this issue by changing two functions in Resource.php.

public static function camelize($word) {
        return preg_replace_callback('/(^|_)([a-z])/',
	function ($matches) {
        	return ucfirst(strtolower($matches[2]));
        }, $word);
}

public static function decamelize($word) {
        return preg_replace_callback(
            '/(^|[a-z])([A-Z])/',
		function ($matches) {
            		return strtolower(strlen($matches[1]) ? $matches[1].$matches[2] : $matches[2]);
        	}, $word
        );
}

**Comment by efossier** [comment]
Hi all, apologies for not getting to this earlier, we've been slow during the holiday period. I'll schedule this for the team to take a look once we're all back in the office next week.

@mnwalker To answer your question this and the 5 other languages of helper libraries twilio offers are maintained by the api and developer education teams, while we do our best to stay on top of issues and bugs most of our time is spent keeping the libraries up to date with new features in the rest api, we always appreciate help in the form of PRs if you know how to fix the problem and want a quicker turn around time :)

**Comment by efossier** [comment]
I looked in to this and realized the examples above are using our legacy library (ie 4.x and lower). Unfortunately we don't have the bandwidth on the team to update the older versions and so 5.x is the only currently maintained version. 

I've checked and 5.x does not use `create_function` so it should be fully compatible with php 7.3. If you'd like to use twilio with php 7.3 in an officially supported manner then you'll have to update your library to the 5.x line, this will also keep you up to date with all the new resources, properties, and parameters we've added in the past year or so.

I understand it can be a large amount of work to port your existing code to use a new version with breaking changes, if its not worth it to you then I suggest using one of the workarounds mentioned above.

**Comment by evictor** [comment]
I created this branch with fixes on 4.12.1 for PHP 7.2: https://github.com/evictor/twilio-php/tree/4.12.1-create-function-fix

You can source this in your composer.json like this:

# 1. Add a repositories key to your composer.json

```
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/evictor/twilio-php"
    }
  ],
```

# 2. Specify dependency

```
"twilio/sdk": "dev-4.12.1-create-function-fix as 4.12.1",
```

Note "4.12.1-create-function-fix" is the branch name on my fork.

**Comment by hopeseekr** [comment]
Thanks to @evictor, I have also needed to port a client to PHP 7.2, so here is the same thing for v3.13.1 of the Twilio SDK:

# 1. Add the repo

```
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/hopeseekr/twilio-php"
    }
  ],
```

# 2. Specify dependency

```
"twilio/sdk": "dev-3.13.1-create-function-fix",
```

**Comment by whitleyblaine** [comment]
> 
> 
> You can fix this issue by changing two functions in Resource.php.
> 
> ```
> public static function camelize($word) {
>         return preg_replace_callback('/(^|_)([a-z])/',
> 	function ($matches) {
>         	return ucfirst(strtolower($matches[2]));
>         }, $word);
> }
> ```
> 
> ```
> public static function decamelize($word) {
>         return preg_replace_callback(
>             '/(^|[a-z])([A-Z])/',
> 		function ($matches) {
>             		return strtolower(strlen($matches[1]) ? $matches[1].$matches[2] : $matches[2]);
>         	}, $word
>         );
> }
> ```

why did you change camelize() to use strtolower()?

**Comment by whitleyblaine** [comment]
Also the comment is wrong in the source code, sms_messages becomes SmsMessages not SMSMessages

**Comment by sajeerbinsaleem** [comment]
> You can fix this issue by changing two functions in Resource.php.
> 
> ```
> public static function camelize($word) {
>         return preg_replace_callback('/(^|_)([a-z])/',
> 	function ($matches) {
>         	return ucfirst(strtolower($matches[2]));
>         }, $word);
> }
> ```
> 
> ```
> public static function decamelize($word) {
>         return preg_replace_callback(
>             '/(^|[a-z])([A-Z])/',
> 		function ($matches) {
>             		return strtolower(strlen($matches[1]) ? $matches[1].$matches[2] : $matches[2]);
>         	}, $word
>         );
> }
> ```

where is this resource.php file dude? i couldn't find one
