### ISSUE TITLE
Cant make a call from REST API when From set as a client identity

### ISSUE THREAD

**Issue by lanlin** [twilio/twilio-php#456]
**twilio-php version: 5.15.6**

### Code Snippet
```php
$option = ['url' => 'a valid url'];
$client->calls->create($to, 'client:564189227f361931080058ea', $option);
```

### Exception/Log
```
[HTTP 400] Unable to create record: From is not a valid phone number: client:564189227f361931080058ea

vendor/twilio/sdk/Twilio/Version.php(207): Twilio\Version->exception(Object(Twilio\Http\Response), 'Unable to creat...')
vendor/twilio/sdk/Twilio/Rest/Api/V2010/Account/CallList.php(83): Twilio\Version->create('POST', '/Accounts/AC72f...', Array, Array)
```

### Description
When i use a real phone number as From, it works fine.
I read your doc: https://www.twilio.com/docs/api/voice/making-calls
![image](https://user-images.githubusercontent.com/3468024/32762499-ab4e6816-c934-11e7-95ae-8f728357b5f8.png)

It says From can be client identifier. And i also know that client names must contain only alphanumeric and underscore characters.
As you see, client:564189227f361931080058ea only contain alphanumeric characters.

So, is there anything wrong?

**Comment by philnash** [comment]
In this case, is the `$to` that you are trying to call a phone number?

**Comment by lanlin** [comment]
@philnash yes, $to is a phone number.

**Comment by lanlin** [comment]
hello? Anyone knows?

**Comment by jmctwilio** [comment]
@lanlin Have you tried the same request directly using cURL?

**Comment by lanlin** [comment]
@jmctwilio useing cURL got 
```json
{"code": 21212, "message": "From is not a valid phone number: client:564189227f361931080058ea", "more_info": "https://www.twilio.com/docs/errors/21212", "status": 400}
```
When From is a valid phone number, To set to client:564189227f361931080058ea, it works.
But, why? The doc said From can be a client identifier.

**Comment by jmctwilio** [comment]
@lanlin Looks like this is an error with the API itself.  I'll create a ticket and assign it to the appropriate team.  Thank you for double-checking!  Unfortunately, I have no ability to estimate when the fix might be made.  I'll make a note to ping this issue when it's corrected.

**Comment by wittyreference** [comment]
You can only use a Client caller ID if the destination is also a Client user; any calls to the PSTN need to have an E.164 address that is either a Twilio number on your account or a verified caller ID.

**Comment by lanlin** [comment]
Thanks. I think the document should mention of this situation, or someone else maybe has same problem like me.

**Comment by philnash** [comment]
Hey, sorry, I find it hard to keep up with GitHub notifications. I should have been looking out for your response. The documentation should be clearer about this as @wittyreference says, when calling to PSTN you require a phone number to be the `From` parameter. I'll raise this with the docs team.

**Comment by jmctwilio** [comment]
Looks like this is going to be cleared up in the docs.  @lanlin Thank you for your patience and for highlighting the lack of clarity in the online docs!

**Comment by philnash** [comment]
I've updated the documentation here: https://www.twilio.com/docs/api/voice/making-calls#required-parameters. It now reads:

> If the To parameter is a phone number, From must also be a phone number.
