### ISSUE TITLE
Nice Examples

### ISSUE THREAD

**Issue by dataf3l** [twilio/twilio-php#460]
I guess it would be nice if the "make a call" example could have a bit more logic, so people could see the potential of the platform from the start, instead of them having to dig deeper into the docs.

The "make a call" example merely plays a sound, is that what this lib is about?

https://twimlets.com/holdmusic?Bucket=com.twilio.music.ambient

<Response>
<Play>
http://com.twilio.music.ambient.s3.amazonaws.com/gurdonark_-_Exurb.mp3
</Play>
<Play>
http://com.twilio.music.ambient.s3.amazonaws.com/aerosolspray_-_Living_Taciturn.mp3
</Play>
<Play>
http://com.twilio.music.ambient.s3.amazonaws.com/gurdonark_-_Plains.mp3
</Play>
<Redirect/>
</Response>

**Comment by jmctwilio** [comment]
@dataf3l Thanks for your feedback.  We're looking forward to continuing to improve the quality and scope of our documentation in 2018.  In addition to expanding the examples, we plan to include sections to describe common patterns employed by the Twilio API -- like the approach the API takes to pagination.
