### ISSUE TITLE
/examples folder

### ISSUE THREAD

**Issue by dataf3l** [twilio/twilio-php#461]
When I use a new repo or a new lib, it is hard for me to "come up with ways to do stuff", because I'm not that creative, but if the thing had a /examples folder (which I always search for), then perhaps my creativity could be ignited ! :)

**Comment by jmctwilio** [comment]
@dataf3l  This is also a great suggestion.  We are evaluating the possibility of creating a stronger link between our documentation and the helper libraries.  I think the improvements you find in 2018 will go a long way toward providing the inspiration you seek.

**Comment by gety9** [comment]
+ 1
