### ISSUE TITLE
Can't change voiceReceiveMode to Fax through incomingPhoneNumbers

### ISSUE THREAD

**Issue by sentiasa** [twilio/twilio-php#462]
I am trying to buy a Fax number and set its webhooks accordingly.
```
$number = $twilio->incomingPhoneNumbers
       ->create([
             "voiceReceiveMode" => 'fax', 

             // also tried "VoiceReceiveMode" => 'fax',

             "voiceUrl" => "http://example.com",
             "phoneNumber" => $request->number,
             "voiceMethod" => "POST"
      ]
);
```
With this code, I am able to purchase the number, set voice method to post also sets the voice url.

I have set the voiceUrl because in the Docs it says:

"At this point, the number's VoiceUrl will now behave as its FaxUrl". as mentioned here
However voiceReveiveMode doesn't change and always stays at "Voice"

Also, if I dd($number), in IncomingPhoneNumberInstance object, under properties, I don't see voiceReceiveMode
```
IncomingPhoneNumberInstance {#249 ▼
  #_assignedAddOns: null
  #version: V2010 {#244 ▶}
  #context: null
  #properties: array:30 [▼
    "accountSid" => "**"
    "addressSid" => null
    "addressRequirements" => "none"
    "apiVersion" => "2010-04-01"
    "beta" => false
    "capabilities" => array:4 [▶]
    "dateCreated" => DateTime {#250 ▶}
    "dateUpdated" => DateTime {#251 ▶}
    "friendlyName" => "(218) 963-5608"
    "identitySid" => null
    "phoneNumber" => "+12189635608"
    "origin" => "twilio"
    "sid" => "**"
    "smsApplicationSid" => ""
    "smsFallbackMethod" => "POST"
    "smsFallbackUrl" => ""
    "smsMethod" => "POST"
    "smsUrl" => ""
    "statusCallback" => ""
    "statusCallbackMethod" => "POST"
    "trunkSid" => null
    "uri" => "/2010-04-01/Accounts/ACcc7e0c85b66b0414485f08a1e03abdba/IncomingPhoneNumbers/PNe2bd51168e719b86cee6c9c46074e46c.json"
    "voiceApplicationSid" => null
    "voiceCallerIdLookup" => false
    "voiceFallbackMethod" => "POST"
    "voiceFallbackUrl" => null
    "voiceMethod" => "POST"
    "voiceUrl" => "http://example.com"
    "emergencyStatus" => "Inactive"
    "emergencyAddressSid" => null
  ]
```

Related here: https://stackoverflow.com/questions/47744893/changing-voicereceivemode-to-fax-is-not-working?noredirect=1#comment82489426_47744893

**Comment by jmctwilio** [comment]
@sentiasa  Your overview is wholly accurate.  As of right now, the `create` verb for phone numbers does not understand VoiceReceiveMode.  You should be able to mutate the number with the receiveMode, though.  We apologize for the confusion; fax is still a fledgling product whose integration is forthcoming.
