### ISSUE TITLE
newline character does not work when calling client->messages->create(...)

### ISSUE THREAD

**Issue by Syntaf** [twilio/twilio-php#471]
It seems when using `\n` inside the twilio message body, it's treated literally instead of creating a newline. Is there another way to accomplish a newline?

### Steps to Reproduce

When using the PHP library to send messages, the following line of code:

    $client->messages->create(
        '+11234567890',
        array(
            'from' => '+10987654321',
            'body' => 'Here is a message \n and a new line'
        )
    );

results in a message where the newline character is treated literally, meaning the user will receive:

`Here is a message \n and a new line`

EDIT: The same occurrence happens with `\r\n`. I noticed [here](https://support.twilio.com/hc/en-us/articles/223181468-How-do-I-Add-a-Line-Break-in-my-SMS-or-MMS-Message-) that I want my newline to encode into `%0a`, however the CURL client encodes `\n` differently which might be the issue.

**Comment by childish-sambino** [comment]
Try wraping the message in double-quotes: `"Here is a message \n and a new line"`

https://php.net/manual/en/language.types.string.php#language.types.string.syntax.double

**Comment by diazsasak** [comment]
Hi @childish-sambino i've try to wrap using double quote. still not work. any solution?

![image](https://user-images.githubusercontent.com/7880137/157361157-d4ffbf21-13dd-4a60-b797-b457780b9bb6.png)

**Comment by childish-sambino** [comment]
@diazsasak `$body` has already been defined. Where that string is built is where the double-quotes are needed. This is not specific to this library.

**Comment by diazsasak** [comment]
@childish-sambino Thank you. it works. i don't need to write \n manually. just need to press enter by keyboard to make a new line
