### ISSUE TITLE
Problems with "underscore" character in text with URL send sms to mobile 

### ISSUE THREAD

**Issue by jayram47inx** [twilio/twilio-php#473]
***Note: I send text sms with URL have undersore link but after send into mobile and i see that 
"_" replace with ' ' ' charatcter like below*
===========================================================================
Input
Social_App

Output
Social'App**
============================================================================
**Version:**twilio-php/3.12.4

### Code Snippet
# Code
        $sid             = Yii::$app->params['twillio_sid'];
        $token           = Yii::$app->params['twillio_token'];
        $snTwillioNumber = Yii::$app->params['twillio_number'];
        $client          = new \Services_Twilio($sid, $token);

        $message = $client->account->messages->sendMessage(
                $snTwillioNumber, // From a valid Twilio number
                $number, // Text this number
                $message
        );
        return $message;

After got sms into mobile
=====================
http://localhost/Social'App/frontend/web/site/reset-password?token=Wh6YEM7ZM2zSoGoQoTOKGD6ukiCjkzOw
### Steps to Reproduce
1.Send sms into mobile number

### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by childish-sambino** [comment]
I'm not seeing anything in the code that's doing this conversion and not able to recreate currently. Have you tried using a more recent release of this lib?

**Comment by akthe** [comment]
We are observing this issue now, can you let us know how it was fixed earlier.

**Comment by inebadeploy** [comment]
Any solution to this?

**Comment by childish-sambino** [comment]
@inebadeploy https://github.com/twilio/twilio-php/issues/589#issuecomment-560489930
