### ISSUE TITLE
Error 403 Method Not allowed.

### ISSUE THREAD

**Issue by jagroop** [twilio/twilio-php#474]
I am trying to fetch list of participants of a conference. But getting this error.

Version : latest

### Code Snippet
```php
$client = new Client($account_sid, $account_token);

$participants = $client
                        ->conferences($conf_id)
                        ->participants
                        ->read();
```

### Exception/Log
```
[HTTP 405] Unable to fetch page: Method not allowed
Twilio\Exceptions\RestException
```

**Comment by AlexAscherson** [comment]
Did you ever resolve this Jagroop? Getting same issue with the demo code for listing conf participants.

**Comment by childish-sambino** [comment]
@AlexAscherson The sample code looks good and works for me (just testing a basic conference with 1-2 participants).

I do, however, see this error when the conference SID is invalid. E.g.
```
$participants = $client
                        ->conferences("not-an-actual-sid")
                        ->participants
                        ->read();
```
Could you check to make sure it's a proper conference ID?

**Comment by AlexAscherson** [comment]
Hey Sambino,

Was just coming back to post that!  I was using the confernece id I had assigned when creating the conference, not the call(?) id that is required / assigned by twilio.

For others having the same issue, the twilio conf id starts with a C. eg: CAd699498e169274fd36d225aef6580fe5

Thanks for you help Sambino!
