### ISSUE TITLE
Incorrect DocBlocks for Voice TwiML

### ISSUE THREAD

**Issue by joshhornby** [twilio/twilio-php#475]
**Version:**
5.19.0

When working with the classes in the `Twilio\TwiML\Voice` namespace, the return types of the `set..` methods are incorrect. 

https://github.com/twilio/twilio-php/blob/master/Twilio/TwiML/Voice/Conference.php#L29

This should actually be:

```
    /**
     * Add Muted attribute.
     * 
     * @param boolean $muted Join the conference muted
     * @return Conference $this.
     */
```

This would also IDE's to not throw warnings when trying to chain multiple set functions together.

**Comment by childish-sambino** [comment]
Resolved
