### ISSUE TITLE
Twilio sip(ip-phone) and Mobile App not connecting the call in same time.

### ISSUE THREAD

**Issue by geeksachin** [twilio/twilio-php#485]
I am using twilio with sip domain. I want to connect incoming call on Ip-Phone(e.g: Zoiper) and Mobile App in same time.

Case: User A have loging in mobile app and connect succesfull with Ip-Phone(Zoiper) but incoming call not connecting on both device in the same time.

I have set incoming url on twilio number.

Use case1: If I am using below code then call connect on mobile. Code:
`echo "<Response>
        <Dial timeout='30' callerId='".$callerId."' record='record-from-answer'>
            <Client>".$user_name."</Client>
        </Dial>
    </Response>";`

Use Case2 :If am using below code then call connect on Ip-Phone(e.g: Zoiper). Code:

`echo "<Response>
         <Dial timeout='30' callerId='".$callerId."' record='record-from-answer'>
             <Sip>".$username."@mydomain.sip.us1.twilio.com</Sip>
         </Dial>
   </Response>";`

Result want to: when any user(Twilio user or skype user) will be call on my twilio number then incoming call should come on Mobile App and Ip-Phone in the same time.

How I can connect call on both device(Mobile App & Ip-Phone) in same time?

If anyone have possible solution for this then please suggestion me.

Thanks
Sachin

**Comment by childish-sambino** [comment]
Have you tried listing both clients with the `Dial` verb? e.g.,
```
<Response>
  <Dial timeout='30' callerId='callerId' record='record-from-answer'>
    <Client>user_name</Client>
    <Sip>user_name@mydomain.sip.us1.twilio.com</Sip>
  </Dial>
</Response>
```
