### ISSUE TITLE
Compositions for 1 room (1 Video and 1 Audio)

### ISSUE THREAD

**Issue by alielkhateeb** [twilio/twilio-php#486]
Hi, just a very quick question, I want to fetch a recording that will always have 1 video resource and 1 audio resource, I noticed the compositions and I used it but I see it can create many complex video and audio compositions, I don't actually need this as I am only fetching 1 room recording, is there any other way?

For now I have this code:

    $composition = $client->video->compositions->create([
        'roomSid' => $room_sid,
        'audioSources' => "*",
        'videoLayout' => array(
            'transcode' => array(
                'video_sources' => array("*")
            )
        ),
        'format' => 'mp4'
    ]);

But again the video_sources is just 1 and also the audio is just 1, so I was wondering if there is a better way since this will charge me every time I fetch a room recording 0.01 per minute and I'm not combining any videos or any audios.

Thanks a lot.

Regards,
Ali

**Comment by saad3074** [comment]
Hi @alielkhateeb did you find any solution for this.

**Comment by alielkhateeb** [comment]
Hi @saad3074

I retrieved the Audio and Video files separately and combined them myself on the server.

**Comment by saad3074** [comment]
@alielkhateeb  thanks. i already done this but it take time for creating composition.

**Comment by childish-sambino** [comment]
I'm not understanding the issue with your current code. It will create a composition containing all audio and video recordings for a single room. If the room has only 1 video and 1 audio recording, it will combine those into a single composition. Could you expand on the issue?

**Comment by alielkhateeb** [comment]
@childish-sambino Hi, this was a long time ago, but I'll explain my point.

Compositions are obviously used for combining multiple videos/audios into a single file, which is chargeable, my case was that the room will always have 1 single participant which means there are not more than 1 video and 1 audio file, these 2 files are provided for free, and through the API you can retrieve the audio/video files separately, but I don't see the point of using compositions to combine a single audio and a single video, that's my point. I hope it's clear.

Let me know if you have any questions.

Thank you.

**Comment by childish-sambino** [comment]
Ah, well I see 2 reasons why there is a charge to do this. First, they are 2 separate files and you're wanting to combine them. Second, the files are not player-friendly without transcoding:

> Recording files are generated with a format optimized for reliability and compactness. This format is not player friendly. Hence, many media players may not render Recordings media files appropriately. For generating player-friendly media files, compose your Recordings using Twilio's Recordings Composition API.

Recommend reaching out to [support](https://twilio.com/help/contact) if this does not suffice.

**Comment by pinkishahub-sdn** [comment]
video composition take very much time to composite.
