### ISSUE TITLE
Getting error: Unable to create record: The From phone number +XXXXXX is not a valid

### ISSUE THREAD

**Issue by SailendraShakya** [twilio/twilio-php#488]
After using twilio in my application, I am getting following error. I trying to run code in my localhost. From number I have taken from twilio which is valid.

[HTTP 400] Unable to create record: The From phone number +XXXX is not a valid, SMS-capable inbound phone number or short code for your account

**Comment by atbaker** [comment]
Hi @SailendraShakya 

Not sure what's going on here, but you'll be better served opening a support ticket with us instead. I recommend emailing `help@twilio.com` or opening a support ticket here: https://support.twilio.com/hc/en-us/requests/new

**Comment by rajesh-smartwebtech** [comment]
Hi @SailendraShakya do you find any solution regarding this i am also getting same issue ?

**Comment by philnash** [comment]
Hey @rajesh-smartwebtech, if the error says that the From number is not valid to send SMS messages, then it is either:

* Not a Twilio number in your account. SMS messages must be sent from [Twilio phone numbers that have been bought and are available in your account](https://www.twilio.com/console/phone-numbers/incoming)
* Not an SMS capable phone number. Not all Twilio numbers can send SMS messages, check the capability of the number you are trying to use

If neither of those is the problem, then please [contact Twilio support](https://www.twilio.com/help/contact) and provide them your account SID and the number you are trying to use to send the SMS message.

**Comment by chinmaya-gupta22** [comment]
I'm receiving above error any update on this?

**Comment by childish-sambino** [comment]
@chinmaya-gupta22 Please open a new issue.
