### ISSUE TITLE
On Localhost, JWT is generated with proper iss value, on the server it has false value.

### ISSUE THREAD

**Issue by alielkhateeb** [twilio/twilio-php#502]
Hi, I have a problem with the generated JWT, I generate it using this code.

sdk version: `5.21.4`

```php
$identity = "Jennie";

$token = new AccessToken(
        $this->account_sid,
        $this->voice_api_sid,
        $this->voice_api_secret,
        5,
        $identity
);

// Create Voice grant
$voiceGrant = new VoiceGrant();
$voiceGrant->setOutgoingApplicationSid($this->application_sid);

// Add grant to token
$token->addGrant($voiceGrant);

return $token->toJWT();
```

### Exception/Log
This is my console errors I get when I try to run Device.setup with the generated token.
```
POST https://eventgw.twilio.com/v4/EndpointEvents 403 (Forbidden)
Uncaught (in promise) Error: {"code":20154,"message":"Invalid Token claims set"}
    at XMLHttpRequest.onreadystatechange (twilio.min.js:55)
```

Note: When I try to decode the JWT with [JWT Decoder](https://jwt.io/) I find that `iss` value is `false` although the JWT generated on my localhost has `iss` value of my API Key.
So it's working on my localhost but not working on the server.

What am I missing?

**Comment by imthepitts** [comment]
@alielkhateeb,

Sorry you're having trouble. Please check the runtime values of the arguments you're passing into the `AccessToken` constructor. 

If you need further assistance, please contact our Support Team so you can share additional details privately.

https://www.twilio.com/help/contact 

All the Best,

Zack
