### ISSUE TITLE
Implementing Group Calling

### ISSUE THREAD

**Issue by verma-prince** [twilio/twilio-php#504]
Hello,

I want to implement group calling feature in my application. Is there any way to achieve this. As i want as if two person are connecting using voice call then i want to add third person to join them means all these three persons must listen and speak with each other.

Please give me solution if you guys have !

Thanks 
Prince

**Comment by verma-prince** [comment]
Any update guys  ???

**Comment by wsyms** [comment]
All you need to do is create a conference call, here is a tutorial: https://www.twilio.com/docs/voice/tutorials/how-to-create-conference-calls-php
