### ISSUE TITLE
[HTTP 400] Unable to fetch page: Paged requests must include a PageToken

### ISSUE THREAD

**Issue by roblesterjr04** [twilio/twilio-php#507]
Overnight this error has now occurred on one of my apps. I've already attempted to update to the latest version of the sdk and that hasn't worked.

**Version:**

### Code Snippet
```php
$accounts = $twilio->api->v2010->accounts
                               ->read();
```

### Exception/Log
```
[HTTP 400] Unable to fetch page: Paged requests must include a PageToken
```

### Steps to Reproduce
1. Retrieve complete list of subaccounts - in our case over 50

**Comment by roblesterjr04** [comment]
I need to express urgency here as its brought down a critical application that we are turning on for customers.

**Comment by roblesterjr04** [comment]
I found a work around by setting a limit. `->read([], 1000)` 

Something clearly changed with the API overnight as this was not necessary yesterday or for at least the last 3 months.

**Comment by james-srl** [comment]
I just had the same issue come up. @roblesterjr04's workaround did the trick, but it seems like a bug.

**Comment by drekinov** [comment]
that appeared over the night for recordings / error alerts resources. already opened support ticket to twilio about that.

**Comment by childish-sambino** [comment]
This is not a change that can be made in the library. An internal ticket has been filed against the relevant product team.

**Comment by childish-sambino** [comment]
This has now been resolved.
