### ISSUE TITLE
Make api URL configurable

### ISSUE THREAD

**Issue by TBlindaruk** [twilio/twilio-php#508]
### Feature Request

Hi,

I have written some functionality which contains communication with twillo via php-sdk.
When I have started API  tests writing, then I got a problem, that I could not mock HTTP requests which were called within this SDK, since all URL is hardcoded, and cannot be configurable. 

So, I have a proposition to give people the possibility to change the URL

**Comment by dinamic** [comment]
Not sure what you are trying to do there, but why don't you just pass-in a custom http client?

IMO you should not be changing the URL at all. What you need to do is to mock the twilio client and make assertions on the different methods that get called, the parameters they are called with, etc.
