### ISSUE TITLE
Error - 12100 Document parse failure Twiml XML syntax error

### ISSUE THREAD

**Issue by KillWil** [twilio/twilio-php#509]
version **>=5.5**

### Code Snippet
Calling function __toString in  sdk/Twilio/Twiml.php

```php
    public function __toString() {
        $xml = $this->element->asXML();
        return (string)str_replace(
            '<?xml version="1.0"?>',
            '<?xml version="1.0" encoding="UTF-8"?>', $xml);
    }
```

results in an syntax error in the debugger 
Error on line 2 of document : The processing instruction target matching \"[xX][mM][lL]\" is not allowed. 

when calling like this

```php
  ...
    $twiml = new Twilio\Twiml();
    $twiml->say($sayMessage, array('voice' => 'alice', 'language' => 'fr-FR'));
    $twiml->dial($salesPhone);
  ...
```

Changing the function to 

```php
    public function __toString() {
        $xml = $this->element->asXML();
        return (string)str_replace(
            '<?xml version="1.0"?>',
            '', $xml);
    }   
```

is working...

**Comment by adsherpa** [comment]
I am having same issue on php 7.0, and twilio sdk 5.3.0, and with that change @KillWil mentioned fixed my issue as well.
Thank you for the hit there.
I think this should be either fixed or refactored in main branch.

**Comment by childish-sambino** [comment]
Not seeing this issue currently, but this module was deprecated as part of the [5.21.1](https://github.com/twilio/twilio-php/releases/tag/5.21.1) release. Is this still happening in later releases?
