### ISSUE TITLE
Twiml.php file name issue

### ISSUE THREAD

**Issue by Gifky** [twilio/twilio-php#513]
**Version:**
5.24

### Exception/Log
```
PHP Fatal error:  Uncaught Error: Class 'Twilio\TwiML' not found
```

The Twiml.php file needs to be renamed to TwiML.php to fix that issue. I'm surprised no one has pointed out such issue since it's impossible to require Twilio via composer without manually upload it and rename that file unless you are running on windows where file names are case insensitive, am I missing something?

**Comment by KasperFranz** [comment]
There is a [Twilio\Twiml file](https://github.com/twilio/twilio-php/blob/master/Twilio/Twiml.php) and then there is a [Twilio\TwiML\TwiML file](https://github.com/twilio/twilio-php/blob/master/Twilio/TwiML/TwiML.php)

What documentation are you using there it is specified as TwiML? i have been running this on linux servers without any issue.

**Comment by Gifky** [comment]
@KasperFranz thanks for the clarification, just solved that issue by using:

```
use Twilio\Twiml;
$response = new Twiml();
```
Instead of:
```
use Twilio\TwiML;
$response = new TwiML();
```
Although the TwiML code is from the docs https://www.twilio.com/docs/libraries/php/usage-guide?code-sample=code-simple-voice-response-saying-chapeau-in-french&code-language=PHP&code-sdk-version=5.x

**Comment by KasperFranz** [comment]
Yeah that documentation contains both versions of the code as you can see the correct one is the Twiml one.

I am sure someone from Twilio can help with getting the documentation updated :smiley:

**Comment by imthepitts** [comment]
Hello everyone,

Sorry for the confusion. The `Twiml` class is deprecated:

https://github.com/twilio/twilio-php/blob/master/Twilio/Twiml.php#L7-L11 

The correct TwiML code is to use the namespace `Twilio\TwiML` with a `VoiceResponse` or `MessagingResponse` class. We've updated the docs to remove the erroneous reference to `Twiml`.

All the Best,

Zack

**Comment by cfinke** [comment]
I believe the docs still include an erroneous reference to TwiML. In the "Reply to a message using PHP" step of https://www.twilio.com/docs/sms/quickstart/php-manual-install, the docs specify:

```
use Twilio\TwiML;
[...]
$response = new TwiML();
```

when I believe it should be

```
use Twilio\TwiML\MessagingResponse;
[...]
$response = new MessagingResponse();
```

Without that change, it generates an error about not being able to load `Twilio/TwiML.php`.

**Comment by childish-sambino** [comment]
@cfinke You're right? Can you submit a PR here? https://github.com/TwilioDevEd/api-snippets/blob/master/quickstart/php/sms/reply_sms_without_composer/reply_sms.5.x.php

**Comment by mugisham** [comment]
This issue hasn't been resolved still and docs are still misleading

**Comment by KasperFranz** [comment]
@childish-sambino  @imthepitts any change the above PR (812 in the api-snippets) can get merge to resolve this?

**Comment by childish-sambino** [comment]
Bumping internally since I don't have write access to the snippets repo.

**Comment by vastdevops** [comment]
BUMP! Still not fixed and wasted so much of my time.

**Comment by childish-sambino** [comment]
@vastdevops It was updated here a couple days ago: https://www.twilio.com/docs/sms/quickstart/php-manual-install?code-sample=code-reply-to-a-sms-using-php-1&code-language=PHP&code-sdk-version=5.x

Is there another place you're seeing where it's incorrect still?

**Comment by vastdevops** [comment]
https://www.twilio.com/docs/voice/tutorials/how-to-create-conference-calls-php
https://www.twilio.com/docs/voice/tutorials/how-to-gather-user-input-via-keypad-php

**Comment by childish-sambino** [comment]
@vastdevops Ah, good catch.

Anyone that wants to fix this, please submit a PR to update these files:
* https://github.com/TwilioDevEd/api-snippets/blob/master/guides/voice/conference-calls-guide/moderated-conference/moderated-conference.php
* https://github.com/TwilioDevEd/api-snippets/blob/master/guides/voice/gather-dtmf-tones-guide/gather-example-step-0/example.5.x.php
* https://github.com/TwilioDevEd/api-snippets/blob/master/guides/voice/gather-dtmf-tones-guide/gather-example-step-1/example.5.x.php
* https://github.com/TwilioDevEd/api-snippets/blob/master/guides/voice/gather-dtmf-tones-guide/gather-example-step-2.1/example.5.x.php
* https://github.com/TwilioDevEd/api-snippets/blob/master/guides/voice/gather-dtmf-tones-guide/gather-example-step-2/example.5.x.php

I'll bump the PR(s) internally afterwards.

**Comment by vastdevops** [comment]
https://github.com/TwilioDevEd/api-snippets/search?p=3&q=%22new+TwiML%22&unscoped_q=%22new+TwiML%22

Dont all of those need to be updated?

**Comment by childish-sambino** [comment]
Yup, or rather these: https://github.com/TwilioDevEd/api-snippets/search?l=PHP&q=%22new+TwiML%22

**Comment by Gaket** [comment]
Similar issue in Java examples:
https://www.twilio.com/docs/voice/twiml

**Comment by childish-sambino** [comment]
@Gaket Not sure I understand your comment. The class `com.twilio.type.Twiml` was added recently and should not be related to this PHP issue. If you're still having an issue, please create a new issue under the [twilio-java](https://github.com/twilio/twilio-java) repo.

**Comment by childish-sambino** [comment]
Fixed by https://github.com/TwilioDevEd/api-snippets/pull/819

**Comment by javier123454321** [comment]
Hey all, I found a reference to the Twiml class in this doc still, on the 'Create a simple PHP application' section:
https://www.twilio.com/docs/usage/tutorials/how-to-set-up-your-php-development-environment
