### ISSUE TITLE
Missing dollar sign in property annotation

### ISSUE THREAD

**Issue by jiri-fajman** [twilio/twilio-php#517]
Hello, 

I have noticed that the `@property` annotation is not used correctly and it causes issues with static code analysis tools like phpstan.

For example in class `Twilio\Rest\Client` there is annotation `@property \Twilio\Rest\Api api`, however there is missing dollar sign. Correct format is `@property \Twilio\Rest\Api $api`. This issue can be found in almost every twilio classes.

Link to `@property` specification:
http://docs.phpdoc.org/references/phpdoc/tags/property.html

Link to the caused issue:
https://github.com/phpstan/phpdoc-parser/issues/15

Could you please fix this?
Thank you.

**Comment by luxemate** [comment]
@cjcodes @ekarson Not sure who's a maintainer of this repo. Consider the issue please, it probably isn't hard to fix.

**Comment by kubk** [comment]
PR: https://github.com/twilio/twilio-php/pull/512

**Comment by LasVegasCoder** [comment]
@jiri-fajman , good catch. I hope this is fixed ASAP. 
PR #512
