### ISSUE TITLE
CurlClient: $buffer not defined in that scope

### ISSUE THREAD

**Issue by pascal-hofmann** [twilio/twilio-php#518]
https://github.com/twilio/twilio-php/blob/165cecbe4f7ac910f016a3e42e5d324765913486/Twilio/Http/CurlClient.php#L75
The variable `$buffer` is not defined in this scope. To me this looks like a refactoring gone wrong. It is used but never freed in `public function options(…)`.

https://github.com/twilio/twilio-php/blob/165cecbe4f7ac910f016a3e42e5d324765913486/Twilio/Http/CurlClient.php#L144

**Comment by childish-sambino** [comment]
Yup, definitely a refactoring issue. I'm open to a PR if anyone wants to resolve it.
