### ISSUE TITLE
New TwiML Response Body Is Too Large

### ISSUE THREAD

**Issue by textmary420** [twilio/twilio-php#519]
Laravel 5.7

### Code Snippet
```php
$twiml = new \Twilio\Twiml\VoiceResponse();
    $twiml->reject();
    return response($twiml)->header('Content-Type', 'text/xml');
```

### Exception/Log
```
TwiML Response is too large
```

### Steps to Reproduce
1. Webhook for twilio voice
2. Phone call returns with "Application Error"
3. Error is thrown in debug console "TwiML Response is too large"

This code was working fine up until a few days ago. Nothing has changed on my end. I've reverted back to the old deprecated code and it works fine. 

This old deprecated code does NOT result in an error
```
$twiml = new \Twilio\Twiml();
    $twiml->reject();
    return response($twiml)->header('Content-Type', 'text/xml');
```

I've viewed the response for both code in Postman and the output is the exact same. Not sure why this is throwing an exception in Twilio.

**Comment by imthepitts** [comment]
Sorry you're having trouble, @textmary420. That error is not a result of the helper library, so please contact our Support team to investigate and include a Call SID that had the issue.

Contact Support here:
https://www.twilio.com/help/contact

All the Best,
Zack
