### ISSUE TITLE
Is there anyway to get permitted GEO locations on SMS and Voice from API/SDK 

### ISSUE THREAD

**Issue by ihatecodinglikeking** [twilio/twilio-php#534]
We am using both SMS and Voice call features, both are working fine but now we are in a situation to support multi countries. 
We know that https://www.twilio.com/console/voice/calls/geo-permissions/low-risk go to this url and allow what counties should have access but is there any way that I can pull permitted counties list from API to list in UI ? 

I am not worried about giving permission from API but I want at least fetch the permitted/allowed by my account/company countries list for both SMS and Voice so that I can make a dropdown in my View.
Which means I should never hit `13227 & 21215 & 32205` these codes

**Comment by childish-sambino** [comment]
The API docs here should be able to help: https://www.twilio.com/docs/voice/api/dialingpermissions-country-resource
