### ISSUE TITLE
Get 

### ISSUE THREAD

**Issue by stevehomer** [twilio/twilio-php#535]
On https://github.com/twilio/twilio-php/tree/4.11.0

the "read our full docs" at URL below is 404

http://readthedocs.org/docs/twilio-php/en/latest/

**Comment by childish-sambino** [comment]
_readthedocs_ is no longer integrated with this library. Docs for versions _5.x_ can be found here: https://www.twilio.com/docs/libraries/reference/twilio-php/index.html
