### ISSUE TITLE
Error - 52004 Credential SID not specified

### ISSUE THREAD

**Issue by generosocarbone** [twilio/twilio-php#537]
`
require_once('../vendor/autoload.php'); // Loads the library
use Twilio\Jwt\AccessToken;
use Twilio\Jwt\Grants\ChatGrant;

$accountSid = 'AC********************';
$apiKeySid = 'SK********************************';
$apiKeySecret = '************************';

$serviceSid = 'IS***************************';
$pushCredentialSid = 'CR*****************************';

$identity = $_REQUEST['identity'];

$token = new AccessToken(
    $accountSid,
    $apiKeySid,
    $apiKeySecret,
    3600,
    $identity
);

$grant = new ChatGrant();
$grant->setServiceSid($serviceSid);
$grant->setPushCredentialSid($pushCredentialSid);
$token->addGrant($grant);

echo $token->toJWT();
`

As you can see from the title I get this error on the Twilio Chat Debugger. Am I missing something in the configuration or in the code?

**Comment by ivailozn** [comment]
I was having exacly the same issue.
Try updating to 5.32.0. That version solved my issue!

**Comment by childish-sambino** [comment]
Not seeing anything obvious in your example. Does updating to the latest version resolve the issue?
