### ISSUE TITLE
Programmable Fax regarding : Twilio

### ISSUE THREAD

**Issue by RajseeShah** [twilio/twilio-php#538]
When I am trying to send fax from twilio, if To number is not capable of receiving fax, then it is shown that mobile having that number gets call from that twilio number from which fax is sent. 

So can you please tell me that if other number is not able to receive the fax, then we can stop that useless call?

**Comment by childish-sambino** [comment]
Not an expert on fax, but I don't think there's a way to know this for certain. For instance, the physical machine could just be down, but that doesn't mean the number is not fax-capable. Do status callbacks help with your case?
