### ISSUE TITLE
Twig Support: add __isset

### ISSUE THREAD

**Issue by belackriv** [twilio/twilio-php#543]
In order by Twig to correctly use dynamic object properties, the magic method __isset must be defined  on the class. ( https://twig.symfony.com/doc/2.x/recipes.html#using-dynamic-object-properties )

Example:
Given a \Twilio\Rest\Api\V2010\Account\AvailablePhoneNumberCountry\LocalInstance to a Twig template
```
{{localInstance.friendlyName}}
```
This will not work unless the following is added to LocalInstance
```
 public function __isset($name)  {
        return array_key_exists($name, $this->properties);
}
```

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.
