### ISSUE TITLE
Getting Warning: Division by zero on conference fetching

### ISSUE THREAD

**Issue by hmtuhindev** [twilio/twilio-php#556]
When I want to fetch conferences list using rest API I am getting this Division by zero. I have created the conference and then run this API Request. Please help me to resolve the issue. Thanks.

**Version:**
^5.34

### Code Snippet
```php
$twilio = new Client($sid, $token);

$conferences = $twilio->conferences
                      ->read(array("friendlyName" => "testConference"), 20);

foreach ($conferences as $record) {
    print($record->sid);
}
```

### Exception/Log
```
Warning: Division by zero in F:\Test Project\client-php\vendor\twilio\sdk\Twilio\Version.php on line 161

```

**Comment by childish-sambino** [comment]
What version of PHP are you running?
