### ISSUE TITLE
Notice of BREAKING CHANGE for PHP version 5.X, 7.0, and 7.1 users on January 1, 2020

### ISSUE THREAD

**Issue by thinkingserious** [twilio/twilio-php#582]
PHP version 5 is at end of life and on December 1, 2019, only PHP versions 7.2+ will be officially supported by the PHP community. 

**On January 1, 2020, Twilio will no longer support PHP version 5 via this helper library.**

**Comment by ejmudrak** [comment]
I have twilio-php v4.2.1 running in a legacy PHP 5.5 application, but the source code is all cloned locally in our app's directory. Will twilio-php break, or just no longer be supported, especially since I have a static version of it? 

Thanks

**Comment by childish-sambino** [comment]
@ejmudrak Existing releases won't break, but they will no longer be supported/maintained.

**Comment by childish-sambino** [comment]
Update: we'll soon be rolling a new major version of this repo that drops support for all EOL PHP versions which is PHP < v7.2

This will not affect existing 5.X releases of this repo.
