### ISSUE TITLE
CurlCilent with proxy fails

### ISSUE THREAD

**Issue by SyunsukeNomura** [twilio/twilio-php#585]
If the proxy resource is passed to CurlClient and the message resource is acquired, the HTTP status code returns 200, but a null page is returned.
Could you modify it so that the message resource can be obtained?
If I don't set up a proxy, I can get a page containing the message resource.

**Version:**
5.39

```php

       $client = new Client(
            $this->config->item('account_sid'),
            $this->config->item('auth_token'),
            null,
            null,
            new CurlClient([ CURLOPT_PROXY => <PROXY URL>])
        );

        $page = null;
        /* @var \Twilio\Rest\Api\V2010\Account\MessageList $resource */
        $resource = $client->account->messages;

        $options = [];
        $messageCntInPage = 100;

        try {
            $page = $resource->page($options, $messageCntInPage);
```

### Exception/Log
```
ERROR - 2019-11-22 14:16:23 --> Page Records can not be deserialized
```

### Steps to Reproduce
1. Specify proxy settings in CurlClient as an option
2. Execute page method of MessageList

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by SyunsukeNomura** [comment]
The following PR has been merged, so it is a solution idea. 
Thank you for your reply.

@see #586
