### ISSUE TITLE
Underscore issue is resurfaced 

### ISSUE THREAD

**Issue by akthe** [twilio/twilio-php#589]
Hi , 
We are observing the same issue now. Kindly let us know how was it resolved.

Problems with "underscore" character in text with URL send sms to mobile #473
**Note: I send text sms with URL have undersore link but after send into mobile and i see that
"_" replace with ' ' ' charatcter 

*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:**

### Code Snippet
```php
# paste code here
```

### Exception/Log
```
<place exception/log here>
```

### Steps to Reproduce
1.
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by childish-sambino** [comment]
I think issues like these are not related to the helper library and are based on carrier settings. Best to [file a support ticket](https://twilio.com/help/contact) and include a few example message SIDs to help them debug the issue.
