### ISSUE TITLE
GuzzleClient loses filters when paginating

### ISSUE THREAD

**Issue by matt-allan** [twilio/twilio-php#592]
**Version:**  5.41.0

### Code Snippet
```php
<?php

require __DIR__.'/vendor/autoload.php';

$client = new Twilio\Rest\Client(
    env('TWILIO_ACCOUNT_SID'),
    env('TWILIO_AUTH_TOKEN'),
    null,
    null,
    new \Twilio\Http\GuzzleClient(new GuzzleHttp\Client())
);

const TEL = '+1xxxxxxxxxx';

$messages = $client->messages->stream([
    'To' => TEL,
]);

foreach ($messages as $message) {
    if ($message->to !== TEL) {
        die(var_dump($message));
    }
}
```

```bash
TWILIO_ACCOUNT_SID=xxxx TWILIO_AUTH_TOKEN=xxxx php ./test_twilio.php
```

### Exception/Log

N/A

### Steps to Reproduce
1. Add an example telephone number to the test script that will return > 50 results
2. run the test script
Expected result: Only matching records are returned
Actual result: After the first page the stream returns **all** messages, not just messages matching the filter.

Looking at the `$url` and `$params` parameters passed to GuzzleClient::request it appears that the first call includes the filter parameters in `$params` while the second call has the filters in the `$url` already and an empty `$params` array. 

```
# first request
"https://api.twilio.com/2010-04-01/Accounts/xxx/Messages.json"
array:1 [
  "To" => "+1xxxxxxxxxx"
]
# second request
"https://api.twilio.com/2010-04-01/Accounts/xxx/Messages.json?To=%2B1xxxxxxxxxx&PageSize=50&Page=1&PageToken=xxxxxxxxxx"
[]
```

**Comment by childish-sambino** [comment]
Yup, looks like a bug. Will work on a fix.
