### ISSUE TITLE
Twilio won't let me connect using AccountSid

### ISSUE THREAD

**Issue by ahsanmster** [twilio/twilio-php#593]
As per the document [here](https://www.twilio.com/docs/iam/connect/quickstart/php) it says when user authenticate using connect button we should pass **Account SID** retrieved during the authorization process as **SID**  and main (using which we've created connect app) account's **Auth Token**  as token to the client, but when i do so it says json not found.

**My Code:**

### Code Snippet
```php
        $sid = 'AC09f****'; // this is the Account SID which we recieve while redirect from twilio
        $token = '964f****'; // main account's auth token
        $twilio = new Client($sid, $token);
        $account = $twilio->getAccount($sid)->fetch();
        $balanceUrl = 'https://api.twilio.com' . $account->subresourceUris['balance'];
        $balanceResponse = $twilio->request('GET', $balanceUrl);
        $responseContent = $balanceResponse->getContent();
        return $responseContent;
```

### Exception/Log
```
array:4 [▼
  "code" => 20404
  "message" => "The requested resource /2010-04-01/Accounts/AC09f9be592ffc9fe12e1c8793034f73ee/Balance.json was not found"
  "more_info" => "https://www.twilio.com/docs/errors/20404"
  "status" => 404
]
```

![image](https://user-images.githubusercontent.com/32548815/71643243-e719b080-2cd8-11ea-843e-e879151cdd9c.png)

### Steps to Reproduce
1. click on connect button by twilio
![image](https://user-images.githubusercontent.com/32548815/71643261-221be400-2cd9-11ea-8534-49c0bfad4f8f.png)
2. Allow from twilio page
3. Save the **Account SID** in URL
4. Pass **Account SID** as twilio sid and **Auth Token** as twilio_token to client

**Note:** i am using Laravel so using twilio SDK in it 

### Version
"twilio/sdk": "^5.38"

**Comment by childish-sambino** [comment]
I'm seeing the same thing. Checking internally to see if this is the expected behavior.

**Comment by childish-sambino** [comment]
Heard back from the team and this is the expected behavior. Connect app should not have access to check the balance of the customer's account.

**Comment by childish-sambino** [comment]
Further clarification, the way Connect Apps work in the backend is that a subaccount is created for the account when they authorize a Connect App. So the authorized account SID is for a subaccount, and subaccounts don't carry balance; they run out of the master account. You'll see a similar response when trying to access the balance for any subaccount.
