### ISSUE TITLE
can't send SMS message content inlucde Chinese, dose it only support english?

### ISSUE THREAD

**Issue by xuelabi123** [twilio/twilio-php#600]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```php
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-php version:
* php version:

**Comment by KasperFranz** [comment]
@xuelabi123  I think you if filled in the description of the issue you will get more help :)
