### ISSUE TITLE
Twiml class was removed

### ISSUE THREAD

**Issue by s-dev-s** [twilio/twilio-php#601]
Any ideas about how we can get a notice about remove some classes like Twiml in the future? This was a problem for us because we were using this class in our project and you broke reverse compatible without changing a major version. My project's all composer's packages update not so often and I haven't even seen class deprecated mark. I've seen just a fact the class was removed!
Even you marked the Twiml class as deprecated do you think this is a good idea to remove it without changing the major version of the application?

Can you please make some changes to this description because[ the sample of this](https://www.twilio.com/docs/voice/quickstart/php-manual-install?code-sample=code-answer-a-call-with-php-1&code-language=PHP&code-sdk-version=5.x) isn't working correctly in the current 5.X version! Thanks!

**Comment by childish-sambino** [comment]
`twilio-php` uses a modified version of [Semantic Versioning](https://semver.org) for all changes. [See this document](https://github.com/twilio/twilio-php/blob/master/VERSIONS.md) for details.

Tracking the samples getting updated here: https://github.com/twilio/twilio-php/issues/513

**Comment by s-dev-s** [comment]
@childish-sambino on the top of the document which one you sent (from the summary)

> 2. MINOR version when you add functionality in a backwards compatible manner, and

Do you think this was a backward-compatible change (removing Twiml class)?

**Comment by childish-sambino** [comment]
semver.org is for standard Semantic Versioning. This repo uses a modified version of it which is documented in the second link. Dropping the deprecated Twiml class was not a backwards-compatible change. Breaking changes that cause a minor version roll are documented in the release notes (e.g., [5.42.0](https://github.com/twilio/twilio-php/releases/tag/5.42.0)).
