### ISSUE TITLE
The provided XML does not conform to the Twilio Markup XML schema

### ISSUE THREAD

**Issue by kcifuentes** [twilio/twilio-php#608]
Hello, when using the class 'Twilio \ TwiML \ MessagingResponse' in the way shown in the documentation https://www.twilio.com/docs/sms/twiml

use Twilio \ TwiML \ MessagingResponse;

```php
$ response = new MessagingResponse ();
$ response-> message ('This is message 1 of 2.');
$ response-> message ('This is message 2 of 2.');
```

echo $ response;

Print the xml as follows:

```xml
<? xml version = "1.0" encoding = "UTF-8"?>
<Message> [My message] </Message>
```

Reading a bit in the documentation and reviewing the sdk code a little, I found that the expected format is as follows:

```xml
<? xml version = "1.0" encoding = "UTF-8"?>
<Response>
    <Message> This is message 1 of 2. </Message>
    <Message> This is message 2 of 2. </Message>
</Response>
```

and as you can see in the printout of my response there is no key <Response>

The code that builds this answer is in the TwiML.php file and is as follows:

```php
private function xml () {
    $ document = new DOMDocument ('1.0', 'UTF-8');
    $ document-> appendChild ($ this-> buildElement ($ this, $ document));
    return $ document;
    }
```

I am using the following version: "twilio / sdk": "^ 5.42"

**Comment by childish-sambino** [comment]
Just tried this out and I'm seeing the expected output. What do you mean "there is no key"? Are you printing the message or the response?

Code:
```
use Twilio\TwiML\MessagingResponse;
$response = new MessagingResponse();
$response->message('This is message 1 of 2.');
$response->message('This is message 2 of 2.');
echo $response;
```

Output:
```
<?xml version="1.0" encoding="UTF-8"?>
<Response><Message>This is message 1 of 2.</Message><Message>This is message 2 of 2.</Message></Response>
```

**Comment by kcifuentes** [comment]
Thanks for the answer @childish-sambino 

at the moment i try to print the response this is what it shows

```xml
<? xml version = "1.0" encoding = "UTF-8"?>
<Message> [My message] </Message>
```
and as you can see it is not adding <Response> parent as it appears on your output.

**Comment by childish-sambino** [comment]
When running the exact sample code I posted do you not see the enclosing `Response` block? Also, what version of PHP are you running?

**Comment by kcifuentes** [comment]
@childish-sambino  thanks, is exactly as you mentioned on your question,  i don't see `Response` block and my PHP version is the 7.3.8

**Comment by childish-sambino** [comment]
And you're _not_ re-assigning the `response` object like this? 
`$response = $response->message('This is message 2 of 2.');`

**Comment by kcifuentes** [comment]
thanks for your help again, as you said that was the problem.
