### ISSUE TITLE
Uncaught exception 'Services_Twilio_TinyHttpException' with message 'Encountered end of file' in /twilio/Services/Twilio/TinyHttp.php

### ISSUE THREAD

**Issue by olikan-acc** [twilio/twilio-php#613]
Recently began to receive errors  

>   [type] => 1
>     [message] => Uncaught exception 'Services_Twilio_TinyHttpException' with message 'Operation timed out after 60001 milliseconds with 0 out of 0 bytes received' in /twilio/Services/Twilio/TinyHttp.php:119
> Stack trace:
> #0 [internal function]: Services_Twilio_TinyHttp->__call('get', Array)
> #1 [internal function]: Services_Twilio_TinyHttp->get('/2010-04-01/Acc...')
> #2 /twilio/Services/Twilio.php(260): call_user_func_array(Array, Array)
> #3 /twilio/Services/Twilio.php(236): Base_Services_Twilio->_makeIdempotentRequest(Array, '/2010-04-01/Acc...', 1)
> #4 /twilio/Services/Twilio/ListResource.php(125): Base_Services_Twilio->retrieveData('/2010-04-01/Acc...', Array)
> #5 /twilio/Services/Twilio/ListResource.php(179): Services_Twilio_ListResource->getPage(0, 50, Array, NULL)
> #6 [internal function]: Services_Twilio_ListResource->getPageGenerator(0, 50, Array, NULL)

    [file] => /twilio/Services/Twilio/TinyHttp.php
    [line] => 119

Changed CURLOPT_TIMEOUT to 120 and now from time to time we get this (see below)

>    [type] => 1
>     [message] => Uncaught exception 'Services_Twilio_TinyHttpException' with message 'Encountered end of file' in /twilio/Services/Twilio/TinyHttp.php:119
> Stack trace:
> #0 [internal function]: Services_Twilio_TinyHttp->__call('get', Array)
> #1 [internal function]: Services_Twilio_TinyHttp->get('/2010-04-01/Acc...')
> #2 /twilio/Services/Twilio.php(260): call_user_func_array(Array, Array)
> #3 /twilio/Services/Twilio.php(236): Base_Services_Twilio->_makeIdempotentRequest(Array, '/2010-04-01/Acc...', 1)
> #4 /twilio/Services/Twilio/ListResource.php(120): Base_Services_Twilio->retrieveData('/2010-04-01/Acc...', Array, true)
> #5 /twilio/Services/Twilio/ListResource.php(179): Services_Twilio_ListResource->getPage(5, 50, Array, '/2010-04-01/Acc...')
> #6 [internal function]: Services_Twilio_ListResource->getPageGenerator(5, 50, Array, '/2010-04-01/Acc...')
> #7 
>     [file] => /twilio/Services/Twilio/TinyHttp.php
>     [line] => 119

There is no definite pattern and frequency for which the problem arises.
We use twilio-php/4.2.0; PHP 5.6
It looks like a problem on the api side. Could you tell me what causes the error?

**Comment by childish-sambino** [comment]
`twilio-php/4.2.0` is several years old and no longer supported. Recommend migrating to a later version.
