### ISSUE TITLE
Migration guide for 5 -> 6?

### ISSUE THREAD

**Issue by neokio** [twilio/twilio-php#614]
There are enough breaking changes in twilio-php 6.0.0 to warrant a migration guide.
Does one exist already?

**Comment by childish-sambino** [comment]
There is not currently a migration guide, but the interface should be compatible with 5.x (return and scalar types added). Are you running into any issues with migration?

**Comment by neokio** [comment]
Not at all! I just hesitate to assume things will work out of the box, and a migration guide would save me time. Really I should just RTFM a little more thoroughly, run tests, check logs, and spot-check every instance in my code. Thanks for the response :)
