### ISSUE TITLE
Duplicate Text Messages

### ISSUE THREAD

**Issue by yusofy** [twilio/twilio-php#615]
### Issue Summary
Hello, i'm building an app with the twilio php sdk. I'm trying the example in the README.MD file and whenever I load the script, I'm getting duplicate text messages. Only 1 sid is outputted, so I'm not entirly sure why i'm getting duplicate text messages. Any help is greatly appreciated. 

### Steps to Reproduce
1. Load the script through the browser

### Code Snippet
```php
<?php

require __DIR__ . '/vendor/autoload.php';

$sid = "XXXXXXXXXXXX"; // Your Account SID from www.twilio.com/console
$token = "XXXXXXXX"; // Your Auth Token from www.twilio.com/console

$client = new Twilio\Rest\Client($sid, $token);
$message = $client->messages->create(
  'XXXXXXXXXX', // Text this number
  array(
    'from' => 'XXXXXXXXXX', // From a valid Twilio number
    'body' => 'Hello from Twilio1!'
  )
);

print $message->sid;

?>
```

### Technical details:
* twilio-php version: 6.0.0 and 6.0.1
* php version: 7.3.4

**Comment by yusofy** [comment]
So, whats interesting - Loading the page on Edge sends it once, doing the same in chrome sends it twice. just FYI

**Comment by childish-sambino** [comment]
This library is not intended to be used in client-side browsers. The risk is exposing your Twilio account credentials.

**Comment by childish-sambino** [comment]
Also, should rotate your auth token since it was in the original summary.

**Comment by yusofy** [comment]
Not sure how to do that. I saw instructions on how to get a secondary token, but couldn't find a way to rotate it. Do you have instructions? Also - that makes sense, I was testing and usually do that in the browser.

**Comment by childish-sambino** [comment]
Requesting the secondary token is the first step. Docs here: https://support.twilio.com/hc/en-us/articles/223136027-Auth-Tokens-and-How-to-Change-Them

**Comment by yusofy** [comment]
Thank you! and thank you for explaining that it was the browser xD
