### ISSUE TITLE
Echo_ is not PSR-4 compatible, and will break with Composer v2.0.

### ISSUE THREAD

**Issue by ellisio** [twilio/twilio-php#616]
### Issue Summary
The `Twilio\TwiML\Voice\Echo_` class is not PSR-4 compatible. I presume this is because "echo" is a reserved keyword in PHP. Noticed this when working on one of our projects this morning.

### Steps to Reproduce
1. Run `composer require twilio/sdk:6.0.1`
2. Observe the composer output.

### Log
```
Deprecation Notice: Class Twilio\TwiML\Voice\Echo_ located in ./vendor/twilio/sdk/src/Twilio/TwiML/Voice/Echo.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.10.0/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185
```

### Technical details:
* twilio-php version: v6.0.1
* php version: 7.3.15

**Comment by childish-sambino** [comment]
Hmm, not seeing this output on my end. `echo` is a reserved word which is why the class name adds an underscore, and the warning you're seeing is because the file name doesn't have the underscore. Any other details you can provide about you setup to help recreate this? OS maybe?

**Comment by L3o-pold** [comment]
@childish-sambino `composer i --no-dev --optimize-autoloader --classmap-authoritative`

**Comment by childish-sambino** [comment]
Yup, I see it now. Working on a fix.

**Comment by arborrow** [comment]
Will this be incorporated into a 6.0.2 tag?

**Comment by childish-sambino** [comment]
@arborrow Yes, either `6.0.2` or `6.1.0`. Depends on other changes. Scheduled for 2020-03-18.

**Comment by hazem-taha** [comment]
I'm still having this issue, anyone got a fix for it ??

**Comment by childish-sambino** [comment]
@hazem-taha What version of this library are you using?

**Comment by hazem-taha** [comment]
@childish-sambino 
`5.42.1`

**Comment by hazem-taha** [comment]
I will update to last version, hopefully it is fixed.

**Comment by childish-sambino** [comment]
Included in [6.1.0](https://github.com/twilio/twilio-php/releases/tag/6.1.0)

**Comment by lptn** [comment]
@childish-sambino 

can we have the same fix on 5.* branch?

**Comment by childish-sambino** [comment]
@lptn  No, there are no plans to backport this change and PRs for older versions will not be approved (per our [supported versions policy](https://github.com/twilio/twilio-php/blob/master/VERSIONS.md#supported-versions)). The main change from v5 to v6 was dropping support for EOL PHP versions which is PHP < v7.2
