### ISSUE TITLE
Misleading Twilio Enqueue instructions

### ISSUE THREAD

**Issue by hdimitrov1** [twilio/twilio-php#622]
### Issue Summary
In the PHP documentation on the webiste, enqueue is listed with an optional first parameter

https://www.twilio.com/docs/taskrouter/twiml-queue-calls

```php
$response = new VoiceResponse();
$response->enqueue(["workflowSid" => "WW0123456789abcdef0123456789abcdef"])
    ->task("{'account_number':'12345abcdef'}");
```
the first parameter is in fact not optional, but needs to be null

### Steps to Reproduce
1. Copy paste example, open page in browser.
2. Observe error

### Code Snippet
```php
$response = new VoiceResponse();
$response->enqueue(["workflowSid" => "WW0123456789abcdef0123456789abcdef"])
    ->task("{'account_number':'12345abcdef'}");
```

### Exception/Log
```
 Argument 2 passed to Twilio\TwiML\TwiML::__construct() must be of the type string or null, array given, called in C:\xampp\htdocs\talkative-engage-cloud\vendor\twilio\sdk\src\Twilio\TwiML\Voice\Enqueue.php on line 22 
```

### Technical details:
* twilio-php version:  5.39.0 tested on 6.1.0 as well
* php version: 7.2, tested on 7.3 as well

Note, reporting here cause I'm not sure if you'd want to fix the api or the documentation.

**Comment by eshanholtz** [comment]
Thanks for pointing this out. This is an error in the documentation. It should be
```
$response = new VoiceResponse();
$response->enqueue(null, array('workflowSid' => 'WW0123456789abcdef0123456789abcdef'));
```
Looks like it needs to be fixed [here](https://github.com/TwilioDevEd/api-snippets/blob/master/rest/taskrouter/twiml/example1/example/example.5.x.php#L8).
