### ISSUE TITLE
Twilio SMS Response

### ISSUE THREAD

**Issue by petersowah** [twilio/twilio-php#626]
### Issue Summary
I want to get the response after I send am SMS. Following the documentation, only the `sid` gets printed instead of the whole response object as seen in the docs.

### Steps to Reproduce
1. Follow the example in the docs, [Twilio Docs](https://www.twilio.com/docs/sms/tutorials/how-to-send-sms-messages-php?code-sample=code-send-an-sms-using-the-programmable-sms-api&code-language=PHP&code-sdk-version=6.x)

### Code Snippet
```php
use Twilio\Rest\Client;

$client = new Client($sid, $token);

$message = $client->messages
                          ->create($request->contacts, [ 'from' => $phone_number, 'body' => $request->message ]);

            print $message->sid;
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-php version: ^6.1
* php version: 7.4.4

**Comment by childish-sambino** [comment]
The sample code only prints the SID. To see the full response object, one way is with `print_r`: `print_r($message->toArray());`

**Comment by petersowah** [comment]
Thanks. Just what I wanted.
