### ISSUE TITLE
Incorrect Type Hint on IncomingPhoneNumberInstance

### ISSUE THREAD

**Issue by datasage** [twilio/twilio-php#627]
### Issue Summary
I have been running through some of my code with Psalm and this one came up as an issue. The type hint for $capabilities is marked as a string. 

In the API response this is an object with several boolean properties.

The client does parse this into an associative array.

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Exception/Log
Psalm error, if it matters.

```
ERROR: InvalidArrayOffset - MyFile.php:1 - Cannot access value on variable $number->capabilities using offset value of 'mms', expecting int (see https://psalm.dev/115)
            $entity->mmsAvailable = $number->capabilities['mms'];
```

### Technical details:
* twilio-php version: 6.2
* php version: 7.3

**Comment by eshanholtz** [comment]
Looks like it's the same issue as https://github.com/twilio/twilio-node/issues/529. This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.
