### ISSUE TITLE
Class Twilio\TwiML\Voice\Echo_ does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by lptn** [twilio/twilio-php#628]
### Issue Summary
Composer 2.0 has changed a way to load classes. Composer 1.9+ displays a deprecation warning for classes that composer 2.0 will not load

### Steps to Reproduce
1. install the package of 5.* version using latest stable composer version (1.10.1)
2. see the warning:
```
Deprecation Notice: Class Twilio\TwiML\Voice\Echo_ located in ./vendor/twilio/sdk/src/Twilio/TwiML/Voice/Echo.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

### Technical details:
* twilio-php version: 5.42.2 (indirect dependency of [aloha/laravel-twilio)](https://github.com/aloha/laravel-twilio), issue on laravel wrapper repo: https://github.com/aloha/laravel-twilio/issues/175
* php version: 7.4.4

**Comment by childish-sambino** [comment]
Duplicates https://github.com/twilio/twilio-php/issues/616
