### ISSUE TITLE
Class TwilioML\Voice\Echo does not comply with psr-4 autoloading standard.

### ISSUE THREAD

**Issue by Xenology** [twilio/twilio-php#630]
### Issue Summary
Composer reports the following deprecation notice when the Twilio library is autoloaded.

```
Deprecation Notice: Class Twilio\TwiML\Voice\Echo_ located in ./vendor/twilio/sdk/src/Twilio/TwiML/Voice/Echo.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.10.5/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

### Steps to Reproduce
1. Install composer
2. ```composer require twilio/sdk```
3. ```composer dump-autoload -o```

### Technical details:
* twilio-php version: 6.3.0
* php version:  PHP 7.1.14

**Comment by childish-sambino** [comment]
Duplicates https://github.com/twilio/twilio-php/issues/616
