### ISSUE TITLE
How to check for reach-ability change of channel members in Twilio programmable chat JS SDK

### ISSUE THREAD

**Issue by AbhijitAQB** [twilio/twilio-php#631]
### Issue Summary
I'm trying to add reach-ability indicator feature in my existing twilio chat. It's a one to one chat. I don't want to show whether any member is online but this feature is required for sending notification via mail. Notification will be sent only to offline members.

I followed their official doc : https://www.twilio.com/docs/chat/reachability-indicator. There is a small code snippet at the bottom of the page but that didn't worked. `updated` event is not getting triggered at any member end. I have set `ReachabilityEnabled` to TRUE in my chat service.

I figured out a way to achieve this using `setInterval()` but I think using event handler is the proper way. Can you show me how to achieve this using event handler or am I mistaking somewhere?

Code below will execute when I click on a channel.

### Code Snippet
```php
// Initialise the Chat client
// Get the current channel by it's unique name

let currentUser = chatClient.user;

// check for reachability change
setInterval(() => {
                currentChannel.getMembers().then(members => {
                    members.forEach(member => {
                        member.getUser().then(user => {
                            if (currentUser.state.identity !== user.state.identity) {
                                if (user.state.online === true) {
                                    $('.contact').attr('is-online', 1);
                                } else if (user.state.online === false) {
                                    $('.contact').attr('is-online', 0);
                                }
                            }
                        }).catch(error => {
                            console.error(error);
                        });
                    });                    
                }).catch(error => {
                    console.error(error);
                });
            }, 500);
```
### Technical details:
* twilio-php version: 6.3.0
* php version: 7.3
* JS SDK version: 3.3.5

**Comment by eshanholtz** [comment]
Hi @AbhijitAQB 
The code snippet you provided appears to be for the JS SDK, not for twilio-php. The REST API documentation provides information on [how to retrieve information about a User in php](https://www.twilio.com/docs/chat/rest/user-resource#fetch-a-user-resource).

**Comment by AbhijitAQB** [comment]
Hi @eshanholtz 
Actually I want to check for user reach-ability change in client side (using JS SDK). So, can you provide the repository link for JS SDK?

**Comment by eshanholtz** [comment]
@AbhijitAQB 
I recommend [submitting a support ticket](https://twilio.com/help/contact) for further help with this.
