### ISSUE TITLE
Pagination issue with searching available phone numbers

### ISSUE THREAD

**Issue by harikt** [twilio/twilio-php#632]
### Issue Summary

There is no next page url. It looks like the response returned doesn't include the meta data information when dumping the response.

```php
$client = new Twilio\Rest\Client(....)
$page_number  = 1;
$page_size = 10;
$client->availablePhoneNumbers('US')
    ->local
    ->page($options, $page_size, \Twilio\Values::NONE, $page_number);
```

This returns a `Twilio\Rest\Api\V2010\Account\AvailablePhoneNumberCountry\LocalPage` object. But it misses a few information when trying to retrieve `getNextPageUrl` .

If you increase the page_size to say 100, it is able to retrieve 100. So this is not because there is more results available. But meta data is missing some how.

### Technical details:
* twilio-php version: 6.4.0
* php version: 7.4.4

**Comment by childish-sambino** [comment]
Listing available phone numbers is limited to 30 results. At least, that's what I remember and what I'm seeing when running the sample code.

**Comment by harikt** [comment]
So do you mean that the pagination should not work if you fetch 10 results out of 30. So what about the rest 20 results.

If you look at https://www.twilio.com/docs/phone-numbers/global-catalog/api/available-numbers?code-sample=code-search-for-toll-free-us-numbers-4&code-language=curl&code-sdk-version=default according to the response it gives meta data. But if you dump the response then there is no meta data.

If you are saying meta data will never be returned or there is no pagination available, then you can close it.

Thank you.

**Comment by childish-sambino** [comment]
At one time, the metadata was included in the response, but pagination was later removed from this API for security reasons. You can retrieve up to 30 numbers from this API and recommend using filtering to narrow down the target number(s).
