### ISSUE TITLE
unable to install composer require twilio/sdk. 

### ISSUE THREAD

**Issue by designerprasan007** [twilio/twilio-php#637]
hi. i'm a kind newbie to twilio. i'm trying to install twilio/sdk by composer but getting an error as given below. please help to solve this.

twilio-php# composer require twilio/sdk
`composer require twilio/sdk`

Using version ^6.5 for twilio/sdk
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)

Installation failed, deleting ./composer.json.

                                                                                           
  [ErrorException]                                                                         
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  
                                                                                           

require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

and my php version is
twilio-php# php -v
PHP 7.3.18-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May 14 2020 10:34:21) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.18, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.18-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
what's wrong with the composer of twilio.

**Comment by magic-77** [comment]
Looks like your composer is outdated. Try with PHP 7.2 or run
```
composer self-update
composer install
```

**Comment by thinkingserious** [comment]
Thanks for helping out @magic-77!

@designerprasan007 

Did updating composer work for you?

With best regards,

Elmer
