### ISSUE TITLE
SMS-capable inbound phone number or short code for your account

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [twilio/twilio-php#638]
Hi @dataich 

 i have many try but same issue. 
```
            [RestException] => SimpleXMLElement Object
                (
                    [Code] => 21606
                    [Message] => The From phone number +17xxxxxxxx00 is not a valid, SMS-capable inbound phone number or short code for your account.
                    [MoreInfo] => https://www.twilio.com/docs/errors/21606
                    [Status] => 400
                )
```

i have create account and also buy sms send number of twilio 
so what do next for solove this ?
because i have checked docs but not any mention others step

**Comment by thinkingserious** [comment]
Hello @rajesh-smartwebtech,

From the error message, the from phone number does not have SMS capabilities. Could you [please verify](https://www.twilio.com/console/phone-numbers)? The from number should be listed at that link in your account. Next to the phone number should be an icon that when you hover over it, says "SMS capable". If not, you will need to purchase a number with SMS capabilities.

With best regards,

Elmer

**Comment by rajesh-smartwebtech** [comment]
@thinkingserious  i have checked recently sandbox token  with sms send not working

**Comment by thinkingserious** [comment]
Please contact our [support team](https://support.twilio.com) with the from phone number you are using so that we can verify the phone number has the required capabilities. Thank you!

**Comment by thinkingserious** [comment]
@rajesh-smartwebtech,

I'm closing this ticket out, since this is not a helper library issue.
