### ISSUE TITLE
“I’m trying to use the PHP helper library to send a text message, but it’s not working. Here’s my code and the error message. What’s wrong?

### ISSUE THREAD

**Issue by chinmaya-gupta22** [twilio/twilio-php#640]
![image](https://user-images.githubusercontent.com/49202034/83553343-adb7cc00-a528-11ea-8e6f-ed638aefab85.png)

**Comment by ctwillie** [comment]
You  are using several variables, (```$accountSid, $authToken, $toNumber, $fromNumber```), but they are never defined. You need to define those variables before you can use them.
Something like this.
```php
$accountSid = 'xxxxxxxxxxxxxx';
$authToken = 'xxxxxxxxxxxxxx';
$toNumber = 'xxxxxxxxxxxxxx';
$fromNumber = 'xxxxxxxxxxxxxx';
$client = new Twilio\Rest\Client($accountSid, $authToken);
$message = $client->account->messages->create($toNumber, $fromNumber, $bodyText);
```

Hope this helps!

**Comment by childish-sambino** [comment]
@ctwillie 👍  Thanks for helping out!
