### ISSUE TITLE
Guzzle client - parameter of type array not working

### ISSUE THREAD

**Issue by j-xhesi** [twilio/twilio-php#649]
### Issue Summary
When replacing default http client with guzzle client, passing array parameters for statusCallbackEvent in creating call resource not working properly.

```
return new Twilio\Rest\Client($this->config->sid, $this->config->token, null, null, 
    new Twilio\Http\GuzzleClient(new GuzzleHttp\Client())
);
```
### Steps to Reproduce
1. Replace twilio default client with guzzle client
```
$client = new \Twilio\Rest\Client($this->config->sid, $this->config->token, null, null, 
    new \Twilio\Http\GuzzleClient(new \GuzzleHttp\Client())
);
```
2. Create call resource, expect call status updates to url for initiated and ringing events
```
$client->calls->create($to, $from, [
    'url' => {{callback_url}},
    'statusCallback' => {{status  url}},
    'statusCallbackEvent' => ['initiated', 'ringing']
]);
```

3. If 'statusCallbackEvent' is type of array twilio http client will work. (ie call backs posted to server), when using guzzle client  (ie call backs not posted to server)

### Guzzle (wont work - calls will be made, status call back will not receive for initiated or ringing)
```
$client->calls->create($to, $from, [
    'url' => {{callback_url}},
    'statusCallback' => {{status  url}},
    'statusCallbackEvent' => ['initiated', 'ringing']
]);
```
### Twilio Client (Works - multiple events)
```
$client->calls->create($to, $from, [
    'url' => {{callback_url}},
    'statusCallback' => {{status  url}},
    'statusCallbackEvent' => ['initiated', 'ringing']
]);
```
### Guzzle (Works - call back received only for one event, use case is to receive for multiple events)
```
$client->calls->create($to, $from, [
    'url' => {{callback_url}},
    'statusCallback' => {{status  url}},
    'statusCallbackEvent' => 'initiated'
]);
```

### Technical details:
* twilio-php version:  "twilio/sdk": 6.9.0
* php version: 7.3

**Comment by j-xhesi** [comment]
![Screenshot from 2020-07-20 19-58-04](https://user-images.githubusercontent.com/42129557/87949194-5a431280-cac3-11ea-85a1-8cf719cea0c2.png)

**Comment by j-xhesi** [comment]
Fix is to avoid using form_params in [TwilioGuzzleClient](https://github.com/twilio/twilio-php/blob/master/src/Twilio/Http/GuzzleClient.php) where duplicate keys are not supported, instead form body from params

**Comment by childish-sambino** [comment]
I'm seeing a similar issue. Looks related to https://github.com/guzzle/guzzle/issues/1196

Working on a fix.
