### ISSUE TITLE
Twilio Rest Client request, /tmp files not cleaned up

### ISSUE THREAD

**Issue by markotitel** [twilio/twilio-php#652]
### Issue Summary
When downloading a media from Twilio with
```
$response = $client->request("GET", $uri);
$mediaLocation = $response->getContent()["redirect_to"];
```
Looks like that temporary files are not deleted from `/tmp` assuming `/tmp` is PHP temp dir.

### Steps to Reproduce
1. Download a file with Twilio Client
2. Save it in S3 or local 
3. Go to /tmp directory and you'll find phpXXXXX tmp file

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-php version: 5.28.1
* php version: 7.2

**Comment by childish-sambino** [comment]
Is this using Twilio's bulk exports? What code is saving the file in step 2?
