### ISSUE TITLE
Verify if WhatsApp number

### ISSUE THREAD

**Issue by albertord84** [twilio/twilio-php#653]
Hi! There is a way to verify if a phone number has a whatsapp account with Twilio? Perhaps returning the number default name and picture url. 
Thanks! :)

**Comment by eshanholtz** [comment]
Are you asking about an API endpoint that lists something like "whatsapp" as a phone number capability? Or are you asking about checking whether a user's phone number is enabled for WhatsApp? I recommend checking out the [F.A.Q](https://www.twilio.com/docs/whatsapp/best-practices-and-faqs) to see if your question is answered there.

**Comment by albertord84** [comment]
Hi, the question is: I have a phone number, but I don't whether it's a WhatsApp number too. I can make a call to it, but, can I send a WhatsApp message without getting an error?

So I need to know if Twilio has something like: Twilio->CheckWhatsappPhone(param PhoneNumer) and Twilio answer me yes or not or something like this...

Thanks:)

**Comment by thinkingserious** [comment]
Hello @albertord84,

We do not have an API as you describe.

Every time you send a WhatsApp message, Twilio automatically checks if the number is enabled for WhatsApp and will fail the message with error code 63003 if the destination was found to be invalid. ([link to docs](https://www.twilio.com/docs/whatsapp/best-practices-and-faqs#api))

For further assistance or to provide additional feedback, please [file a support ticket](https://twilio.com/help/contact).

With best regards,

Elmer
