### ISSUE TITLE
ForwardedFrom list

### ISSUE THREAD

**Issue by olikan** [twilio/twilio-php#658]
Hello, guys!

Is any way to get the list of calls by ForwardedFrom field?
I tried to add param ForwardedFrom and today's date and it responses with the full list of call by this date and doesn't sort by ForwardedFrom.
Or may be, If I will request by "To" field, can I get in the response body the field where further the call was dialed to?

**Comment by thinkingserious** [comment]
Hello @olikan,

I don't see a way to filter by `ForwardedFrom` directly via the API. Note that we don't always have that information, as it's carrier dependent.

Could you please provide a code snippet that illustrates what you are trying to achieve?

With best regards,

Elmer
