### ISSUE TITLE
Can't install in laravel 6

### ISSUE THREAD

**Issue by tribitsolution3** [twilio/twilio-php#659]
Could not load package mews/purifier in http://repo.packagist.org: [UnexpectedValueException] Could not parse version constraint ~4.*: Invalid version string "~4.*

 Could not parse version constraint ~4.*: Invalid version string "~4.*"

**Comment by thinkingserious** [comment]
Hello @tribitsolution3,

I'm not quite sure this is an issue related to this helper library. However, I found [this solution](https://stackoverflow.com/questions/63862580/composer-runtimeexception-could-not-load-package-mews-purifier) that may help you. Please take a look and let us know. Thanks!

With best regards,

Elmer

**Comment by KasperFranz** [comment]
You have an issue in your version string :).

It should be ~4.0 the problem it is reporting on is mews/purifier which this library does not use?

**Comment by tribitsolution3** [comment]
@thinkingserious. Thanks!

**Comment by thinkingserious** [comment]
Thanks for helping out @KasperFranz!

@tribitsolution3 you are welcome!
