### ISSUE TITLE
Fax issue: [HTTP 403] Unable to create record

### ISSUE THREAD

**Issue by jonjieviduya** [twilio/twilio-php#662]
Whenever I tried to use my test credentials for Fax, it throws an error:

> [HTTP 403] Unable to create record: Resource not accessible with Test Account Credentials

**Code**
```
public function send()
{
	$sid    = env('TWILIO_ACCOUNT_SID');
	$token  = env('TWILIO_AUTH_TOKEN');
	$to = env('TO_EXAMPLE');
	$twilio = new Client($sid, $token);
	$mediaURL = asset('pdfs/dummy.pdf');
	$from = ["from" => '+' . env('TWILIO_NUMBER')];

	$fax = $twilio->fax->v1->faxes
		->create('+' . $to, $mediaURL, $from);

	print($fax->sid);
}
```

**Comment by thinkingserious** [comment]
Hello @jonjieviduya,

It appears that the fax API requires a non-test account. If you did not want to upgrade, you could test this endpoint with our [OpenAPI specification](https://github.com/twilio/twilio-oai/blob/main/spec/json/twilio_fax.json).

With best regards,

Elmer
