### ISSUE TITLE
Incorrect default value type for MessageOptions::create parameter

### ISSUE THREAD

**Issue by davefu** [twilio/twilio-php#663]
### Issue Summary
Since default value for all parameters is `Twilio\Value::NONE` constant with string value (_except array values from version >6.2_), PHP throws `TypeError` for integer parameters, cause it cannot convert (string) value of the constant to int.
I've noticed this issue while calling `Twilio\Rest\Api\V2010\Account\MessageOptions::create()` option builder, but I think it affects all option builders with integer parameter (and default value of `Twilio\Value::NONE`).

### Steps to Reproduce
1. call MessageOptions::create() without any parameter

### Exception/Log
```
Fatal error: Uncaught TypeError: Argument 9 passed to Twilio\Rest\Api\V2010\Account\MessageOptions::create() must be of the type int, string given, called in <file from our project>
```

### Technical details:
* twilio-php version: >6.0.0
* php version: >7.1

(The issue applies also for PHP 7.0, but since affected package versions support only 7.1 and higher, I've reported this version.)

**Comment by eshanholtz** [comment]
Nice catch! This was an oversight when adding type hints during our PHP7 upgrade. We need additional [Values unit testing](https://github.com/twilio/twilio-php/blob/main/tests/Twilio/Unit/ValuesTest.php) that fails on the current implementation to ensure we don't miss this moving forward. 

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.
