### ISSUE TITLE
The 'To' number is not a valid phone number.

### ISSUE THREAD

**Issue by KevinRignault** [twilio/twilio-php#665]
Hello there,

I have a trouble with Twilio :
- In test mode, my script works well but I don't receive message (I have the response from the API with a status of my message as 'Queued')
- In live mode, I have this error : The 'To' number +33600000000 is not a valid phone number. (Of course I put a real phone number, my own)

Here is the script : 

```
public function sendSMS()
{
	$sid = env('TWILIO_SID');
	$token = env('TWILIO_TOKEN');

	$client = new \Twilio\Rest\Client($sid, $token);
	$message = $client->messages->create(
	  '+33600000000', // Here I put a real phone number, my own
	  [
	    'from' => '+33600000000', // Here I put a valid twilio number
	    'body' => $body
	  ]
	);

	return $message;
}
```

Can you please help me ?

Thanks a lot,

**Comment by childish-sambino** [comment]
In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).
