### ISSUE TITLE
Error with the link

### ISSUE THREAD

**Issue by CodeNinjaUG** [twilio/twilio-php#666]
```
   TypeError

  Argument 2 passed to Twilio\Rest\Api\V2010\Account\CallList::create() must be of the type string, null given, called in C:\xampp\htdocs\VoiceCalls\app\Console\Commands\callEveryOne.php on line 53

  at C:\xampp\htdocs\VoiceCalls\vendor\twilio\sdk\src\Twilio\Rest\Api\V2010\Account\CallList.php:53
    49|      * @param array|Options $options Optional Arguments
    50|      * @return CallInstance Created CallInstance
    51|      * @throws TwilioException When an HTTP error occurs.
    52|      */
  > 53|     public function create(string $to, string $from, array $options = []): CallInstance {
    54|         $options = new Values($options);
    55|
    56|         $data = Values::of([
    57|             'To' => $to,

  1   C:\xampp\htdocs\VoiceCalls\app\Console\Commands\callEveryOne.php:53
      Twilio\Rest\Api\V2010\Account\CallList::create("704277679", ["voice.linkagesug.com/broadcast"])

  2   C:\xampp\htdocs\VoiceCalls\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:37
      App\Console\Commands\callEveryOne::handle()
```

### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```php
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-php version: 
* php version:

**Comment by CodeNinjaUG** [comment]
foreach (User::cursor() as $user ) {
            $call = $twilio->calls
                ->create( $user->phone_number, // to
                    config('services.twilio.phone_number'),
                    [ "url" => "http://voice.linkagesug.com/broadcast"]
                );
        }
these are my parameters

**Comment by childish-sambino** [comment]
Looks like `config('services.twilio.phone_number')` in your code is returning `null`. Should investigate how this config is being loaded.

**Comment by CodeNinjaUG** [comment]
'twilio' => [
        'account_sid' => env('TWILIO_ACCOUNT_SID'),
        'auth_token'  => env('TWILIO_AUTH_TOKEN'),

    ],

**Comment by CodeNinjaUG** [comment]
Got i didnt include the phone number thank you
'twilio' => [
'account_sid' => env('TWILIO_ACCOUNT_SID'),
'auth_token' => env('TWILIO_AUTH_TOKEN'),
'phone_number'=>env('TWILIO_PHONE_NUMBER'),
],
