### ISSUE TITLE
An attempt to retrieve content from url returned the HTTP status code 419

### ISSUE THREAD

**Issue by CodeNinjaUG** [twilio/twilio-php#668]
An attempt to retrieve content from url returned the HTTP status code 419

### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```php
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-php version: 
* php version:

**Comment by childish-sambino** [comment]
Could you provide more details, code samples, and links for what you're trying to accomplish?

**Comment by CodeNinjaUG** [comment]
public function call(){

       $sid    = config('services.twilio.account_sid');
       $token  = config('services.twilio.auth_token');
       $twilio = new Client($sid, $token);

       foreach (User::cursor() as $user ) {
           $call = $twilio->calls
               ->create( $user->phone_number, // to
                   config('services.twilio.phone_number'),
                   [ "url" => "http://voice.linkagesug.com/broadcast"]
               );
       }
   }

  public function broadcast()
    {
         $response =  new Twilio\TwiML\VoiceResponse();
         $response->play('http://demo.twilio.com/docs/classic.mp3');
         echo $response;
         // $response->header('Content-Type', 'audio/mp3');
         // var_dump($response);
   }

**Comment by eshanholtz** [comment]
I'd double check the link provided as the "url" parameter, making sure that it is [publicly available and returns proper TwiML](https://www.twilio.com/docs/voice/make-calls#specify-a-url-parameter). If you need further help, I recommend [reaching out to support](https://twilio.com/help/contact)

**Comment by CodeNinjaUG** [comment]
Helo the link is publicly available but it looks like the link must be an .xml file because when i use  .xml to call the demo link used by twilio it plays and works for me

**Comment by eshanholtz** [comment]
Correct, Twilio is expecting the response returned by that `broadcast()` function to be valid TwiML (which is xml format)

**Comment by CodeNinjaUG** [comment]
how do we create a dynamic .xml how do we create a dynamic url with the mp3 link shared in it

**Comment by thinkingserious** [comment]
Hello @CodeNinjaUG,

Could you please explain what the use case of your project is? (please describe what success looks like) I'm having a bit of trouble understanding what you are trying to achieve. 

With best regards,

Elmer

**Comment by CodeNinjaUG** [comment]
i am creating an app where i upload audio to through the application and attach a csv of numbers then send the audio to the list of numbers in the csv file am asking if there is any way i can be creating switch to the different xml links that are supposed to be played by twilio without changing the links manually

**Comment by thinkingserious** [comment]
Hello @CodeNinjaUG,

What you describe is not an issue related to this helper library, so I will close this issue and I would suggest that you reach out to our [support team](https://support.twilio.com/hc/en-us).

That said, it seems like you will need to implement some logic that queries a data store of your xml links and matches those links to your desired criteria, utilizing a function whose job is to determine the correct link.

With best regards,

Elmer
