### ISSUE TITLE
[6.13] Twilio\Rest\Video not found in Twilio\Rest\Client

### ISSUE THREAD

**Issue by Matt-Evans-UKDS** [twilio/twilio-php#670]
### Issue Summary
After upgrading to 6.13, am now seeing an error when attempting to call the Video class via the Client class that the Video class cannot be found. Issue does not persist when downgrading back to 6.12.

### Steps to Reproduce
1. Set up a new or existing PHP project (in my case, Laravel 8)
2. Install or upgrade the twilio-php package v 6.13
3. Attempt to access Client->video after setting up the Twilio\Rest\Client using Twilio credentials

### Code Snippet
```php
  // app\Services\TwilioRoomService@59-82

    /**
     * Make Twilio room based on name
     *
     * @param string $name
     * @return RoomInstance
     * @throws TwilioException
     */
    public function makeRoom(string $name): RoomInstance
    {
        try {
            /** @var \Twilio\Rest\Client $this->twilio */
            return $this->twilio->video->v1->rooms->create([
                "type" => "go",
                "uniqueName" => $name
            ]);
        } catch (TwilioException $e) {
            Log::critical('Twilio Exception', [
                'Code' => $e->getCode(),
                'Message' => $e->getMessage()
            ]);

            throw $e;
        }
    }
```

### Exception/Log
(truncated to relevant parts)
```
{
    "class": "Error",
    "message": "Class 'Twilio\\Rest\\Video' not found",
    "code": 0,
    "file": ".../vendor/twilio/sdk/src/Twilio/Rest/Client.php:913",
    "trace": [
        ".../vendor/twilio/sdk/src/Twilio/Rest/Client.php:976",
        ".../app/Services/TwilioRoomService.php:70",
}
```

### Technical details:
* twilio-php version: 6.13
* php version: 7.4.7
* composer version: 2.0.7

**Comment by shwetha-manvinkurke** [comment]
Hi @Matt-Evans-UKDS, 

Would you be able to try the latest 6.16 version and see if you can find the same issue? I wasn't able to reproduce it in the current version. Let me know if you have any concerns using the latest version.

Thanks,
Shwetha
