### ISSUE TITLE
Get SMS Price type:question

### ISSUE THREAD

**Issue by wifirevaithi** [twilio/twilio-php#674]
I need to get the sms price,Now getting SMS details in callback and checking the sms details it's returning empty value,

My Question is: Anyway to get sms price for a number?or please anyone suggest a good method to update the sms price in my database

Thank you.

**Comment by thinkingserious** [comment]
Hello @wifirevaithi,

You can obtain the pricing for a given sent SMS message using the [Messages endpoint](https://www.twilio.com/docs/sms/tutorials/how-to-retrieve-and-modify-message-history-php?code-sample=code-list-all-messages&code-language=PHP&code-sdk-version=6.x). 

That said, the [SMS webhook](https://www.twilio.com/docs/usage/webhooks/sms-webhooks?code-sample=code-send-an-sms-with-a-statuscallback-url&code-language=PHP&code-sdk-version=6.x) should include the price; however, it does take a few seconds to process.

Please take a look and let me know if you need further assistance.

With best regards,

Elmer

**Comment by wifirevaithi** [comment]
hi @thinkingserious thanks for your response but my problem is it takes few seconds i placed a update price function in status update function which will be callback will status is changed, but there i can't get the price. So your suggesting me to run the corn job in my server to update the price. Please suggest.
Thank you
