### ISSUE TITLE
How can i validate ACCOUNT SID & AUTH TOKEN ??

### ISSUE THREAD

**Issue by Ok9xNirab** [twilio/twilio-php#677]
I didn't see any methods to validate credentials !!

**Comment by shwetha-manvinkurke** [comment]
Hi @Ok9xNirab The credentials are validated automatically when you create a client instance. What exactly is your use case?

**Comment by Ok9xNirab** [comment]
> Hi @Ok9xNirab The credentials are validated automatically when you create a client instance. What exactly is your use case?

I'm making a wordpress plugin . So, I want to validate Twilio credentials before saved !! 

I already do it by Guzzle-http .
Here is my code :
https://github.com/springdevs/SMS/blob/c309731b8b09479fb1cb71638a856b1f70075cf2/includes/Admin/Forms.php#L27

Thanks.

**Comment by shwetha-manvinkurke** [comment]
Maybe try the [verify api](https://www.twilio.com/docs/verify/api/verification-check)?

**Comment by Ok9xNirab** [comment]
> Maybe try the [verify api](https://www.twilio.com/docs/verify/api/verification-check)?

Yes . validate account sid & token , before saved !!
