### ISSUE TITLE
Remove proprietary formatting for serializing MessageInstance to string

### ISSUE THREAD

**Issue by slothstronaut** [twilio/twilio-php#678]
I'd be more than happy to submit a PR for this since it will be easy to implement.

This custom response string makes no sense, why not just return JSON? Seems like there must be some reason for making it so painful to get the complete response object.

From `src/Twilio/Rest/Api/V2010/Account/MessageInstance.php`

```
    /**
     * Provide a friendly representation
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "$key=$value";
        }
        return '[Twilio.Api.V2010.MessageInstance ' . \implode(' ', $context) . ']';
    }
```

This response string us not useful, it would be much better if it were JSON, but since I'm sure there are dependencies on this existing format, probably better to just add a `->toJson()` method to not break things.

Is there some underlying reason why `MessageInstance` shouldn't be able to return a full JSON object of all of its fields?

That aside, there is also a native PHP function to accomplish the above: https://www.php.net/manual/en/function.http-build-query.php, so not sure why this was done with a foreach loop.

**Comment by shwetha-manvinkurke** [comment]
Hi @slothstronaut Why is the response string not useful to you and how exactly would the json output be better for your use case? That said, this file is auto generated by our internal library and we would need to make changes there and a community PR wouldn't help here.

**Comment by slothstronaut** [comment]
Ah ok, that makes a lot more sense. That string returned would require building a custom parser to gather any kind of metrics on the fields returned, otherwise what is the point of even collecting that info? I guess for logging while doing development, but beyond that it doesn't seem of very much value.

Appreciate the follow-up anyway 👍
