### ISSUE TITLE
Fetch All SubAccount Usage Resource of Twilio Main Account

### ISSUE THREAD

**Issue by vedawebtech** [twilio/twilio-php#679]
I am new in PHP and twillio. I am trying to fetch all type usage information of my sub accounts. Basically I want store this information in my google sheet and need this value

https://i.stack.imgur.com/zz4CW.png

I am able to fetch all my sub accounts SID like below

```
<?php
require_once 'vendor/autoload.php';

use Twilio\Rest\Client;
$sid  = "my main account sid";
$token = "my token";

$twilio = new Client($sid, $token);

$accounts = $twilio->api->v2010->accounts
                               ->read([], 20);

$items = array();
foreach ($accounts as $record) {
    $items[] = $record->sid;
   
}
 print_r($items);
?>
```

This is fine. I can loop my all sub account inside forearch for get usage. For Fetch usage I am following this guide

and code is like below

```
<?php
require_once 'vendor/autoload.php';

use Twilio\Rest\Client;
$sid  = "my main account";
$token = "my token";

$client = new Client($sid, $token);

$records = $client->usage->records->read(
    array(
        "category" => "sms-outbound",
        "startDate" => "2021-02-01",
        "endDate" => "2021-02-28"
    )
);

// Loop over the list of records and echo a property for each one
foreach ($records as $record) {
    echo $record->price;
}
?>
```

Currently I am getting cost of my main account.

I am not getting idea How I can get cost of MY sub account with different type usage which I have mentioned in above image. I am not getting idea that I am following correct API guideline for achieve my goal or not. Let me know if someone here can guide me for same or can give me example.

Thanks a lot!

**Comment by johnpaulmedina** [comment]
There are several ways to achieve this.

1. Create a Twilio instance using the sub account SID, and sub account token or API Key.

2. Create an instance using the main account Sid, main account token, and third parameter being the sub account SID - I'm away from my computer at the moment but I believe it is the third param and how I achieve this.

You'll want to loop twice. Once for each sub account and then another for each billing category.

**Comment by thinkingserious** [comment]
Thank you for helping out @johnpaulmedina!

@vedawebtech, please feel free to reopen if you still require assistance. Thank you!
