### ISSUE TITLE
Support for PHP8

### ISSUE THREAD

**Issue by ibpavlov** [twilio/twilio-php#682]
### Issue Summary
PHP 8 is not officially supported. Do you plan to support it soon? 

I am using only a subset of this library and upgraded successfully to PHP 8. I haven't found any issue with my use case working with the current version, but it will be better if it's officially supported. 
Maybe a good first step would be to add it in the `.travis.yml` file and run tests against it to check if there are a lot of issues. 

### Technical details:
* twilio-php version: 6.20
* php version: 8

**Comment by JenniferMah** [comment]
Hi @ibpavlov we don't have an official date yet for when we will support PHP 8. I think adding it to the `.travis.yml` and running tests against it is a great idea! If you open a PR and link this issue we will be able to start the review process.
