### ISSUE TITLE
upgrade from 5 to 6 

### ISSUE THREAD

**Issue by Goddard** [twilio/twilio-php#685]
I noticed in the wiki a guide exists for upgrading from 4 to 5 do we have one for upgrading from 5 to 6?

Thanks

**Comment by JenniferMah** [comment]
Hi @Goddard we don't have a specific upgrade guide for 5 to 6.[ Here's the changelog from when we released v6](https://github.com/twilio/twilio-php/releases/tag/6.0.0). Most of these changes in the changelog were changes under the hood for the twilio-php library and shouldn't require any changes on the your part. There was some changes to how the `read()` function is called in 6.2.X to 6.3.x which is documented [here](https://github.com/twilio/twilio-php/blob/main/UPGRADE.md#2020-04-15-62x-to-63x).
