### ISSUE TITLE
Wrong character encoding when fetching message

### ISSUE THREAD

**Issue by IllesAprod** [twilio/twilio-php#686]
### Issue Summary
When fetching a message with twilio-php it gives me wrong encoded characters (on client side with js sdk we get good encoding)

### Steps to Reproduce
1. Send message to conversations from js sdk containing these characters: ááűűúúőőóóüüööíí
2. Fetching message with twilio-php 
```
 $messageSid = 'YYY';
 $message = $client->conversations->v1->services('XXX')->conversations($sid)->messages($messageSid)->fetch();
```
3.  dump $message->body getting characters like: Ã¡Ã¡Å±Å±ÃºÃºÅÅÃ³Ã³Ã¼Ã¼Ã¶Ã¶Ã­Ã­

**Possible workaround:**
With iconv we were able to minimize wrong characters, but "ő" stil not working
ááűűúúőőóóüüööíí --> ááűűúú�?�?óóüüööíí 
Example code:
```
$fixed = iconv("UTF-8", "Windows-1252//TRANSLIT", $message->body);
```

### Technical details:
* twilio-php version: 6.21.0 
* php version: 7.4

**Comment by shwetha-manvinkurke** [comment]
@IllesAprod I wasn't able to reproduce it. Have you tried curl-ing to see what you get back?
```curl
curl -H "Accept-Charset: utf-8" -X GET 'https://conversations.twilio.com/v1/Conversations/CHXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/Messages/IMXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' \
-u $TWILIO_ACCOUNT_SID:$TWILIO_AUTH_TOKEN
```

**Comment by IllesAprod** [comment]
@shwetha-manvinkurke ![Screenshot 2021-05-18 at 7 42 31](https://user-images.githubusercontent.com/10177368/118597264-bee70080-b7ac-11eb-8a37-375bf14236d2.png)
Thanks for your reply, I tried with curl (I had to put /Services/ISXXX... in the url but I dont think it makes any difference)

The message what i sent was (Screenshot from twilio js conversations sdk)
![Screenshot 2021-05-18 at 7 42 31](https://user-images.githubusercontent.com/10177368/118597280-c5757800-b7ac-11eb-98aa-ec13a74827c9.png)
```
ááűűúúőőóóüüööíí
```

With curl i get:
![Screenshot 2021-05-18 at 7 44 20](https://user-images.githubusercontent.com/10177368/118597362-e0e08300-b7ac-11eb-899f-eb87499ef635.png)
```
{"body": "\u00c3\u00a1\u00c3\u00a1\u00c5\u00b1\u00c5\u00b1\u00c3\u00ba\u00c3\u00ba\u00c5\u0091\u00c5\u0091\u00c3\u00b3\u00c3\u00b3\u00c3\u00bc\u00c3\u00bc\u00c3\u00b6\u00c3\u00b6\u00c3\u00ad\u00c3\u00ad"
```

Which is converted (using this converter: https://r12a.github.io/app-conversion/)
```
Ã¡Ã¡Å±Å±ÃºÃºÅÅÃ³Ã³Ã¼Ã¼Ã¶Ã¶Ã­Ã­
```

And that looks the same what i get when I try
```
 $message = $client->conversations->v1->services('XXX')->conversations($sid)->messages($messageSid)->fetch();
 var_dump($message->body);
 ```
 
 So as I can see this is a Twilio Backend related error, can u help how to reach them with that?

**Comment by IllesAprod** [comment]
Hi @shwetha-manvinkurke 

We went further and we had to use $body = utf8_decode($message->body); to get good encoding (maybe it should be added to the sdk?)

Thanks for your help

**Comment by shwetha-manvinkurke** [comment]
Hi @IllesAprod I suggest reaching out to [support](https://support.twilio.com/) and discussing this issue with them.
