### ISSUE TITLE
Documentation improvment request - Conversations Attributes and not valid JSON error

### ISSUE THREAD

**Issue by Hemric** [twilio/twilio-php#691]
### Issue Summary
When trying to create or update whatever conversations related resources along with attributes we have to encode them in json first. using php `json_encode()` function is the way to go. 

But by default php encodes utf8 characters and escapes slashes which is not accepted as valid JSON content by Twilio API as shown in the following example
```
curl -X POST https://conversations.twilio.com/v1/Users \
--data-urlencode "Identity=testJsonNotValidUser1" \
--data-urlencode 'Attributes={"url":"https:\/\/some.link.net", "firstName":"l\u00e9a"}' \
-u $ACCOUNT_ID:$ACCOUNT_TOKEN

{"code": 50304, "message": "Attributes not valid JSON", "more_info": "https://www.twilio.com/docs/errors/50304", "status": 400}% 
```

It would be really helpful to explain somewhere in the documentation what is valid JSON for Twilio. 

And advise php users to use the following flags

```
json_encode($attributes, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
```

An even better solution would be that twilio-php takes care of the encoding itself and users just provide an array in the attributes option ?

### Technical details:
* twilio-php version: 6.19.0
* php version: 8.0.3

**Comment by shwetha-manvinkurke** [comment]
@Hemric the API expects a json string. Here's my test code that worked:

```php
$attributes_arr = array("topic" => "hello®ø", "url" => "https://test.com");
$attributes = json_encode($attributes_arr);

$response = $client->conversations->v1->conversations->create([
    "attributes" => $attributes,
    "friendlyName" => "doesThisWork"
]);
```

Can you share your php code snippet?

**Comment by Hemric** [comment]
Hello @shwetha-manvinkurke,

I just tested your snippet it works fine with `conversations` !
It is when i try with `users` that this does not work anymore.

Here's my test code that didn't work:

```php
$attributes_arr = [
    'my_link' => 'https://some.link.net',
    'firstName' => 'léa'
];
$attributes = json_encode($attributes_arr); // {'my_link':'https:\/\/some.link.net','firstName':'l\u00e9a'}
$response = $client->conversations->v1->users->create('thisWillNotWork', ['attributes' => $attributes]);
// Twilio\Exceptions\RestException: [HTTP 400] Unable to create record: Attributes not valid JSON
```

And the one working:

```php
$attributes_arr = [
    'my_link' => 'https://some.link.net',
    'firstName' => 'léa'
];
$attributes = json_encode($attributes_arr, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
$response = $client->conversations->v1->users->create('thisWillWork', ['attributes' => $attributes]);
```

**Comment by shwetha-manvinkurke** [comment]
Thanks for the clarification! I reached out to the internal team who's going into look into this.

**Comment by shwetha-manvinkurke** [comment]
@Hemric This should now be fixed.
