### ISSUE TITLE
Sms History

### ISSUE THREAD

**Issue by ahmadkureshi** [twilio/twilio-php#695]
Hello, Team Twilio I need help, 
I want to retrieve all my SMS history which I sent and the number sent on my Twilio number. I cant find information about that API? please help how can I display all chat in history sent and receive messages like 

Sent : Hello 
Received : Hey How are  you
Sent: I am good.
Received: Whats up 

Please guide me.

**Comment by shwetha-manvinkurke** [comment]
Let us know if [this](https://www.twilio.com/docs/sms/api/message-resource?code-sample=code-read-list-all-messages&code-language=PHP&code-sdk-version=6.x) helps

**Comment by ahmadkureshi** [comment]
Hello @shwetha-manvinkurke  thank you for your reply but this will just give one way messages. we need to display both way messages like and show them as chat history.

We can use conversation but for SMS if our twilio number adds one participant into two conversations and a user reply to our Twilio number it will appear in two conversations? right

So is there any way from programmable SMS to retrieve incoming and outgoing conversations and sort them as time? hope you get my question. We want 1:1 conversation sorted as per the messages explained below:

p1: Hello   //  10/02/2021
p2: Hey How are you.  //  10/03/2021
p1: I am good you tell?  //  10/04/2021
p2: doing great   //  10/05/2021

**Comment by ahmadkureshi** [comment]
// sharing a solution for getting conversation in sequential order 
        // Also twilio has conversation option to create channel but if you try to create a channel with the number with whom you already have that will throw an error so I think this solution is good but make sure are using number of records filter as per needs. My issue got solved with the below code.
        
        $account_sid = getenv("TWILIO_SID");
        $auth_token = getenv("TWILIO_AUTH_TOKEN");
        $twilio_number = getenv("TWILIO_NUMBER");

        $twilio = new Client($account_sid, $auth_token);

        $outgoing_messages = $twilio->messages
            ->read([
                "from" => $twilio_number,
                'to'=>'XXXXXXXXX'
            ],
                500
            );

        $incoming_messages = $twilio->messages
            ->read([
                'from'=>'XXXXXXXXXX',
                "to" => $twilio_number

            ],
                500
            );

        $messages = array();
        foreach ($outgoing_messages as $outgoing_message){
            $message['status'] = $outgoing_message->status;
            $message['message'] = $outgoing_message->body;
            $message['time'] = $outgoing_message->dateSent;

            $messages[] = $message;
        }

        foreach ($incoming_messages as $incoming_message){
            $message['status'] = $incoming_message->status;
            $message['message'] = $incoming_message->body;
            $message['time'] = $incoming_message->dateSent;

            $messages[] = $message;
        }
        
         usort($messages, function($a, $b) {
            return $a['time'] <=> $b['time'];
        });

        dd($messages);

**Comment by shwetha-manvinkurke** [comment]
Don't think there is a programmable SMS API that fits your use case. Recommend going the conversation route and looks like you have that figured out.

**Comment by ahmadkureshi** [comment]
Hello, I just shared a solution in my last above comment. Closing this issue as the problem got solved. Possible with conversation too but we cant create two or more channels with the same number so it is better to go with filters and array merge.
