### ISSUE TITLE
I dont understand the verification service

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [twilio/twilio-php#696]
The doc explicit says:

```
Twilio deletes the verification SID once it’s:

expired (10 minutes)
approved
when the max attempts to check a code have been reached
```

I dont understand how can one use this service while this is the case, how I am supposed to know if the code has been approved or expired when both return the same error? How is this normal. I started integrating twilio 3 days ago and it has been frustating to say the least, I spent the last day just trying to understand how is this supposed to work and would appreciate any help.

I am successfully sending the code and verifying the sms, the problem is, lets say the user verified their phone and logged in, and they log out, and now they want to log in again (in a short span of time), as soon as they try to verify their phone, it will throw 404, for what reason? IT DOES NOT SAY FOR WHAT REASON , how is this acceptable?

Obivously, in the logs it says "its approved", but I need to know on the API response.

This is the logs
<img width="1809" alt="Screen Shot 2021-09-16 at 12 31 51" src="https://user-images.githubusercontent.com/29608698/133641276-89cefd32-b900-4f4f-a58f-712ac6d6ef2b.png">

This is what the api returns
<img width="1524" alt="Screen Shot 2021-09-16 at 12 32 08" src="https://user-images.githubusercontent.com/29608698/133641304-1d1a3ede-728d-4ac5-aa13-2f58de9ec746.png">

This is also what the api returns if the code was expired. To me this is just dumb, and thats why I am ASKING IF I am missing something. I just dont get it.

**Comment by oandrebecker** [comment]
👀

**Comment by shwetha-manvinkurke** [comment]
@diego-lipinski-de-castro understand your frustration, but from the helper library perspective, we return what the underlying API returns. I suggest you reach out to [support](https://support.twilio.com/hc/en-us) for resolution.
