### ISSUE TITLE
Deprecation on `ArrayAccess::offsetGet`

### ISSUE THREAD

**Issue by ahma0942** [twilio/twilio-php#712]
https://github.com/twilio/twilio-php/blob/d4a5ad22e761a14c5e355debb88a6f17640b247c/src/Twilio/Values.php#L62

Getting deprecation link on this. You forgot to add return type for the `offsetGet` method:
`    public function offsetGet($offset): mixed {`

**Comment by JenniferMah** [comment]
Hi @ahma0942!
Thanks for bringing this to our attention. This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog. Please feel free to open a PR with this fix and we will review it.

**Comment by ahma0942** [comment]
You're welcome @JenniferMah
I've opened a PR :+1:

**Comment by shwetha-manvinkurke** [comment]
Fixed by https://github.com/twilio/twilio-php/pull/713
