### ISSUE TITLE
Is it possible to make a real call from agent to user 

### ISSUE THREAD

**Issue by pratikraman-dev** [twilio/twilio-php#715]
When ever im trying to make outbound call its transferring me to programmable voice o want to make a voice call from my twilio phone number to another customers is it possible with twilio. to make a call with real voice from agent to customer

**Comment by JenniferMah** [comment]
Hi @pratikraman-dev! Please check out the [programmable voice docs](https://www.twilio.com/docs/voice/make-calls?code-sample=code-make-an-outbound-call-to-a-phone-number&code-language=PHP&code-sdk-version=6.x). If you still need help, please [file a support ticket](https://twilio.com/help/contact).
