### ISSUE TITLE
Incorrect type information in Twilio\Rest\Api\V2010\Account\MessageInstance

### ISSUE THREAD

**Issue by DaveLiddament** [twilio/twilio-php#727]
### Issue Summary

There is incorrect type information for the [MessageInstance::$errorCode](https://github.com/twilio/twilio-php/blob/68aa5dd58450d3b449c83138567ecfca93955ed9/src/Twilio/Rest/Api/V2010/Account/MessageInstance.php#L38) property.

The type hint suggests it will always be an int:
```
 @property int $errorCode
```

I'm getting TypeErrors, it seems that `$errorCode` can also be `null`.

Please can you update the docblock to the correct type: 
```
 @property int|null $errorCode
```

As the use of static analysis tools is increasing it is quite important that type information is correct. 

Thanks

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the **issue summary** will help it move up the backlog.

**Comment by DaveLiddament** [comment]
@childish-sambino I'm happy to provide a PR for this. Can you confirm if [MessageInstance](https://github.com/twilio/twilio-php/blob/68aa5dd58450d3b449c83138567ecfca93955ed9/src/Twilio/Rest/Api/V2010/Account/MessageInstance.php) is autogenerated? I see this comment at the top which suggests it might be:

```
/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0
 * /       /
 */
```

If it is auto generated please can you point me in the direction of how to update the source data. 
If it is NOT auto generated then let me know and I'll supply a fix to this file. 

Thanks
