### ISSUE TITLE
Usage Guide Syntax mismatches (Documentation)

### ISSUE THREAD

**Issue by d-miles** [twilio/twilio-php#729]
### Issue Summary
Wasn't sure where to report an error in the documentation, and thought this might be a better place than through a support ticket? I was looking for a repository to perhaps send a pull request but couldn't find one.

The [Exceptions area of the Usage Guide](https://www.twilio.com/docs/libraries/php/usage-guide#exceptions) page has a bunch of instances of invalid PHP syntax being used and/or mismatched Twilio method names. This is perhaps due to them being either generated or copied from documentation for other language's libraries. 

1. In the first/second ([Twilio Client](https://www.twilio.com/docs/libraries/php/usage-guide#twilio-client)), and fourth ([TwilioException](https://www.twilio.com/docs/libraries/php/usage-guide#twilioexception)) examples:
```php
call = $client->account->calls
                  ->get("CAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
```
should be `$call = ...`

2. The first/second ([Twilio Client](https://www.twilio.com/docs/libraries/php/usage-guide#twilio-client), and third ([CurlClient](https://www.twilio.com/docs/libraries/php/usage-guide#curlclient)) examples have the same error:
```php
echo $e.get_code();
```
should be `$e->get_code();` -- though I'm not sure if `get_code()` is the correct method name either. If v4.x/v5.x exception classes are anything like v6.x exception classes, then this should also be `getCode()` or `getMessage()`.

3. [TwimlException](https://www.twilio.com/docs/libraries/php/usage-guide#twimlexception):
```php
echo $e
```
should be `$e->getCode();` or `$e->getMessage();`

4. [TwilioException](https://www.twilio.com/docs/libraries/php/usage-guide#twilioexception) recommends catching `TwilioException` and calling `$e->getStatusCode()`; this method is only available on `RestException` though.

Hope this helps improve your documentation! 😄

**Comment by childish-sambino** [comment]
Thanks for the call out. The exception handling docs work for both 5.x and 6.x. I've submitted the changes for internal review.

**Comment by rakatyal** [comment]
The docs have been updated. Please let us know if we can help with anything else.
