### ISSUE TITLE
OpenSSL SSL_connect: Connection reset by peer in connection to lookups.twilio.com:443

### ISSUE THREAD

**Issue by axelthat** [twilio/twilio-php#737]
### Issue Summary
Using lookups API results in openssl error. This doesn't happen all the time. It happens randomly.

### Steps to Reproduce
1. Since the error occurs randomly, run the following code until you see the error. I get error after running the code 2-3 times.

### Code Snippet
```php
$twilio = new \Twilio\Rest\Client(
    config('twilio.sid'),
    config('twilio.auth_token'),
);

$phoneMeta = $twilio->lookups->v1->phoneNumbers(
    '+12196183229'
)->fetch(["type" => ["carrier"]]);
```

### Exception/Log
```
Twilio\Exceptions\EnvironmentException
OpenSSL SSL_connect: Connection reset by peer in connection to lookups.twilio.com:443
```

<img width="801" alt="Screen Shot 2022-06-03 at 3 02 00 PM" src="https://user-images.githubusercontent.com/31353695/171826227-7ced6249-54dd-46be-9c50-903d570ede4b.png">

### Technical details:
* twilio-php version: ^6.16
* php version: 8.0.18

**Comment by claudiachua** [comment]
Hi @axelthat, I've replicated your code and tested it but was unable to verify the error that you are receiving. I have added this to the backlog for further investigation. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by axelthat** [comment]
Hello @claudiachua ! This doesn't happen anymore.
