### ISSUE TITLE
Verify otp backward compatibility broken with v.6.39.0

### ISSUE THREAD

**Issue by hashcode7** [twilio/twilio-php#740]
### Issue Summary
Latest change breaks verify sms. Below code does not work anymore. 

### Exception/Log
Error occurred: Twilio\Rest\Verify\V2\Service\VerificationCheckList::create(): Argument #1 ($options) must be of type array, string given, called in /var/task/app/Utils/SmsVerify.php on line 44

### Technical details:
* twilio-php version: 6.39.0
* php version: ^8.0

<img width="1371" alt="Screen Shot 2022-07-18 at 7 28 45 PM" src="https://user-images.githubusercontent.com/14336739/179634067-f2bdcb63-0451-46b5-b7dd-0988250c0344.png">

6.39.0 changelog does mention this breaking change but not expected this in a minor release.

### Code Snippet
The following used to work but breaks now.  Below taken from twilio docs. 
https://www.twilio.com/docs/verify/api/verification-check

```php
# paste code here
$verification_check = $twilio->verify->v2->services("VAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
                                         ->verificationChecks
                                         ->create("1234", // code
                                                  ["to" => "+15017122661"]
                                         );

**Comment by childish-sambino** [comment]
Checking with the product team to see if this API change will be rolled back which was not marked as breaking. Otherwise, breaking changes to the API result in a minor version roll. Versioning guide here: https://github.com/twilio/twilio-php/blob/main/VERSIONS.md

**Comment by kendugu** [comment]
We're experiencing the same issue here as well.

**Comment by childish-sambino** [comment]
Doesn't look like this will be rolled back. I've updated the changelog and release notes to mark this specific change as breaking (which would produce a MINOR version roll).

Moving the `code` argument into `$options` block resolves this issue. Twilio Docs changes are still a WIP.

**Comment by childish-sambino** [comment]
Linked C# ticket with comment.

**Comment by ITopGun** [comment]
https://github.com/twilio/twilio-csharp/issues/622

**Comment by childish-sambino** [comment]
Closing as "won't fix". See my comments above on how to update your code with the latest version and versioning strategy.

**Comment by miken32** [comment]
Just for the record, changing method signatures in a minor version change is some bullshit. Just glad I spotted this before pushing out changes to production.
