### ISSUE TITLE
Can I remove the ability to send SMS texts from the majority of purchased numbers?

### ISSUE THREAD

**Issue by pravinkarmur** [twilio/twilio-php#741]
Hello,

Is there any way I can restrict only one number to send SMS from?
I mean how can I set capability on the purchased number?

Is this possible?
And if yes then what steps do I have to follow?

Thank you.

**Comment by JenniferMah** [comment]
In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).
