### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by PhantomWatson** [twilio/twilio-php#780]
These links are broken in [this repository's wiki](https://github.com/twilio/twilio-php/wiki):
- [Twilio PHP reference documentation](http://readthedocs.org/docs/twilio-php/en/latest/)
- [Debugging HTTP requests using the twilio-php library](https://github.com/twilio/twilio-php/wiki/Debugging)
- [Building the documentation locally](https://github.com/twilio/twilio-php/wiki/Documentation)

**Comment by AsabuHere** [comment]
Hi @PhantomWatson,
Thank you for the heads up!
This issue has been added to our internal backlog to be prioritised

Thanks,
Athira

**Comment by AsabuHere** [comment]
This issue is resolved now, replaced two broken links with the correct ones and removed one link which is not relevant
