### ISSUE TITLE
Composer Package Version Behind GitHub Release

### ISSUE THREAD

**Issue by BrookeDot** [twilio/twilio-php#782]
### Issue Summary
When installing `twilio/sdk` using composer the available version is a few versions behind. For example, currently the available version is 7.5.0 where the released version on GitHub is 7.7.0
https://packagist.org/packages/twilio/sdk

I get alerts when a new release is on GitHub and have been noticing the lag for a few months now. Previously the package and GitHub were in sync. 
 
### Steps to Reproduce
1. Install with composer `composer require twilio/sdk`
2. Note the installed version is 7.5.0
3. Not the released version on GitHub is 7.7.0   – https://github.com/twilio/twilio-php/releases/tag/7.7.0

### Technical details:
* twilio-php version: 7.5.0
* php version: 8.1.21

**Comment by BrookeDot** [comment]
Looks like it was updated on packagist. The timestamps reads: `Last update: 2023-07-28 11:16:57 UTC` which is after this issue was filed. I think something could be going on with the auto-update workflow but we can close this out and re-open if it reoccurs.

**Comment by BrookeDot** [comment]
Reopening, let's keep an eye on this for 7.8.0
https://github.com/twilio/twilio-php/releases/tag/7.8.0
https://packagist.org/packages/twilio/sdk

Let's see how long "auto update" takes to update the package.

**Comment by BrookeDot** [comment]
Same with 7.9.0

**Comment by BrookeDot** [comment]
Ok so looking at the update date, it looks like composer is updating monthly (`Last update: 2023-08-28 11:31:06 UTC`) around 11am UTC on the 28th of the month. 

It's possible that this is expected in which case updating the documentation seems like the next logical step. I was expecting the composer package to update with each new tag.

**Comment by BrookeDot** [comment]
@twilio-dx  not sure if that account is monitored for mentioned, but if so I would be curious on the above.

**Comment by mbabker** [comment]
FWIW I noticed it again with the 7.11.0 tag.  It wasn't part of my `composer outdated` list earlier in the week, it's there today, even though according to GitHub's releases tab it's been tagged for a week now.

**Comment by BrookeDot** [comment]
> it's there today, even though according to GitHub's releases tab it's been tagged for a week now.

Yeah, I stopped updating this ticket each time this happens :) but to summarize:

- Composer (  Packagist ) is only updating monthly, on the 28th of each month causing both `composer outdated` and `composer update` to not provide any builds published between the 29th of the previous month and 27th of the current month. 

I'm not sure who at @Twilio can look into this, but may submit a ticket directly to get more eyes on this or an opinion from those who maintain to this package.

**Comment by BrookeDot** [comment]
I have opened a support ticket up with Twilio encouraging a reply here. I'll report back once we know more.

**Comment by sbansla** [comment]
Thank you for noticing this, Yesterday we had new twilio version(https://github.com/twilio/twilio-php/releases/tag/7.11.1) released. But is is not available at packagist. Let me look into this.

**Comment by sbansla** [comment]
There was an issue with configured webhook, It has been resolved, Although currently I have updated the packagist manually. For final confirmation lets wait for next release.
Here is the latest version: https://packagist.org/packages/twilio/sdk#7.11.1

**Comment by BrookeDot** [comment]
Thanks for taking a look @sbansla and fixing the webhook. 🙇‍♀️ I will keep an eye on this for the next release and update this issue or close it out if things update automatically. Thanks again for your support!

**Comment by sbansla** [comment]
Webhook fix worked, I can see latest package here
https://packagist.org/packages/twilio/sdk#7.12.0

**Comment by sbansla** [comment]
Closing the issue as it is fixed, re-open it if you have question related to this issue.
