### ISSUE TITLE
Twilio SDK indicates MMS and SMS as false, even though the API confirms them as true for both

### ISSUE THREAD

**Issue by axelthat** [twilio/twilio-php#783]
### Issue Summary
I wanted to get the list of numbers for area code 215. However, the SDK returns MMS and SMS capabilities as false even though the API returns them as true.

### Steps to Reproduce

Returns MMS and SMS capabilities as false.
```
$twilio = new \Twilio\Rest\Client(config('twilio.sid'), config('twilio.auth_token'));
$availablePhoneNumbers = $twilio
    ->availablePhoneNumbers('US')
    ->local->read(['areaCode' => 215], 20);
```

Returns MMS and SMS capabilities as true.
```
curl "https://api.twilio.com/2010-04-01/Accounts/XXX/AvailablePhoneNumbers/US/Local.json?AreaCode=215&PageSize=20"
```

https://github.com/twilio/twilio-php/blob/09595314150128cd1f9dab4e37887e97b189f093/src/Twilio/Base/PhoneNumberCapabilities.php#L23-L24

If we take a look at API, the key "MMS" and "SMS" are uppercase, so I believe the above two lines should follow the same case?
```
{
   "address_requirements" : "none",
   "beta" : false,
   "capabilities" : {
      "MMS" : true,
      "SMS" : true,
      "voice" : true
   },
   ...
}
```

### Technical details:
* twilio-php version: 7.8.0
* php version: 8.2.8

**Comment by axelthat** [comment]
My very own mistake. I was doing this to validate capabilities: `collect($availableTwilioNumber->capabilities)->has(['MMS', 'SMS', 'voice'])` instead of `$ins->capabilities->getMms() && $ins->capabilities->getSms() && $ins->capabilities->getVoice()`.

**Comment by saintanger** [comment]
Well actually for me it always returns true on all of them. $ins->capabilities->getSms()
There is something wrong on the sdk for it
