### ISSUE TITLE
Beenish wants to pay 0 USD to have this issue fixed

### ISSUE THREAD

**Issue by ratroot** [twilio/twilio-php#784]
If you create an interaction with an SMS or WhatsApp participant that’s already in a conversation, the participant will not be added and the agent ends up with a conversation task with nobody else in it. 
 For more details visit [https://mintycode.io](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=818ee9fe-783e-4a4f-b266-e5b66f6706bb&owner=twilio&name=twilio-php)

**Comment by shengslogar** [comment]
Seems like spam. 🤮 https://github.com/search?q=mintycode.io&type=issues

**Comment by sbansla** [comment]
no update. closing the issue.
